export interface WorshipMeHelpSection{title:string;paragraphs:readonly string[];bullets?:readonly string[]}
export interface WorshipMeTutorialStep extends WorshipMeHelpSection{id:string}

export const WORSHIP_ME_TUTORIAL_STEPS:readonly WorshipMeTutorialStep[]=[
 {id:'goal',title:'THE GOAL',paragraphs:['Build the strongest following on the board. The game ends only when all remaining Village tiles are face up and at least one player has three of their own followers, including Priests, in their own Temple.','That Temple condition only triggers the ending. It does not automatically win the game. Compare every player’s total on-board followers; the greatest total wins. A highest-total tie remains unresolved under the current rule.']},
 {id:'round',title:'HOW A ROUND WORKS',paragraphs:['Each round has Placement, Resolution, then Production and end-of-round stages. Players complete Placement turns in turn order before the queued actions resolve.','A normal Placement turn gives two placements and allows at most one Smite. Extra Bless placements and Temple penalties can change that total. END TURN gives up your remaining placements.']},
 {id:'bless-tile',title:'BLESS TILE',paragraphs:['Choose BLESS TILE, then select a legal tile. Blessing face-down Village land reveals whether it is a Farm, Bakery, or Home.','Farms and Bakeries may receive improved production. An explicitly Blessed Home gains its special Bless contribution. Temples create special effects for the next round, so not every Bless behaves alike.']},
 {id:'bless-edge',title:'BLESS EDGE',paragraphs:['Bless Edge is directional: select the origin first, the destination second, then CONFIRM. Movement and cargo are chosen from the origin during Resolution; the destination never supplies the mover.','A legal choice may move your ordinary follower, your Priest, a Neutral, or—when permitted—an opponent-colored ordinary follower. Wheat or Bread may travel as cargo, and resource-only movement is possible when the rule permits it. CANCEL clears the unsubmitted selection.']},
 {id:'smite-tile',title:'SMITE TILE',paragraphs:['A successful Smite Tile can turn an empty revealed production tile face down, remove one Wheat or Bread when resources exist, and suppress that tile’s production for the round.','Smite never ejects a villager merely because the tile was Smited. When both Wheat and Bread can be removed, the resolving player chooses during Resolution. Temple Smite has its own next-round effect.']},
 {id:'smite-edge',title:'SMITE EDGE',paragraphs:['Choose SMITE EDGE, select two adjacent tiles, then CONFIRM. Unlike Bless Edge, the physical block is not directional: it is impassable in both directions for the round.','CANCEL clears the unsubmitted edge. A normal Placement turn allows at most one Smite total, whether Tile or Edge.']},
 {id:'temples-priests',title:'TEMPLES & PRIESTS',paragraphs:['Bless your own Temple for one extra Bless placement next round. Bless an opponent Temple to make its owner persistent first player beginning next round, until another opponent-Temple Bless replaces it. Smite your own Temple to reverse direction next round. Smite an opponent Temple to remove one placement from that player’s next Placement turn.','At end of round, three ordinary own-color villagers in a player’s Temple convert exactly one into a Priest: at most once per round and twice per player per game. The Priest moves to Village Square if capacity permits; otherwise it stays in the Temple. Priests count as followers, enhance Farms and Bakeries to Blessed production, and protect their tile and incident edges from opponents. They do not enhance Homes.']},
 {id:'production-victory',title:'PRODUCTION & WINNING',paragraphs:['A normal Farm makes 1 Wheat per occupant; a Blessed or Priest-enhanced Farm makes 2. A normal Bakery spends 2 Wheat for 1 Bread; a Blessed or Priest-enhanced Bakery spends 1. Production is limited by the applicable occupancy and available resources. Homes can contribute colors to the bag and trigger their own draw. After Home production, the game separately attempts one normal bag draw for each player.','Reveal all remaining Village land, satisfy the three-own-followers Temple trigger, then have the highest total follower count across the entire board. The triggering player does not automatically win.']},
];

export const WORSHIP_ME_HOW_TO_PLAY_SECTIONS:readonly WorshipMeHelpSection[]=[
 {title:'OBJECTIVE',paragraphs:['Build the strongest following on the board. The game-end trigger requires every remaining Village tile to be face up and at least one player to have three own followers, including Priests, in their own Temple.','The Temple condition only triggers the ending; it does not restrict who can win. Compare every player’s total on-board followers. The greatest total wins, while a highest-total tie remains unresolved under the current rule.']},
 {title:'ROUND STRUCTURE',paragraphs:['A round proceeds through Placement, Resolution, then Production and end-of-round processing. During Placement, each player completes their turn in order. The queued actions then resolve in placement order before production, Home events, draws, Priest creation, victory, cleanup, next-round Temple effects, and Village Square refill.']},
 {title:'PLACEMENT RULES',paragraphs:['A normal turn permits two placements and at most one Smite; END TURN stops remaining placements early. Extra Blesses and Temple penalties can alter the available total.'],bullets:['A tile token claims that tile against later opponents’ tile placements and placements on its incident edges.','Bless Edge claims its edge against later opponents.','Smite Edge claims its edge and both endpoint tiles against later opponents.','The same player cannot duplicate an edge or tile token. A Temple may be targeted only once per round.','An opposing Priest protects its tile and incident edges. The Priest’s owner may still target them.']},
 {title:'BLESS TILE',paragraphs:['Select BLESS TILE and a legal tile. Face-down Village land is revealed. Farms and Bakeries can gain improved production, explicitly Blessed Homes gain a special contribution, and Temples create next-round effects.']},
 {title:'BLESS EDGE',paragraphs:['Select the origin, then the adjacent destination, then CONFIRM. Direction matters. During Resolution, choose a legal mover and optional Wheat or Bread cargo from the origin. The destination never supplies the mover.','Legal outcomes can include your ordinary follower, your Priest, a Neutral, an opponent-colored ordinary follower under conversion rules, or resource-only movement when your color is present at both endpoints.']},
 {title:'SMITE TILE',paragraphs:['A successful Smite may turn an empty revealed production tile face down, remove one Wheat or Bread, and suppress production for the round. It never ejects a villager merely because the tile was Smited. If both resources are present, the resolving player chooses which one to remove.']},
 {title:'SMITE EDGE',paragraphs:['Select two adjacent tiles and CONFIRM. The edge is blocked in both directions for the round. A normal turn permits at most one Smite total across Smite Tile and Smite Edge.']},
 {title:'FARMS',paragraphs:['A normal Farm produces 1 Wheat per occupant. A Blessed or Priest-enhanced Farm produces 2 Wheat per occupant. A Smited Farm produces nothing that round. Resources do not consume pawn capacity.']},
 {title:'BAKERIES',paragraphs:['A normal Bakery spends 2 Wheat for 1 Bread. A Blessed or Priest-enhanced Bakery spends 1 Wheat for 1 Bread. Output is constrained by occupants and available Wheat. A Smited Bakery produces nothing that round.']},
 {title:'HOMES',paragraphs:['A Home production event requires exactly two occupants and the configured Bread cost, currently 1 Bread. The Bread is consumed. If both occupants are the same color, that color contributes one token to the new-villager bag. If they are different colors, each color contributes one token. An explicitly Blessed Home adds one additional token of the Blessing player’s color; it does not replace the occupants’ contribution.','The Home then performs its own draw from the bag toward Village Square. If the Square is full, the drawn follower remains in the bag. Priests do not enhance Homes, do not passively Bless them, and grant no Home bonus.']},
 {title:'NORMAL END-ROUND BAG DRAW',paragraphs:['After Home production and its Home-triggered draws resolve, the game separately attempts one normal draw from the new-villager bag for each player at the end of the round. If a follower is drawn and Village Square has room, it enters the Square. If the bag is empty, no follower is drawn; if the Square is full, the drawn follower remains in the bag.']},
 {title:'TEMPLES',paragraphs:[],bullets:['Bless your own Temple: gain one extra Bless placement next round.','Bless an opponent Temple: that Temple’s owner becomes persistent first player next round until another opponent-Temple Bless replaces it.','Smite your own Temple: reverse play direction beginning next round.','Smite an opponent Temple: that player loses one placement on their next Placement turn.']},
 {title:'PRIESTS',paragraphs:['At end of round, three ordinary own-color villagers in a player’s Temple convert exactly one into a Priest. Creation is limited to once per round and two Priests per player per game. The Priest moves to Village Square if capacity permits; otherwise it remains in the Temple.','Priests count as followers, enhance Farms and Bakeries without stacking with an explicit Bless, and protect their tile and incident edges from opposing placement. They do not enhance Homes.']},
 {title:'VILLAGE SQUARE & NEUTRALS',paragraphs:['At the round boundary, add at most one Neutral when Village land remains face down, no player-colored villager or Priest occupies the Square, the Square has room, and the Neutral cap permits it. No automatic Neutral is added after every Village tile is face up.','The global Neutral cap is 10 across the board and bag.']},
 {title:'CAPACITY',paragraphs:['Farm, Bakery, Home, and Temple tiles hold four pawns. Village Square capacity equals the player count plus two. Resources do not consume pawn capacity.']},
 {title:'RESOLUTION',paragraphs:['Queued actions resolve in their placed order against the current board. Bless Edge movement and cargo choices, and Smite resource choices, are made when their action resolves. If no legal Bless Edge choice remains, it resolves as a logged no-op.']},
 {title:'VICTORY',paragraphs:['All remaining Village tiles must be face up and at least one player must have three own followers, including Priests, in their own Temple. Then compare every player’s total on-board followers. The greatest total wins.','Getting three followers into a Temple does not automatically win; it only helps trigger the final comparison. A highest-total tie remains unresolved.']},
 {title:'GAME CONTROLS',paragraphs:[],bullets:['BLESS TILE — select a legal tile and place a Bless action.','BLESS EDGE — select origin, then destination; direction matters.','SMITE TILE — place the turn’s Smite on a legal tile.','SMITE EDGE — place the turn’s Smite on an adjacent edge.','END TURN — give up remaining Placement actions.','CONFIRM — submit a selected edge after both endpoints are chosen.','CANCEL — clear an unsubmitted edge selection.','Bless Edge resolution choices — choose the legal follower and cargo movement when prompted.','WHEAT / BREAD — choose which resource a pending Smite removes.','REFRESH GAME — request the latest trusted game view when synchronization is unavailable or stale.','ROOM CHAT / SEND — send a room message without changing game state.','LEAVE GAME — permanently hand the departing human’s canonical seat to a Balanced AI, remove membership, and leave that seat unreclaimable for this game.','RETURN TO LOBBY — after game over, the host returns the same room to its lobby for another match while preserving its identity and applicable metadata.','HOW TO PLAY — open this reference.']},
];

export type WorshipMeHelpMode='tutorial'|'guide';
export interface WorshipMeHelpState{mode?:WorshipMeHelpMode;tutorialStep:number;roomCode?:string}
export interface WorshipMeHelpController{readonly state:WorshipMeHelpState;enterActiveRoom(roomCode:string):void;openGuide(roomCode?:string):void;closeGuide():void;replayTutorial(roomCode?:string):void;back():void;next():void;skip():void;finish():void}
type SessionStorageLike=Pick<Storage,'getItem'|'setItem'>;
export const worshipMeTutorialStorageKey=(roomCode:string)=>`ngs.worshipMe.tutorial.v1:${roomCode.trim().toUpperCase()}`;
const availableSessionStorage=():SessionStorageLike|undefined=>{try{return globalThis.sessionStorage}catch{return undefined}};

export function createWorshipMeHelpController(storage:SessionStorageLike|undefined=availableSessionStorage()):WorshipMeHelpController{
 let state:WorshipMeHelpState={tutorialStep:0},activeRoom:string|undefined;const seen=new Set<string>();
 const normalized=(roomCode?:string)=>roomCode?.trim().toUpperCase()||undefined;
 const stored=(roomCode:string)=>{if(seen.has(roomCode))return true;try{if(storage?.getItem(worshipMeTutorialStorageKey(roomCode))==='seen'){seen.add(roomCode);return true;}}catch{}return false;};
 const markSeen=()=>{const roomCode=state.roomCode;if(!roomCode)return;seen.add(roomCode);try{storage?.setItem(worshipMeTutorialStorageKey(roomCode),'seen');}catch{}}
 const dismiss=()=>{markSeen();state={...state,mode:undefined};};
 return{
  get state(){return{...state};},
  enterActiveRoom(roomCode){const room=normalized(roomCode);if(!room||activeRoom===room)return;activeRoom=room;state={tutorialStep:0,roomCode:room,mode:stored(room)?undefined:'tutorial'};},
  openGuide(roomCode){state={...state,roomCode:normalized(roomCode)??state.roomCode,mode:'guide'};},
  closeGuide(){state={...state,mode:undefined};},
  replayTutorial(roomCode){state={roomCode:normalized(roomCode)??state.roomCode,tutorialStep:0,mode:'tutorial'};},
  back(){if(state.mode==='tutorial')state={...state,tutorialStep:Math.max(0,state.tutorialStep-1)};},
  next(){if(state.mode!=='tutorial')return;if(state.tutorialStep>=WORSHIP_ME_TUTORIAL_STEPS.length-1){dismiss();return;}state={...state,tutorialStep:state.tutorialStep+1};},
  skip(){if(state.mode==='tutorial')dismiss();},
  finish(){if(state.mode==='tutorial')dismiss();},
 };
}

const MODAL_FOCUSABLE='button:not([disabled]):not([hidden]),a[href]:not([hidden]),input:not([disabled]):not([hidden]),select:not([disabled]):not([hidden]),textarea:not([disabled]):not([hidden]),[tabindex]:not([tabindex="-1"]):not([hidden])';
const canReceiveModalFocus=(element:HTMLElement)=>{if(element.hidden||element.closest('[inert],[hidden]'))return false;const style=globalThis.getComputedStyle?.(element);return !style||style.display!=='none'&&style.visibility!=='hidden';};
export interface WorshipMeHelpModalBinding{release():void}
export function restoreWorshipMeHelpFocus(opener:HTMLElement|undefined){if(!opener?.isConnected||opener.inert||opener.closest('[inert]')||!opener.matches(MODAL_FOCUSABLE))return false;opener.focus();return document.activeElement===opener;}
export function bindWorshipMeHelpModal(application:HTMLElement,overlay:HTMLElement,dialog:HTMLElement,initialFocusSelector?:string):WorshipMeHelpModalBinding{
 application.inert=true;
 const focusable=()=>[...dialog.querySelectorAll<HTMLElement>(MODAL_FOCUSABLE)].filter(canReceiveModalFocus);
 const onKeyDown=(event:KeyboardEvent)=>{if(event.key!=='Tab')return;const controls=focusable();if(!controls.length){event.preventDefault();dialog.focus();return;}const first=controls[0],last=controls.at(-1)!;if(event.shiftKey&&(document.activeElement===first||!dialog.contains(document.activeElement))){event.preventDefault();last.focus();}else if(!event.shiftKey&&(document.activeElement===last||!dialog.contains(document.activeElement))){event.preventDefault();first.focus();}};
 overlay.addEventListener('keydown',onKeyDown);
 const preferred=initialFocusSelector?dialog.querySelector<HTMLElement>(initialFocusSelector):undefined;(preferred&&canReceiveModalFocus(preferred)?preferred:focusable()[0]??dialog).focus();
 return{release(){overlay.removeEventListener('keydown',onKeyDown);application.inert=false;}};
}
