import type {BotStrategy,GameState,Player,VillagerColor} from '../engine/types';
const colors:VillagerColor[]=['red','purple','blue','cyan','green','yellow','orange','black','neutral'];
const strategyNames:Record<BotStrategy,string>={random:'Random AI',growth:'Growth AI',templeRush:'Temple Rush AI',balanced:'Balanced AI'};
export function boardTotals(s:GameState){return Object.fromEntries(colors.map(color=>[color,s.board.reduce((n,c)=>n+c.villagers.filter(v=>v===color).length+c.priests.filter(v=>v===color).length,0)])) as Record<VillagerColor,number>}
export function playerControlLabel(p:Player){return p.control==='ai'?strategyNames[p.botStrategy??'random']:'Human'}
export function winnerPlayer(s:GameState){return s.winnerId?s.players.find(p=>p.id===s.winnerId):undefined}
export function renderSidebar(s:GameState,actingBotId?:string){
 const current=s.players.find(p=>p.id===s.turnOrder[s.currentPlayerIndex]);
 const resolver=s.players.find(p=>p.id===s.pendingResolution?.playerId),winner=winnerPlayer(s);
 const shown=s.phase==='gameOver'?winner:resolver??current,totals=boardTotals(s),relevant=[...s.players.map(p=>p.color),'neutral'] as VillagerColor[],bot=!!actingBotId;
 const heading=s.phase==='gameOver'?`${winner?.name??'Unknown player'} wins!`:s.pendingResolution?`${resolver?.name}: resolve queued action`:`${current?.name} · ${cap(s.phase)}`;
 const identity=shown?`<span class="player-badge" style="--player-color:${shown.color}">${shown.color}</span> <small class="control-label">${playerControlLabel(shown)}</small>`:'';
 const actionControls=s.phase==='placement'?`<button data-command="end-turn" ${bot?'disabled':''}>End placements early</button>`:'<button data-command="end-turn" hidden disabled>End placements</button>';
 const queue=`<section class="status-block queue-block"><h3>Resolution Queue</h3><ol class="queue">${s.actionQueue.map((q,i)=>{const p=s.players.find(p=>p.id===q.placement.playerId)!,status=i<s.resolutionIndex?'Resolved':i===s.resolutionIndex&&s.phase==='resolution'?'Resolving':'Pending',target=q.placement.type==='placeTile'?q.placement.cellId:q.placement.kind==='bless'?`${q.placement.from} → ${q.placement.to}`:`${q.placement.a}–${q.placement.b}`;return`<li class="${status.toLowerCase()}"><b>#${q.sequence}</b> <span style="color:${p.color}">${p.name} (${cap(p.color)})</span><br>${cap(q.placement.kind)} · ${q.placement.type==='placeTile'?'Tile':'Edge'} · ${target}<small>${status}</small></li>`}).join('')||'<li class="empty">No placements queued</li>'}</ol></section>`;
 const followers=`<section class="status-block follower-block"><h3>On-board Followers</h3>${relevant.map(x=>`<div class="total"><i class="pawn" style="--c:${x}"></i><span>${cap(x)}</span><b>${totals[x]}</b></div>`).join('')}</section>`;
 return `<aside><h1>Worship Me!</h1><p>Round ${s.round} · ${s.direction===1?'Clockwise':'Counter-clockwise'} · ${cap(s.phase)}</p><h2>${heading} ${identity}</h2>${bot?'<p class="ai-acting">AI is acting…</p>':''}${actionControls}<div class="status-grid">${queue}${followers}</div><section class="priest-status"><h3>Priests</h3>${s.players.map(x=>`<p><i class="pawn priest" style="--c:${x.color}">P</i> ${x.name}: ${x.priestsCreated} / 2</p>`).join('')}</section><div class="utility-controls"><button data-command="save">Save</button><button data-command="resume">Resume</button><button data-command="export">Export Game State</button><button data-command="export-playbyplay">Export Play-by-Play</button><label>Import JSON<input data-command="import" type="file" accept="application/json"></label><button data-command="new">New Game</button><button data-command="bot-delay">${bot?'Toggle':'Disable'} AI delay</button></div><details><summary>Debug</summary><pre>${escapeHtml(JSON.stringify(s,null,2))}</pre></details></aside>`;
}
const cap=(x:string)=>x[0].toUpperCase()+x.slice(1);const escapeHtml=(x:string)=>x.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]!));
