import {describe,expect,it} from 'vitest';import {getPolicy} from '../src/games/worship-me/ai/policies';import {marginalProduction,scoreActionDetailed,scoreResolutionOption,weights} from '../src/games/worship-me/ai/scoring';import {blessEdgeOptions} from '../src/games/worship-me/engine/resolution';import type {BlessEdgePlacement,GameState} from '../src/games/worship-me/engine/types';import {game,player,reveal} from './helpers';
function edge(s:GameState,a:string,b:string):BlessEdgePlacement{return{type:'placeEdge',from:a,to:b,kind:'bless',playerId:player(s).id}}
function pending(s:GameState,a:string,b:string){const action=edge(s,a,b),options=blessEdgeOptions(s,action);s.phase='resolution';s.pendingResolution={type:'blessEdgeMove',queueIndex:0,playerId:player(s).id,options};s.actionQueue=[{sequence:1,placement:action}];return options}
describe('strategy-aware placement and resolution',()=>{
 it('A: TempleRush ahead in followers values using its third Temple follower to trigger the end',()=>{const s=game(),p=player(s),t=s.board.find(c=>c.id===p.templeCellId)!,near=reveal(s,'0,1');for(const c of s.board)if(c.visibleKind==='hidden')c.visibleKind=c.hiddenKind!;t.villagers.push(p.color,p.color);near.villagers.push(p.color,p.color,p.color);const inward=scoreResolutionOption(s,p.id,{from:near.id,to:t.id,moverRole:'ordinary'},weights.templeRush);expect(inward.components.endTriggerValue).toBeGreaterThan(0)});
 it('B: TempleRush behind in followers strongly avoids triggering its own loss',()=>{const s=game(),p=player(s),opp=player(s,1),t=s.board.find(c=>c.id===p.templeCellId)!,near=reveal(s,'0,1');for(const c of s.board)if(c.visibleKind==='hidden')c.visibleKind=c.hiddenKind!;t.villagers.push(p.color,p.color);near.villagers.push(p.color);for(const c of s.board.filter(c=>c.visibleKind!=='temple').slice(0,3))c.villagers.push(opp.color,opp.color,opp.color);const inward=scoreResolutionOption(s,p.id,{from:near.id,to:t.id,moverRole:'ordinary'},weights.templeRush);expect(inward.components.endTriggerValue).toBeLessThan(-100)});
 it('C: Growth sends Wheat into a Bakery',()=>{const s=game(),p=player(s),farm=reveal(s,'1,1'),bakery=reveal(s,'1,2','bakery');farm.wheat=1;farm.villagers.push(p.color);bakery.villagers.push(p.color);const options=pending(s,farm.id,bakery.id),choice=getPolicy('growth').choosePendingResolution(s),selected=options[(choice.decision as {optionIndex:number}).optionIndex];expect(selected).toMatchObject({from:farm.id,to:bakery.id,resource:'wheat'})});
 it('D: Growth sends Bread into an exactly-two-villager Home when resource-only transfer is legal',()=>{const s=game(),p=player(s),source=reveal(s,'1,1','bakery'),home=reveal(s,'1,2','home');source.bread=1;source.villagers.push(p.color);home.villagers.push(p.color,p.color);const options=pending(s,source.id,home.id),choice=getPolicy('growth').choosePendingResolution(s),selected=options[(choice.decision as {optionIndex:number}).optionIndex];expect(selected).toMatchObject({from:source.id,to:home.id,resource:'bread',resourceOnly:true})});
 it('E: Growth preserves a productive exactly-two-villager Home',()=>{const s=game(),p=player(s),home=reveal(s,'1,1','home'),other=reveal(s,'1,2');home.villagers.push(p.color,p.color);home.bread=1;const leave=scoreResolutionOption(s,p.id,{from:home.id,to:other.id,moverRole:'ordinary'},weights.growth),stay=scoreActionDetailed(s,{type:'placeTile',cellId:home.id,kind:'bless',playerId:p.id},weights.growth);expect(stay.score).toBeGreaterThan(leave.score)});
 it('F: after all land is revealed, an AI ahead values a favorable end trigger',()=>{const s=game(),p=player(s),t=s.board.find(c=>c.id===p.templeCellId)!,near=s.board.find(c=>c.id==='0,1')!;for(const c of s.board)if(c.visibleKind==='hidden')c.visibleKind=c.hiddenKind!;t.villagers.push(p.color,p.color);near.villagers.push(p.color,p.color,p.color);const toward=scoreResolutionOption(s,p.id,{from:near.id,to:t.id,moverRole:'ordinary'},weights.balanced),side=s.board.find(c=>c.id==='1,1')!,routine=scoreResolutionOption(s,p.id,{from:near.id,to:side.id,moverRole:'ordinary'},weights.balanced);expect(toward.score).toBeGreaterThan(routine.score+50)});
 it('G: a productive opponent Home is a competitive Smite target',()=>{const s=game(),p=player(s),opp=player(s,1),home=reveal(s,'1,1','home'),empty=reveal(s,'1,2');home.villagers.push(opp.color,opp.color);home.bread=1;const productive=scoreActionDetailed(s,{type:'placeTile',cellId:home.id,kind:'smite',playerId:p.id},weights.balanced),irrelevant=scoreActionDetailed(s,{type:'placeTile',cellId:empty.id,kind:'smite',playerId:p.id},weights.balanced);expect(productive.score).toBeGreaterThan(irrelevant.score+40)});
 it('H: opponent Temple Smite is valuable only when delaying that trigger protects the AI',()=>{const s=game(),p=player(s),opp=player(s,1),temple=s.board.find(c=>c.id===opp.templeCellId)!;for(const c of s.board)if(c.visibleKind==='hidden')c.visibleKind=c.hiddenKind!;temple.villagers.push(opp.color,opp.color);for(const c of s.board.filter(c=>c.visibleKind!=='temple').slice(0,3))c.villagers.push(opp.color,opp.color);const dangerous=scoreActionDetailed(s,{type:'placeTile',cellId:temple.id,kind:'smite',playerId:p.id},weights.templeRush);for(const c of s.board.filter(c=>c.visibleKind!=='temple').slice(3,7))c.villagers.push(p.color,p.color,p.color);const beneficialOpponentTrigger=scoreActionDetailed(s,{type:'placeTile',cellId:temple.id,kind:'smite',playerId:p.id},weights.templeRush);expect(dangerous.score).toBeGreaterThan(beneficialOpponentTrigger.score+100)});
 it('scores Bakery Bless by actual marginal Bread, not theoretical capacity',()=>{const s=game(),p=player(s),bakery=reveal(s,'1,1','bakery');bakery.villagers.push(p.color,p.color,p.color,p.color);expect(marginalProduction(bakery,s,'bless')).toBe(0);const empty=scoreActionDetailed(s,{type:'placeTile',cellId:bakery.id,kind:'bless',playerId:p.id},weights.growth);bakery.wheat=2;expect(marginalProduction(bakery,s,'bless')).toBe(1);const supplied=scoreActionDetailed(s,{type:'placeTile',cellId:bakery.id,kind:'bless',playerId:p.id},weights.growth);expect(supplied.score).toBeGreaterThan(empty.score)});
 it('scores Home Bless and Smite only when an actual birth qualifies',()=>{const s=game(),p=player(s),opp=player(s,1),home=reveal(s,'1,1','home');home.villagers.push(opp.color,opp.color);const noBread=scoreActionDetailed(s,{type:'placeTile',cellId:home.id,kind:'bless',playerId:p.id},weights.balanced);home.bread=1;const bless=scoreActionDetailed(s,{type:'placeTile',cellId:home.id,kind:'bless',playerId:p.id},weights.balanced),smite=scoreActionDetailed(s,{type:'placeTile',cellId:home.id,kind:'smite',playerId:p.id},weights.balanced);expect(bless.score).toBeGreaterThan(noBread.score);expect(smite.components.productionPreventedValue).toBeGreaterThan(0)});
 it('scores Farm → Bakery separately from Bakery → Farm',()=>{const s=game(),p=player(s),farm=reveal(s,'1,1'),bakery=reveal(s,'1,2','bakery');farm.villagers.push(p.color);bakery.villagers.push(p.color);farm.wheat=1;const forward=scoreActionDetailed(s,{type:'placeEdge',from:farm.id,to:bakery.id,kind:'bless',playerId:p.id},weights.growth),reverse=scoreActionDetailed(s,{type:'placeEdge',from:bakery.id,to:farm.id,kind:'bless',playerId:p.id},weights.growth);expect(forward.score).toBeGreaterThan(reverse.score)});
 it('scores only one removable resource for Smite regardless of Farm stockpile',()=>{const s=game(),p=player(s),farm=reveal(s,'1,1');farm.villagers.push(player(s,1).color);farm.wheat=1;const one=scoreActionDetailed(s,{type:'placeTile',cellId:farm.id,kind:'smite',playerId:p.id},weights.balanced);farm.wheat=100;const hundred=scoreActionDetailed(s,{type:'placeTile',cellId:farm.id,kind:'smite',playerId:p.id},weights.balanced);expect(one.components.resourceRemovalValue).toBe(hundred.components.resourceRemovalValue);expect(hundred.score).toBe(one.score)});
 it('does not value a Bakery Smite as though all stored resources disappear',()=>{const s=game(),p=player(s),bakery=reveal(s,'1,1','bakery');bakery.wheat=20;bakery.bread=5;const stocked=scoreActionDetailed(s,{type:'placeTile',cellId:bakery.id,kind:'smite',playerId:p.id},weights.balanced);bakery.wheat=1;bakery.bread=1;const small=scoreActionDetailed(s,{type:'placeTile',cellId:bakery.id,kind:'smite',playerId:p.id},weights.balanced);expect(stocked.components.resourceRemovalValue).toBe(small.components.resourceRemovalValue);expect(stocked.components.productionPreventedValue).toBe(small.components.productionPreventedValue)});
 it('values releasing Square capacity when own followers are trapped in the bag',()=>{const s=game(),p=player(s),square=s.board.find(c=>c.visibleKind==='square')!,to=reveal(s,'2,3');square.villagers=Array(s.players.length+2).fill('neutral');s.newVillagerBag=Array(6).fill(p.color);const option={from:square.id,to:to.id,neutral:true,moverColor:'neutral' as const},congested=scoreResolutionOption(s,p.id,option,weights.growth);s.newVillagerBag=[];const emptyBag=scoreResolutionOption(s,p.id,option,weights.growth);expect(congested.components.populationReleaseValue).toBeGreaterThan(0);expect(congested.score).toBeGreaterThan(emptyBag.score+40)});
 it('Growth develops Temple pressure after reveal while ahead',()=>{const s=game(),p=player(s),opp=player(s,1),temple=s.board.find(c=>c.id===p.templeCellId)!,near=reveal(s,'0,1'),bakery=reveal(s,'1,1','bakery'),home=reveal(s,'1,2','home');for(const c of s.board)if(c.visibleKind==='hidden')c.visibleKind=c.hiddenKind!;near.villagers.push(p.color,p.color,p.color);bakery.villagers.push(p.color);bakery.bread=1;home.villagers.push(p.color,p.color);s.board.find(c=>c.visibleKind==='farm')!.villagers.push(opp.color);const templeMove=scoreResolutionOption(s,p.id,{from:near.id,to:temple.id,moverRole:'ordinary',moverColor:p.color},weights.growth),bread=scoreResolutionOption(s,p.id,{from:bakery.id,to:home.id,resourceOnly:true,resource:'bread'},weights.growth);expect(templeMove.components.terminalPressure).toBeGreaterThan(0);expect(templeMove.score).toBeGreaterThan(bread.score)});
 it('Growth avoids a losing third-Temple trigger but favors it while ahead',()=>{const s=game(),p=player(s),opp=player(s,1),temple=s.board.find(c=>c.id===p.templeCellId)!,near=reveal(s,'0,1');for(const c of s.board)if(c.visibleKind==='hidden')c.visibleKind=c.hiddenKind!;temple.villagers.push(p.color,p.color);near.villagers.push(p.color);for(const c of s.board.filter(c=>c.visibleKind!=='temple').slice(0,4))c.villagers.push(opp.color,opp.color,opp.color);const behind=scoreResolutionOption(s,p.id,{from:near.id,to:temple.id,moverRole:'ordinary',moverColor:p.color},weights.growth);for(const c of s.board) c.villagers=c.villagers.filter(v=>v!==opp.color);near.villagers.push(p.color,p.color,p.color);const ahead=scoreResolutionOption(s,p.id,{from:near.id,to:temple.id,moverRole:'ordinary',moverColor:p.color},weights.growth);expect(behind.components.endTriggerValue).toBeLessThan(0);expect(ahead.score).toBeGreaterThan(behind.score+100)});
});
