import {readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {describe,expect,it,vi} from 'vitest';
// @vitest-environment happy-dom
import {bindWorshipMeHelpModal,createWorshipMeHelpController,restoreWorshipMeHelpFocus,WORSHIP_ME_HOW_TO_PLAY_SECTIONS,WORSHIP_ME_TUTORIAL_STEPS,worshipMeTutorialStorageKey} from '../src/games/worship-me/ui/howToPlay';

const repositoryRoot=(process as unknown as {cwd():string}).cwd(),contentSource=readFileSync(resolve(repositoryRoot,'src/games/worship-me/ui/howToPlay.ts'),'utf8'),css=readFileSync(resolve(repositoryRoot,'src/games/worship-me/ui/howToPlay.css'),'utf8'),shell=readFileSync(resolve(repositoryRoot,'src/platform/shell.ts'),'utf8'),migrations=resolve(repositoryRoot,'supabase/migrations');
const memoryStorage=()=>{const values=new Map<string,string>();return{values,getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value);}};};
const tutorialText=WORSHIP_ME_TUTORIAL_STEPS.flatMap(step=>[step.title,...step.paragraphs,...(step.bullets??[])]).join(' '),guideText=WORSHIP_ME_HOW_TO_PLAY_SECTIONS.flatMap(section=>[section.title,...section.paragraphs,...(section.bullets??[])]).join(' ');

describe('Worship Me guided tutorial content',()=>{
 it('provides eight concise authoritative steps',()=>{expect(WORSHIP_ME_TUTORIAL_STEPS).toHaveLength(8);for(const text of ['THE GOAL','Placement','Resolution','Production','BLESS TILE','BLESS EDGE','SMITE TILE','SMITE EDGE','TEMPLES & PRIESTS','Priest','all remaining Village tiles','greatest total wins','does not automatically win'])expect(tutorialText).toContain(text);});
 it('preserves the exact victory distinction and unresolved tie',()=>{expect(tutorialText).toMatch(/Temple condition only triggers the ending/i);expect(tutorialText).toMatch(/does not automatically win/i);expect(tutorialText).toMatch(/every player’s total on-board followers/i);expect(tutorialText).toMatch(/highest-total tie remains unresolved/i);});
 it('documents all four Temple effects and Priest constraints',()=>{for(const text of ['Bless your own Temple','Bless an opponent Temple','Smite your own Temple','Smite an opponent Temple','at most once per round','twice per player per game','do not enhance Homes'])expect(tutorialText).toContain(text);});
});

describe('Worship Me detailed How to Play reference',()=>{
 it('contains every required rules section',()=>{expect(WORSHIP_ME_HOW_TO_PLAY_SECTIONS.map(section=>section.title)).toEqual(['OBJECTIVE','ROUND STRUCTURE','PLACEMENT RULES','BLESS TILE','BLESS EDGE','SMITE TILE','SMITE EDGE','FARMS','BAKERIES','HOMES','NORMAL END-ROUND BAG DRAW','TEMPLES','PRIESTS','VILLAGE SQUARE & NEUTRALS','CAPACITY','RESOLUTION','VICTORY','GAME CONTROLS']);});
 it('documents multiplayer controls and resolution choices without local debug controls',()=>{for(const label of ['BLESS TILE','BLESS EDGE','SMITE TILE','SMITE EDGE','END TURN','CONFIRM','CANCEL','REFRESH GAME','ROOM CHAT / SEND','LEAVE GAME','RETURN TO LOBBY','HOW TO PLAY','WHEAT / BREAD','Bless Edge resolution choices'])expect(guideText).toContain(label);for(const forbidden of ['Save game','Resume game','Import save','Export save','Debug JSON'])expect(guideText).not.toContain(forbidden);});
 it('matches implemented production, capacity, neutral, and departure behavior',()=>{for(const text of ['1 Wheat per occupant','2 Wheat per occupant','2 Wheat for 1 Bread','1 Wheat for 1 Bread','exactly two occupants','currently 1 Bread','player count plus two','global Neutral cap is 10','Balanced AI','unreclaimable'])expect(guideText).toContain(text);expect(guideText).toContain('Priests do not enhance Homes');});
 it('distinguishes Home draws and contributions from the separate normal bag draw',()=>{for(const text of ['same color, that color contributes one token','different colors, each color contributes one token','adds one additional token of the Blessing player’s color','Home-triggered draws','separately attempts one normal draw from the new-villager bag for each player','bag is empty, no follower is drawn','Square is full, the drawn follower remains in the bag'])expect(guideText).toContain(text);});
});

describe('per-room tutorial state behavior',()=>{
 it('auto-opens once, preserves its step across trusted repaints, and stays closed after Skip',()=>{const storage=memoryStorage(),help=createWorshipMeHelpController(storage);help.enterActiveRoom('abc234');expect(help.state).toMatchObject({mode:'tutorial',tutorialStep:0,roomCode:'ABC234'});help.next();help.next();expect(help.state.tutorialStep).toBe(2);help.enterActiveRoom('ABC234');expect(help.state).toMatchObject({mode:'tutorial',tutorialStep:2});help.skip();expect(help.state.mode).toBeUndefined();expect(storage.values.get(worshipMeTutorialStorageKey('ABC234'))).toBe('seen');help.enterActiveRoom('ABC234');expect(help.state.mode).toBeUndefined();});
 it('completes all steps and persists the room marker without accepting a command adapter',()=>{const storage=memoryStorage(),help=createWorshipMeHelpController(storage);help.enterActiveRoom('ABC234');for(let index=1;index<WORSHIP_ME_TUTORIAL_STEPS.length;index++)help.next();expect(help.state.tutorialStep).toBe(WORSHIP_ME_TUTORIAL_STEPS.length-1);help.finish();expect(help.state.mode).toBeUndefined();expect(storage.values.get(worshipMeTutorialStorageKey('ABC234'))).toBe('seen');expect(Object.keys(help).sort()).toEqual(['back','closeGuide','enterActiveRoom','finish','next','openGuide','replayTutorial','skip','state']);});
 it('honors an existing marker but auto-opens independently for a different room',()=>{const storage=memoryStorage();storage.setItem(worshipMeTutorialStorageKey('ABC234'),'seen');const help=createWorshipMeHelpController(storage);help.enterActiveRoom('ABC234');expect(help.state.mode).toBeUndefined();help.enterActiveRoom('xyz789');expect(help.state).toMatchObject({mode:'tutorial',tutorialStep:0,roomCode:'XYZ789'});});
 it('opens the guide and replays step one even after the room is seen',()=>{const storage=memoryStorage();storage.setItem(worshipMeTutorialStorageKey('ABC234'),'seen');const help=createWorshipMeHelpController(storage);help.enterActiveRoom('ABC234');help.openGuide('ABC234');expect(help.state.mode).toBe('guide');help.replayTutorial();expect(help.state).toMatchObject({mode:'tutorial',tutorialStep:0,roomCode:'ABC234'});});
 it('does not reopen automatically for a same-room gameOver repaint or rematch',()=>{const help=createWorshipMeHelpController(memoryStorage());help.enterActiveRoom('ABC234');help.finish();help.enterActiveRoom('ABC234');expect(help.state.mode).toBeUndefined();});
 it('fails safely when session storage reads and writes throw',()=>{const storage={getItem:vi.fn(()=>{throw Error('blocked');}),setItem:vi.fn(()=>{throw Error('blocked');})},help=createWorshipMeHelpController(storage);expect(()=>help.enterActiveRoom('ABC234')).not.toThrow();expect(help.state.mode).toBe('tutorial');expect(()=>help.skip()).not.toThrow();expect(help.state.mode).toBeUndefined();help.enterActiveRoom('XYZ789');expect(help.state.mode).toBe('tutorial');});
});

describe('shell help integration and accessibility',()=>{
 it('offers HOW TO PLAY on landing, lobby, active turns, non-current turns, and game over',()=>{expect(shell.match(/data-how-to-play/g)?.length).toBeGreaterThanOrEqual(3);expect(shell).toMatch(/hero-actions[\s\S]*?data-how-to-play/);expect(shell).toMatch(/lobby-controls__actions[\s\S]*?data-how-to-play/);expect(shell).toMatch(/active-game__status-actions[\s\S]*?data-how-to-play/);expect(shell).toContain("else controls=gameOverControls()");});
 it('auto-enters independently of turn authority, preserves controller state across paint, and renders help outside canonical state',()=>{expect(shell).toContain('help.enterActiveRoom(code)');expect(shell.indexOf('help.enterActiveRoom(code)')).toBeLessThan(shell.indexOf('const canPlace='));expect(shell).toContain('bindHowToPlay(code)');expect(shell).toContain("root.insertAdjacentHTML('beforeend'");expect(contentSource).not.toMatch(/GameState|stateVersion|submitGameAction|startGame|manageLobby|leaveRoom|returnToLobby|advanceAI|sendRoomChatMessage/);});
 it('uses accessible modal navigation, Escape handling, replay, and a blocking responsive backdrop',()=>{for(const token of ['role="dialog"','aria-modal="true"','aria-labelledby="worship-tutorial-heading"','aria-labelledby="worship-guide-heading"','SKIP TUTORIAL','START PLAYING','REPLAY TUTORIAL',"event.key!=='Escape'"])expect(shell).toContain(token);expect(css).toContain('position:fixed');expect(css).toContain('overflow-y:auto');expect(css).toContain('100dvh');expect(css).toContain('z-index:1000');});
 it('keeps static help HTML escaped and help actions free of gameplay commands',()=>{expect(shell).toContain('escapeHtml(section.title)');expect(shell).toContain('escapeHtml(paragraph)');expect(shell).toContain('escapeHtml(item)');const helpBlock=shell.slice(shell.indexOf('const helpSection='),shell.indexOf('const chatPanel='));for(const forbidden of ['submitGame(','start(','manageLobby(','leave(','returnLobby(','advanceAI(','sendChat('])expect(helpBlock).not.toContain(forbidden);});
});

describe('help modal DOM containment',()=>{
 const mount=(kind:'tutorial'|'guide'= 'tutorial')=>{document.body.innerHTML=`<div id="root"><div class="play-shell"><button data-background>BLESS TILE</button><button data-how-to-play>HOW TO PLAY</button></div><div data-worship-help><section role="dialog" tabindex="-1">${kind==='tutorial'?'<button data-tutorial-skip>SKIP TUTORIAL</button><button data-tutorial-back>BACK</button><button data-tutorial-next>NEXT</button>':'<button data-guide-close>CLOSE</button><button data-replay-tutorial>REPLAY TUTORIAL</button><button data-guide-close>CLOSE</button>'}</section></div></div>`;const application=document.querySelector<HTMLElement>('.play-shell')!,overlay=document.querySelector<HTMLElement>('[data-worship-help]')!,dialog=overlay.querySelector<HTMLElement>('[role="dialog"]')!,background=document.querySelector<HTMLButtonElement>('[data-background]')!,opener=document.querySelector<HTMLButtonElement>('[data-how-to-play]')!;return{application,overlay,dialog,background,opener};};
 const tab=(target:HTMLElement,shiftKey=false)=>target.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',shiftKey,bubbles:true,cancelable:true}));

 it('keeps tutorial focus inside the actual dialog and the background inert',()=>{const dom=mount(),action=vi.fn();dom.background.onclick=action;const binding=bindWorshipMeHelpModal(dom.application,dom.overlay,dom.dialog,'[data-tutorial-next]');const controls=[...dom.dialog.querySelectorAll<HTMLButtonElement>('button')];expect(dom.application.inert).toBe(true);expect(dom.dialog.inert).toBe(false);expect(dom.dialog.contains(document.activeElement)).toBe(true);controls.at(-1)!.focus();tab(controls.at(-1)!);expect(document.activeElement).toBe(controls[0]);tab(controls[0],true);expect(document.activeElement).toBe(controls.at(-1));dom.overlay.click();expect(action).not.toHaveBeenCalled();expect(dom.dialog.contains(document.activeElement)).toBe(true);binding.release();expect(dom.application.inert).toBe(false);});
 it('opens from a real guide button, contains focus, and restores the connected opener',()=>{const dom=mount('guide');let binding:ReturnType<typeof bindWorshipMeHelpModal>|undefined;dom.opener.onclick=()=>{binding=bindWorshipMeHelpModal(dom.application,dom.overlay,dom.dialog,'[data-guide-close]');};dom.opener.focus();dom.opener.click();const controls=[...dom.dialog.querySelectorAll<HTMLButtonElement>('button')];expect(document.activeElement).toBe(controls[0]);controls.at(-1)!.focus();tab(controls.at(-1)!);expect(document.activeElement).toBe(controls[0]);binding!.release();expect(restoreWorshipMeHelpFocus(dom.opener)).toBe(true);expect(dom.application.inert).toBe(false);expect(document.activeElement).toBe(dom.opener);});
 it('releases inert safely when a repaint disconnects the saved opener',()=>{const dom=mount('guide'),focus=vi.spyOn(dom.opener,'focus');const binding=bindWorshipMeHelpModal(dom.application,dom.overlay,dom.dialog,'[data-guide-close]');dom.application.innerHTML='<button data-new-control>NEW CONTROL</button>';expect(dom.opener.isConnected).toBe(false);expect(()=>{binding.release();restoreWorshipMeHelpFocus(dom.opener);}).not.toThrow();expect(dom.application.inert).toBe(false);expect(focus).not.toHaveBeenCalled();});
 it('keeps mounted background handlers untouched by tutorial navigation and pointer shielding',()=>{const dom=mount(),backgroundAction=vi.fn();dom.background.onclick=backgroundAction;const help=createWorshipMeHelpController(memoryStorage());help.enterActiveRoom('ABC234');const binding=bindWorshipMeHelpModal(dom.application,dom.overlay,dom.dialog,'[data-tutorial-next]');dom.dialog.querySelector<HTMLButtonElement>('[data-tutorial-next]')!.onclick=()=>help.next();dom.dialog.querySelector<HTMLButtonElement>('[data-tutorial-back]')!.onclick=()=>help.back();dom.dialog.querySelector<HTMLButtonElement>('[data-tutorial-skip]')!.onclick=()=>help.skip();dom.dialog.querySelector<HTMLButtonElement>('[data-tutorial-next]')!.click();dom.dialog.querySelector<HTMLButtonElement>('[data-tutorial-back]')!.click();dom.overlay.click();expect(backgroundAction).not.toHaveBeenCalled();expect(dom.dialog.contains(document.activeElement)).toBe(true);binding.release();});
});

describe('Milestone 15 backend immutability',()=>{
 it('keeps exactly 22 migrations with migration 22 byte-pinned',async()=>{const names=readdirSync(migrations,{withFileTypes:true}).filter(entry=>!entry.isDirectory()&&entry.name.endsWith('.sql')).map(entry=>entry.name).sort();expect(names).toHaveLength(22);expect(names.at(-1)).toBe('20260924000005_room_chat.sql');const bytes=new TextEncoder().encode(readFileSync(resolve(migrations,'20260924000005_room_chat.sql'),'utf8')),digest=await crypto.subtle.digest('SHA-256',bytes),hash=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,'0')).join('');expect(hash).toBe('1ab7b2f0603f830205f973fd6013e24daece2a4678f294e570d80b748b69e341');});
});
