import {readdirSync,readFileSync} from 'node:fs';
import {describe,expect,it,vi} from 'vitest';
import {listJoinableRooms} from '../src/platform/rooms/listJoinableRooms';
import {joinPublicRoom} from '../src/platform/rooms/joinPublicRoom';
import {manageLobby} from '../src/platform/rooms/manageLobby';
import {createRoomKickSyncCoordinator} from '../src/platform/rooms/roomKickSync';
import {renderLobbyPlayerRows} from '../src/platform/rooms/lobbyPlayerRows';
import type {HumanLobbyPlayer} from '../src/platform/rooms/lobby';

const migrationUrl=new URL('../supabase/migrations/',import.meta.url);
const migration=readFileSync(new URL('../supabase/migrations/20260924000000_lobby_discovery_and_host_moderation.sql',import.meta.url),'utf8');
const listEdge=readFileSync(new URL('../supabase/functions/list-rooms/index.ts',import.meta.url),'utf8');
const publicJoinEdge=readFileSync(new URL('../supabase/functions/join-public-room/index.ts',import.meta.url),'utf8');
const manageEdge=readFileSync(new URL('../supabase/functions/manage-lobby/index.ts',import.meta.url),'utf8');
const joinEdge=readFileSync(new URL('../supabase/functions/join-room/index.ts',import.meta.url),'utf8');
const shell=readFileSync(new URL('../src/platform/shell.ts',import.meta.url),'utf8');
const config=readFileSync(new URL('../supabase/config.toml',import.meta.url),'utf8');
const hashes:Record<string,string>={
 '20260919190346_create_ngsllc_core.sql':'dfa5c612e9edc4c58b685d3a80c4ebd826f0c0450df3d5ed0689005f01029840','20260919190347_restrict_rls_auto_enable.sql':'16f698e12a5b68c5aa1022d37311ff127fe8350f8ed965eee08c8cf4a5fd592b','20260919190348_create_room_server_command.sql':'ca25b2ddda8a351ad526a7884f0d8920fb137652f77a7235d4679fbb8941dd81','20260920000000_join_room_server_command.sql':'bb96b67025475877d89a335e278dc6ce9b8b733d3c9858fd49dbdbd5a17aef79','20260920000001_lobby_lifecycle.sql':'5ec1beccbe16f9a267806ddd155d08a349286a4d6625a0de3ac6eb94d592af96','20260920000002_player_color_selection.sql':'0887a28b155576694e22f339e82fd1951c7ce9978da439661a217bbdeffc2230','20260920000003_player_ready_state.sql':'73ac0263ec0f0af59da1394bdc00b687a47ac7f8c7e7587577813c5718de9f47','20260920000004_start_game.sql':'5bc2bd51cdb12166ad1285740a60760974925593d0b5b0e40be2140ce2230706','20260921000000_active_game_state_read.sql':'3956a00b749e0475e56b910e88671580ff4934b484498e05e875fcdf358359cb','20260921000001_gameplay_mutation.sql':'a80840b9a2cade11645b7360c31ec401e900cc06413f5335e62c67a642dffaab','20260922000000_realtime_game_sync.sql':'53d6e92e41b06371bab2be49dc8e05cf0f609e2d49addc258e135b6dae8696b6','20260922000001_realtime_lobby_sync.sql':'783559b6fcfd841a5dbda98bf21a27bccce2899a9687c644a914955114bbc27a','20260922000002_multiplayer_ai_players.sql':'68481194f0c79ea8b5729db7088e9fd4bacce03bf5ac76c902af0c69c1b418ff','20260923000000_fix_multiplayer_ai_sql_ambiguity.sql':'3d684ce2b4285b1cce4747f27679d5693071a47fbef091d837c373cd83e5ba6d','20260923000001_fix_start_game_coalesce.sql':'5139fda069f56017e9fcbccd8ce73a29dd05804494c6c9a01829ef816ffe8afb','20260923000002_active_player_ai_takeover.sql':'1fca1fc0096a6cd37c53e5e7462569b34709b0094e636218e2575fe889e13905'};

const authenticatedClient=(invoke:(name:string,options:{body:unknown})=>Promise<unknown>)=>({auth:{getSession:vi.fn(async()=>({data:{session:{user:{id:'user-1'}}},error:null}))},functions:{invoke:vi.fn(invoke)}});

describe('lobby discovery and moderation clients',()=>{
 it('sends only gameSlug and accepts only the safe directory DTO',async()=>{const invoke=vi.fn(async(_name:string,_options:{body:unknown})=>({data:{rooms:[{roomCode:'ABC234',hostDisplayName:'Alice',humanPlayers:2,aiPlayers:1,totalPlayers:3,maxPlayers:8,createdAt:'2026-09-24T00:00:00Z'}]},error:null}));const result=await listJoinableRooms({gameSlug:'worship-me'},authenticatedClient(invoke) as never);expect(invoke).toHaveBeenCalledWith('list-rooms',{body:{gameSlug:'worship-me'}});expect(result.rooms[0]).toEqual({roomCode:'ABC234',hostDisplayName:'Alice',humanPlayers:2,aiPlayers:1,totalPlayers:3,maxPlayers:8,createdAt:'2026-09-24T00:00:00Z'});expect(result.rooms[0]).not.toHaveProperty('hostUserId');});
 it('keeps directory join roomCode/displayName-only and uses its distinct Edge path',async()=>{const invoke=vi.fn(async()=>({data:{room:{id:'room-1',code:'ABC234',gameId:'game-1',status:'lobby'},joinedNew:true},error:null}));await joinPublicRoom({roomCode:' abc234 ',displayName:' Bob '},authenticatedClient(invoke) as never);expect(invoke).toHaveBeenCalledWith('join-public-room',{body:{roomCode:'ABC234',displayName:'Bob'}});});
 it('sends only host moderation commands, never requester authority',async()=>{const invoke=vi.fn(async()=>({data:{roomCode:'ABC234'},error:null}));const client=authenticatedClient(invoke) as never;await manageLobby({roomCode:'ABC234',command:{type:'setJoinMode',joinMode:'code'}},client);await manageLobby({roomCode:'ABC234',command:{type:'kickPlayer',targetUserId:'11111111-1111-4111-8111-111111111111'}},client);expect(invoke).toHaveBeenNthCalledWith(1,'manage-lobby',{body:{roomCode:'ABC234',command:{type:'setJoinMode',joinMode:'code'}}});expect(invoke).toHaveBeenNthCalledWith(2,'manage-lobby',{body:{roomCode:'ABC234',command:{type:'kickPlayer',targetUserId:'11111111-1111-4111-8111-111111111111'}}});});
});

describe('migration #17 STATIC CONTRACT (not PostgreSQL execution)',()=>{
 it('remains unchanged before the return-to-lobby migration',async()=>{const names=readdirSync(migrationUrl,{withFileTypes:true}).filter(entry=>!entry.isDirectory()&&entry.name.endsWith('.sql')).map(entry=>entry.name).sort();expect(names).toHaveLength(18);expect(names.at(-2)).toBe('20260924000000_lobby_discovery_and_host_moderation.sql');expect(names.at(-1)).toBe('20260924000001_return_finished_game_to_lobby.sql');for(const[name,hash]of Object.entries(hashes)){const bytes=new TextEncoder().encode(readFileSync(new URL(`../supabase/migrations/${name}`,import.meta.url),'utf8')),digest=await crypto.subtle.digest('SHA-256',bytes),actual=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,'0')).join('');expect(actual).toBe(hash);}});
 it('adds exact public/code room access metadata with public default',()=>{expect(migration).toContain("add column join_mode text not null default 'public'");expect(migration).toContain("check (join_mode in ('public', 'code'))");});
 it('lists only active, public, non-full Worship Me rooms with a live human host and no requester kick',()=>{const start=migration.indexOf('create function public.list_joinable_rooms_server'),end=migration.indexOf('create function public.set_room_join_mode_server');const body=migration.slice(start,end);for(const token of ["g.status = 'active'","r.status = 'lobby'","r.join_mode = 'public'",'host_player.user_id = r.host_user_id','counts.human_count + counts.ai_count < g.max_players','rk.user_id = p_user_id','order by r.created_at desc, r.code asc'])expect(body).toContain(token);expect(body).not.toContain('host_user_id text');expect(body).not.toContain('game_state');});
 it('uses one shared lock-safe join algorithm for code and public joins',()=>{expect(migration).toContain('ngsllc_private.join_lobby_member');expect(migration).toContain('pg_catalog.pg_advisory_xact_lock');expect(migration).toContain('array_agg(affected.affected_room_id order by affected.affected_room_id)');expect(migration).toContain('foreach v_lock_room_id in array v_lock_room_ids');expect(migration).toContain('p_require_public and v_join_mode is distinct from');expect(migration).toMatch(/join_room_server[\s\S]*p_display_name,[\s\n]+false/);expect(migration).toMatch(/join_public_room_server[\s\S]*p_display_name,[\s\n]+true/);});
 it('checks kick and capacity before departing old lobbies',()=>{const kick=migration.indexOf('from public.room_kicks as rk',migration.indexOf('join_lobby_member')),capacity=migration.indexOf('v_player_count + v_ai_count >= v_max_players'),depart=migration.indexOf('depart_lobby_member',migration.indexOf('join_lobby_member'));expect(kick).toBeGreaterThan(0);expect(kick).toBeLessThan(depart);expect(capacity).toBeLessThan(depart);});
 it('locks join-mode changes, avoids no-op updates, and extends the single M10 rooms trigger',()=>{expect(migration).toContain('for update of r;');expect(migration).toContain('if v_join_mode = v_requested_join_mode then');expect(migration).toContain('drop trigger rooms_bump_lobby_update on public.rooms');expect(migration).toContain('after update of host_user_id, status, join_mode on public.rooms');expect((migration.match(/create trigger rooms_bump_lobby_update/g)??[])).toHaveLength(1);expect(migration).toContain('new.join_mode is distinct from old.join_mode');});
 it('creates an own-row-only kick table with no browser writes and exact Realtime addition',()=>{expect(migration).toContain('create table public.room_kicks');expect(migration).toContain('primary key (room_id, user_id)');expect(migration).toContain('alter table public.room_kicks enable row level security');expect(migration).toContain('using (user_id = (select auth.uid()))');expect(migration).toContain('grant select on table public.room_kicks to authenticated');expect(migration).not.toMatch(/grant (insert|update|delete)[^;]*room_kicks to authenticated/i);expect(migration).toContain('alter publication supabase_realtime add table public.room_kicks');});
 it('publishes exactly the two version-signal tables plus user-specific kicks',()=>{const all=readdirSync(migrationUrl,{withFileTypes:true}).filter(entry=>!entry.isDirectory()&&entry.name.endsWith('.sql')).map(entry=>readFileSync(new URL(`../supabase/migrations/${entry.name}`,import.meta.url),'utf8')).join('\n'),published=Array.from(all.matchAll(/alter publication supabase_realtime add table public\.([a-z_]+)/g),match=>match[1]);expect(published).toEqual(['room_game_updates','room_lobby_updates','room_kicks']);for(const table of ['rooms','room_players','room_ai_players','room_states'])expect(published).not.toContain(table);});
 it('makes kick record plus human deletion one atomic locked RPC and never handles AI',()=>{const start=migration.indexOf('create function public.kick_room_player_server'),end=migration.indexOf('revoke execute on function public.join_room_server');const body=migration.slice(start,end);expect(body).toContain('for update of r');expect(body.indexOf('insert into public.room_kicks')).toBeLessThan(body.indexOf('delete from public.room_players'));expect(body).toContain("v_room_status is distinct from 'lobby'");expect(body).toContain('p_target_user_id = p_user_id');expect(body).not.toContain('delete from public.room_ai_players');});
 it('keeps every public command service-role-only and security invoker',()=>{for(const signature of ['join_room_server(text,uuid,text)','join_public_room_server(text,uuid,text)','list_joinable_rooms_server(text,uuid)','set_room_join_mode_server(text,uuid,text)','kick_room_player_server(text,uuid,uuid)']){expect(migration).toContain(`revoke execute on function public.${signature} from public, anon, authenticated, service_role`);expect(migration).toContain(`grant execute on function public.${signature} to service_role`);}expect((migration.match(/security invoker/g)??[]).length).toBeGreaterThanOrEqual(6);});
 it('passes the SQL-special-form and ambiguity audit',()=>{for(const bad of ['pg_catalog.coalesce','pg_catalog.nullif','pg_catalog.greatest','pg_catalog.least','pg_catalog.case','pg_catalog.cast','pg_catalog.extract','pg_catalog.position','pg_catalog.overlay','pg_catalog.trim'])expect(migration.toLowerCase()).not.toContain(bad);expect(migration).not.toMatch(/pg_catalog\.substring\([^)]*\sfrom\s/i);});
 it('STATIC CONTRACT: serializes final-slot, mode/join, kick/rejoin, kick/Start, and kick/color/Ready races on room locks',()=>{expect(migration).toContain('foreach v_lock_room_id in array v_lock_room_ids');expect(migration).toMatch(/set_room_join_mode_server[\s\S]*for update of r/);expect(migration).toMatch(/kick_room_player_server[\s\S]*for update of r/);for(const file of ['20260923000000_fix_multiplayer_ai_sql_ambiguity.sql','20260923000001_fix_start_game_coalesce.sql'])expect(readFileSync(new URL(`../supabase/migrations/${file}`,import.meta.url),'utf8')).toContain('for update of r');});
});

describe('Edge, UI, and kick lifecycle contracts',()=>{
 it('uses JWT verification and exact request shapes for all new functions',()=>{for(const name of ['list-rooms','join-public-room','manage-lobby'])expect(config).toContain(`[functions.${name}]\nverify_jwt = true`);expect(listEdge).toContain("exact(body,['gameSlug'])");expect(publicJoinEdge).toContain("exact(body,['roomCode','displayName'])");expect(manageEdge).toContain("exact(body,['roomCode','command'])");for(const edge of [listEdge,publicJoinEdge,manageEdge]){expect(edge).toContain('auth.getUser(token)');expect(edge).toContain('SUPABASE_SECRET_KEYS');}});
 it('maps the kick ban specifically in code and public joins',()=>{for(const edge of [joinEdge,publicJoinEdge]){expect(edge).toContain("error.code==='P0007'");expect(edge).toContain('You were removed from this room by the host.');}});
 it('renders directory and code join separately, room access, human kick, and existing AI removal',()=>{for(const token of ['AVAILABLE ROOMS','JOIN BY CODE','data-join-public','data-room-join-mode','data-kick-player','data-ai-remove','CODE ONLY'])expect(shell).toContain(token);expect(shell).toContain("joinPublic({roomCode:control.dataset.joinPublic!,displayName})");expect(shell).toContain("join({roomCode,displayName})");});
 it('shows kick only for other humans and never for AI',()=>{const alice:HumanLobbyPlayer={control:'human',participantId:'u1',userId:'u1',displayName:'Alice',playerColor:'red',turnOrder:null,isReady:true,isHost:true,isCurrentUser:true},bob:HumanLobbyPlayer={...alice,participantId:'u2',userId:'u2',displayName:'Bob',isHost:false,isCurrentUser:false};const html=renderLobbyPlayerRows([alice,bob],true);expect(html).not.toContain('data-kick-player="u1"');expect(html).toContain('data-kick-player="u2"');expect(renderLobbyPlayerRows([alice,bob],false)).not.toContain('data-kick-player');});
 it('owns at most one kick subscription and protects against stale old-room callbacks',async()=>{const callbacks=new Map<string,()=>void>(),unsubscribed:string[]=[];const kicked=vi.fn();const sync=createRoomKickSyncCoordinator(kicked,async options=>{callbacks.set(options.roomId,()=>options.onKick({roomId:options.roomId,kickedAt:'now'}));return{roomId:options.roomId,async unsubscribe(){unsubscribed.push(options.roomId);}};});await sync.enter('11111111-1111-4111-8111-111111111111');await sync.enter('22222222-2222-4222-8222-222222222222');callbacks.get('11111111-1111-4111-8111-111111111111')!();expect(kicked).not.toHaveBeenCalled();callbacks.get('22222222-2222-4222-8222-222222222222')!();expect(kicked).toHaveBeenCalledOnce();expect(unsubscribed).toContain('11111111-1111-4111-8111-111111111111');await sync.leave();expect(unsubscribed).toContain('22222222-2222-4222-8222-222222222222');});
 it('defense-in-depth filters kick payloads to the authenticated user in addition to RLS',()=>{const source=readFileSync(new URL('../src/platform/rooms/subscribeRoomKicks.ts',import.meta.url),'utf8');expect(source).toContain('row.user_id===user.id');expect(source).toContain("table:'room_kicks'");expect(source).toContain("event:'INSERT'");});
 it('cleans the kick subscription on route changes, lobby leave, Start, and kick redirect',()=>{expect(shell).toContain('Promise.all([roomKickSync.leave(),roomSync.leave(),roomLobbySync.leave()])');expect(shell).toContain('await roomKickSync.leave();router.navigate');expect(shell).toContain('if(started){await roomKickSync.leave();await roomSync.refresh();}');expect(shell).toContain("pendingJoinNotice='You were removed from the room by the host.'");});
});
