import {readFileSync,readdirSync} from 'node:fs';
import {describe,expect,it,vi} from 'vitest';
import type {SupabaseClient} from '@supabase/supabase-js';
import {ACTIVE_LOBBY_PRESENCE_INTERVAL_MS,createActiveLobbyPresenceCoordinator,type ActiveLobbyPresenceEnvironment} from '../src/platform/rooms/activeLobbyPresence';
import {createTouchLobbyPresenceAction,touchLobbyPresence} from '../src/platform/rooms/lobbyPresence';

const migrationUrl=new URL('../supabase/migrations/',import.meta.url);
const migration=readFileSync(new URL('../supabase/migrations/20260924000003_lobby_presence_and_stale_directory.sql',import.meta.url),'utf8');
const lifecycle=readFileSync(new URL('../supabase/migrations/20260920000001_lobby_lifecycle.sql',import.meta.url),'utf8');
const core=readFileSync(new URL('../supabase/migrations/20260919190346_create_ngsllc_core.sql',import.meta.url),'utf8');
const m10=readFileSync(new URL('../supabase/migrations/20260924000000_lobby_discovery_and_host_moderation.sql',import.meta.url),'utf8');
const edge=readFileSync(new URL('../supabase/functions/lobby-presence/index.ts',import.meta.url),'utf8');
const coordinator=readFileSync(new URL('../src/platform/rooms/activeLobbyPresence.ts',import.meta.url),'utf8');
const shell=readFileSync(new URL('../src/platform/shell.ts',import.meta.url),'utf8');
const config=readFileSync(new URL('../supabase/config.toml',import.meta.url),'utf8');
const priorHashes:Record<string,string>={
 '20260919190346_create_ngsllc_core.sql':'dfa5c612e9edc4c58b685d3a80c4ebd826f0c0450df3d5ed0689005f01029840','20260919190347_restrict_rls_auto_enable.sql':'16f698e12a5b68c5aa1022d37311ff127fe8350f8ed965eee08c8cf4a5fd592b','20260919190348_create_room_server_command.sql':'ca25b2ddda8a351ad526a7884f0d8920fb137652f77a7235d4679fbb8941dd81','20260920000000_join_room_server_command.sql':'bb96b67025475877d89a335e278dc6ce9b8b733d3c9858fd49dbdbd5a17aef79','20260920000001_lobby_lifecycle.sql':'5ec1beccbe16f9a267806ddd155d08a349286a4d6625a0de3ac6eb94d592af96','20260920000002_player_color_selection.sql':'0887a28b155576694e22f339e82fd1951c7ce9978da439661a217bbdeffc2230','20260920000003_player_ready_state.sql':'73ac0263ec0f0af59da1394bdc00b687a47ac7f8c7e7587577813c5718de9f47','20260920000004_start_game.sql':'5bc2bd51cdb12166ad1285740a60760974925593d0b5b0e40be2140ce2230706','20260921000000_active_game_state_read.sql':'3956a00b749e0475e56b910e88671580ff4934b484498e05e875fcdf358359cb','20260921000001_gameplay_mutation.sql':'a80840b9a2cade11645b7360c31ec401e900cc06413f5335e62c67a642dffaab','20260922000000_realtime_game_sync.sql':'53d6e92e41b06371bab2be49dc8e05cf0f609e2d49addc258e135b6dae8696b6','20260922000001_realtime_lobby_sync.sql':'783559b6fcfd841a5dbda98bf21a27bccce2899a9687c644a914955114bbc27a','20260922000002_multiplayer_ai_players.sql':'68481194f0c79ea8b5729db7088e9fd4bacce03bf5ac76c902af0c69c1b418ff','20260923000000_fix_multiplayer_ai_sql_ambiguity.sql':'3d684ce2b4285b1cce4747f27679d5693071a47fbef091d837c373cd83e5ba6d','20260923000001_fix_start_game_coalesce.sql':'5139fda069f56017e9fcbccd8ce73a29dd05804494c6c9a01829ef816ffe8afb','20260923000002_active_player_ai_takeover.sql':'1fca1fc0096a6cd37c53e5e7462569b34709b0094e636218e2575fe889e13905','20260924000000_lobby_discovery_and_host_moderation.sql':'42b08a785f5c289639211df0c03344909f005f76b8e1848c65e5c99ad5efe568','20260924000001_return_finished_game_to_lobby.sql':'af563be022bac9166854cf75a03841cdaf0159f14ceecb6f722661720a5a8a9a','20260924000002_fix_return_to_lobby_signal_read.sql':'2eccc6391230116a28c6a3b19be44bb56c29412f1efcc6d48cb50f360f765e42',
};

const functionBody=(name:string)=>migration.match(new RegExp(`create(?: or replace)? function ${name.replace('.','\\.')}\\([\\s\\S]*?\\n\\$\\$;`))?.[0]??'';
const presence=functionBody('public.touch_lobby_presence_server');
const directory=functionBody('public.list_joinable_rooms_server');

interface DirectoryCase{hostSeenAt:number;now:number;joinMode:'public'|'code';humanPlayers:number;aiPlayers:number;maxPlayers:number;kicked:boolean}
const directoryEligible=(room:DirectoryCase)=>room.joinMode==='public'&&room.hostSeenAt>=room.now-90_000&&room.humanPlayers+room.aiPlayers<room.maxPlayers&&!room.kicked;

function environment(){
 let interval:(()=>void)|undefined,visibility:(()=>void)|undefined,focus:(()=>void)|undefined,online:(()=>void)|undefined,visible=true;
 const value:ActiveLobbyPresenceEnvironment={setInterval:vi.fn(callback=>{interval=callback;return 1;}),clearInterval:vi.fn(()=>{interval=undefined;}),onVisibilityChange:callback=>{visibility=callback;return()=>{visibility=undefined;};},onFocus:callback=>{focus=callback;return()=>{focus=undefined;};},onOnline:callback=>{online=callback;return()=>{online=undefined;};},isVisible:()=>visible};
 return{value,interval:()=>interval?.(),visibility:()=>visibility?.(),focus:()=>focus?.(),online:()=>online?.(),setVisible:(next:boolean)=>{visible=next;}};
}
const deferred=()=>{let resolve!:()=>void;const promise=new Promise<void>(yes=>{resolve=yes;});return{promise,resolve};};

describe('migration #20 lobby presence STATIC CONTRACT (not PostgreSQL execution)',()=>{
 it('retains migration 20 and pins migrations 1-19 unchanged',async()=>{const names=readdirSync(migrationUrl,{withFileTypes:true}).filter(entry=>!entry.isDirectory()&&entry.name.endsWith('.sql')).map(entry=>entry.name).sort();expect(names).toHaveLength(22);expect(names.at(-3)).toBe('20260924000003_lobby_presence_and_stale_directory.sql');expect(names.at(-2)).toBe('20260924000004_room_naming.sql');for(const[name,hash]of Object.entries(priorHashes)){const bytes=new TextEncoder().encode(readFileSync(new URL(`../supabase/migrations/${name}`,import.meta.url),'utf8')),digest=await crypto.subtle.digest('SHA-256',bytes),actual=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,'0')).join('');expect(actual).toBe(hash);}});
 it('requires a fresh current human host and keeps every established directory filter and ordering',()=>{for(const token of ["g.status = 'active'","r.status = 'lobby'","r.join_mode = 'public'",'host_player.user_id = r.host_user_id',"host_player.last_seen_at >= pg_catalog.now() - interval '90 seconds'",'counts.human_count + counts.ai_count < g.max_players','rk.user_id = p_user_id','order by r.created_at desc, r.code asc'])expect(directory).toContain(token);expect(directory).not.toContain('return last_seen_at');});
 it('models fresh, stale, exact-threshold, code-only, full, kicked, and mixed-capacity directory outcomes',()=>{const base:DirectoryCase={hostSeenAt:10_000,now:10_000,joinMode:'public',humanPlayers:1,aiPlayers:2,maxPlayers:8,kicked:false};expect(directoryEligible(base)).toBe(true);expect(directoryEligible({...base,hostSeenAt:base.now-90_001})).toBe(false);expect(directoryEligible({...base,hostSeenAt:base.now-90_000})).toBe(true);expect(directoryEligible({...base,joinMode:'code'})).toBe(false);expect(directoryEligible({...base,humanPlayers:4,aiPlayers:4})).toBe(false);expect(directoryEligible({...base,kicked:true})).toBe(false);expect(directoryEligible({...base,humanPlayers:2,aiPlayers:5})).toBe(true);});
 it('keeps a stale host hidden despite a fresh non-host until trusted succession makes that fresh human host',()=>{const now=200_000,staleHost:DirectoryCase={hostSeenAt:now-90_001,now,joinMode:'public',humanPlayers:2,aiPlayers:0,maxPlayers:8,kicked:false};expect(directoryEligible(staleHost)).toBe(false);expect(directoryEligible({...staleHost,hostSeenAt:now})).toBe(true);expect(presence).toContain('depart_lobby_member');});
 it('makes the threshold inclusive and leaves explicit code/public join commands unchanged',()=>{expect(directory).toContain('last_seen_at >=');expect(migration).not.toContain('join_lobby_member');expect(migration).not.toContain('join_public_room_server');expect(migration).not.toContain('join_room_server');});
 it('locks the lobby, verifies membership, refreshes only the caller first, then snapshots stale others deterministically',()=>{const update=presence.indexOf('update public.room_players as caller'),snapshot=presence.indexOf('select coalesce(');expect(presence).toContain('for update of r');expect(presence).toContain("v_room_status is distinct from 'lobby'");expect(presence).toContain('caller.user_id = p_user_id');expect(update).toBeGreaterThan(0);expect(update).toBeLessThan(snapshot);expect(presence).toContain('set last_seen_at = greatest(caller.last_seen_at, v_now)');expect(presence).toContain('member.user_id <> p_user_id');expect(presence).toContain("member.last_seen_at < v_now - interval '90 seconds'");expect(presence).toContain('array_agg(stale.user_id order by stale.joined_at asc, stale.user_id asc)');});
 it('captures one wall-clock timestamp after the room lock and uses it monotonically for refresh and cutoff',()=>{const lock=presence.indexOf('for update of r'),clock=presence.indexOf('v_now := pg_catalog.clock_timestamp()');expect(clock).toBeGreaterThan(lock);expect(presence.match(/pg_catalog\.clock_timestamp\(\)/g)).toHaveLength(1);expect(presence).not.toMatch(/(?:pg_catalog\.)?now\s*\(/i);expect(presence).not.toMatch(/(?:pg_catalog\.)?transaction_timestamp\s*\(/i);expect(presence).toContain('greatest(caller.last_seen_at, v_now)');expect(presence).toContain("member.last_seen_at < v_now - interval '90 seconds'");});
 it('reuses deterministic lobby departure for stale humans and never touches AI, Ready, color, or canonical state',()=>{expect(presence).toContain('ngsllc_private.depart_lobby_member(v_room_id, v_stale_user_id)');expect(lifecycle).toContain('order by rp.joined_at asc, rp.user_id asc');for(const forbidden of ['room_ai_players','room_states','is_ready','player_color','turn_order','display_name'])expect(presence).not.toContain(forbidden);});
 it('keeps last_seen-only writes outside M10 while deletion and host transfer remain meaningful',()=>{expect(m10).toContain("if tg_table_name = 'room_players'");expect(m10).toContain("if tg_op = 'DELETE'");expect(m10).toContain('new.display_name is distinct from old.display_name');expect(m10).not.toContain('new.last_seen_at is distinct from old.last_seen_at');expect(m10).toContain('new.host_user_id is distinct from old.host_user_id');});
 it('is service-only SECURITY INVOKER with sufficient existing minimum table privileges',()=>{expect(presence).toContain('security invoker');expect(presence).toContain("set search_path = ''");expect(migration).toContain('revoke execute on function public.touch_lobby_presence_server(text,uuid)\nfrom public, anon, authenticated, service_role');expect(migration).toContain('grant execute on function public.touch_lobby_presence_server(text,uuid)\nto service_role');expect(core).toContain('grant select, insert, update, delete on table public.rooms to service_role');expect(core).toContain('grant select, insert, update, delete on table public.room_players to service_role');expect(migration).not.toMatch(/grant\s+(?:select|insert|update|delete|all)\s+on table/i);});
 it('passes output ambiguity, balanced-body, and special SQL form review',()=>{for(const alias of ['public.rooms as r','public.room_players as caller','public.room_players as member'])expect(presence).toContain(alias);expect((migration.match(/create(?: or replace)? function/g)??[])).toHaveLength(2);expect((migration.match(/end;\r?\n\$\$;/g)??[])).toHaveLength(2);for(const bad of ['pg_catalog.coalesce','pg_catalog.nullif','pg_catalog.greatest','pg_catalog.least'])expect(migration.toLowerCase()).not.toContain(bad);expect(migration).not.toMatch(/pg_catalog\.substring\([^)]*\sfrom\s/i);});
 it('STATIC CONTRACT: hides zero-observer stale rooms without destructive cleanup and resumes after trusted host refresh/transfer',()=>{expect(directory).toContain('host_player.last_seen_at >= pg_catalog.now()');expect(migration).not.toMatch(/delete from public\.rooms|delete from public\.room_players/i);expect(presence).toContain('depart_lobby_member');});
});

describe('lobby presence Edge and browser trust boundary',()=>{
 it('uses verified JWT identity, current key dictionaries, exact roomCode-only input, and safe errors',()=>{expect(config).toContain('[functions.lobby-presence]\nverify_jwt = true');expect(edge).toContain('auth.getUser(token)');expect(edge).toContain("key('SUPABASE_PUBLISHABLE_KEYS')");expect(edge).toContain("key('SUPABASE_SECRET_KEYS')");expect(edge).toContain("keys.length!==1||keys[0]!=='roomCode'");expect(edge).toContain('p_user_id:user.id');for(const forbidden of ['userId','lastSeenAt','timestamp','timeout','staleUser'])expect(edge).not.toContain(forbidden);});
 it('sends only normalized roomCode and validates the narrow result',async()=>{const invoke=vi.fn(async()=>({data:{roomCode:'ABC234',completed:true},error:null})),client={auth:{getSession:vi.fn(async()=>({data:{session:{user:{id:'user-1'}}},error:null}))},functions:{invoke}} as unknown as SupabaseClient;await expect(touchLobbyPresence({roomCode:' abc234 '},client)).resolves.toEqual({roomCode:'ABC234',completed:true});expect(invoke).toHaveBeenCalledWith('lobby-presence',{body:{roomCode:'ABC234'}});});
});

describe('active lobby presence coordinator',()=>{
 it('touches immediately and every 20 seconds without overlap',async()=>{const env=environment(),pending=deferred(),touch=vi.fn().mockImplementationOnce(()=>pending.promise).mockResolvedValue({roomCode:'ABC234',completed:true}),sync=createActiveLobbyPresenceCoordinator({}, {touch,environment:env.value});sync.enter('abc234');expect(touch).toHaveBeenCalledWith({roomCode:'ABC234'});expect(env.value.setInterval).toHaveBeenCalledWith(expect.any(Function),ACTIVE_LOBBY_PRESENCE_INTERVAL_MS);env.interval();expect(touch).toHaveBeenCalledTimes(1);pending.resolve();await pending.promise;env.interval();await vi.waitFor(()=>expect(touch).toHaveBeenCalledTimes(2));});
 it('suppresses hidden interval, focus, and online touches, then recovers immediately when visible',async()=>{const env=environment(),touch=vi.fn().mockResolvedValue({roomCode:'ABC234',completed:true}),sync=createActiveLobbyPresenceCoordinator({}, {touch,environment:env.value});sync.enter('ABC234');await vi.waitFor(()=>expect(touch).toHaveBeenCalledTimes(1));env.setVisible(false);env.visibility();env.interval();env.focus();env.online();await Promise.resolve();expect(touch).toHaveBeenCalledTimes(1);env.setVisible(true);env.visibility();await vi.waitFor(()=>expect(touch).toHaveBeenCalledTimes(2));env.focus();await vi.waitFor(()=>expect(touch).toHaveBeenCalledTimes(3));env.online();await vi.waitFor(()=>expect(touch).toHaveBeenCalledTimes(4));});
 it('does not touch immediately when entering hidden and touches once when visibility returns',async()=>{const env=environment(),touch=vi.fn().mockResolvedValue({roomCode:'ABC234',completed:true}),sync=createActiveLobbyPresenceCoordinator({}, {touch,environment:env.value});env.setVisible(false);sync.enter('ABC234');env.interval();env.focus();env.online();await Promise.resolve();expect(touch).not.toHaveBeenCalled();env.setVisible(true);env.visibility();await vi.waitFor(()=>expect(touch).toHaveBeenCalledTimes(1));});
 it('sends a distinct immediate request when switching rooms while the old production action request is pending',async()=>{const env=environment(),old=deferred(),command=vi.fn().mockImplementationOnce(()=>old.promise).mockResolvedValue({roomCode:'XYZ789',completed:true}),action=createTouchLobbyPresenceAction(command as never),sync=createActiveLobbyPresenceCoordinator({}, {touch:action,environment:env.value});sync.enter('ABC234');expect(command).toHaveBeenNthCalledWith(1,{roomCode:'ABC234'});sync.enter('XYZ789');expect(command).toHaveBeenNthCalledWith(2,{roomCode:'XYZ789'});old.resolve();await old.promise;expect(sync.isCurrent('XYZ789')).toBe(true);expect(command).toHaveBeenCalledTimes(2);});
 it('sends a fresh immediate request when the same room is re-entered in a new generation',async()=>{const env=environment(),old=deferred(),command=vi.fn().mockImplementationOnce(()=>old.promise).mockResolvedValue({roomCode:'ABC234',completed:true}),action=createTouchLobbyPresenceAction(command as never),sync=createActiveLobbyPresenceCoordinator({}, {touch:action,environment:env.value});sync.enter('ABC234');sync.leave();sync.enter('ABC234');expect(command).toHaveBeenCalledTimes(2);expect(command).toHaveBeenNthCalledWith(2,{roomCode:'ABC234'});old.resolve();await old.promise;expect(sync.isCurrent('ABC234')).toBe(true);});
 it('cleans timers/listeners and protects a new room from stale old-room completion',async()=>{const env=environment(),old=deferred(),errors:unknown[]=[],touch=vi.fn().mockImplementationOnce(()=>old.promise).mockResolvedValue({roomCode:'XYZ789',completed:true}),sync=createActiveLobbyPresenceCoordinator({onError:error=>errors.push(error)}, {touch,environment:env.value});sync.enter('ABC234');sync.enter('XYZ789');expect(env.value.clearInterval).toHaveBeenCalled();expect(sync.isCurrent('XYZ789')).toBe(true);old.resolve();await old.promise;expect(errors).toEqual([]);sync.leave();expect(sync.isCurrent('XYZ789')).toBe(false);const calls=touch.mock.calls.length;env.interval();env.focus();env.online();await Promise.resolve();expect(touch).toHaveBeenCalledTimes(calls);});
 it('contains presence scheduling only, never lobby/game polling',()=>{expect(coordinator).toContain('setInterval');for(const forbidden of ['getLobby','getActiveGameState','roomLobbySync','roomSync','setTimeout'])expect(coordinator).not.toContain(forbidden);});
});

describe('shell lifecycle integration',()=>{
 it('runs exactly one presence mode and restarts lobby presence after Return to Lobby',()=>{expect(shell).toContain('lobbyPresence.enter(lobby.room.code)');expect(shell).toContain("if(lobby.room.status==='active')");expect(shell).toContain('lobbyPresence.leave();activeLobbySnapshot=lobby');expect(shell).toContain('lobbyPresence.leave();void roomKickSync.leave();activeRoomLifecycle.enter(code)');expect(shell).toContain('onReturnedLobby:async lobby=>');expect(shell).toContain('renderLobbyState(lobby,pendingLobbyNotice)');});
 it('stops lobby presence for explicit Leave, Start, Kick, and route cleanup',()=>{expect(shell).toContain("pendingJoinNotice='You were removed from the room by the host.';lobbyPresence.leave()");expect(shell).toMatch(/leaveButton\.onclick[\s\S]*?lobbyPresence\.leave\(\)/);expect(shell).toMatch(/startButton\.onclick[\s\S]*?lobbyPresence\.leave\(\)/);expect(shell).toContain('lobbyPresence.leave();gamePresence.leave();activeRoomLifecycle.leave()');});
 it('restarts after failed Leave or Start only while the same lobby remains current',()=>{expect(shell).toContain("if(roomLobbySync.isCurrent(lobby.room.code))lobbyPresence.enter(lobby.room.code)");expect((shell.match(/if\(roomLobbySync\.isCurrent\(lobby\.room\.code\)\)lobbyPresence\.enter\(lobby\.room\.code\)/g)??[]).length).toBeGreaterThanOrEqual(2);});
});
