import {describe,expect,it} from 'vitest';import {applyAction} from '../src/games/worship-me/engine/reducer';import {deserializeGame,serializeGame} from '../src/games/worship-me/engine/serialization';import {exportPlayByPlay,playByPlayFilename} from '../src/games/worship-me/engine/history';import {getLegalActions} from '../src/games/worship-me/engine/legalActions';import {evaluateBotAction,commitBotAction} from '../src/games/worship-me/ai/runner';import {simulateGame} from '../src/games/worship-me/ai/simulate';import {game,player,reveal} from './helpers';
describe('persistence and bots',()=>{
 it('round-trips queue, claims, and placement progress',()=>{let s=game(),p=player(s);s=applyAction(s,{type:'placeTile',cellId:'1,1',kind:'bless',playerId:p.id});const x=deserializeGame(serializeGame(s));expect(x.actionQueue).toEqual(s.actionQueue);expect(x.tileClaims).toEqual(s.tileClaims);expect(x.placementsUsed[p.id]).toBe(1)});
 it('round-trips a pending resolution decision',()=>{let s=game(),p=player(s),a=reveal(s,'1,1'),b=reveal(s,'1,2'),round=s.round;a.villagers.push(p.color);s=applyAction(s,{type:'placeEdge',from:a.id,to:b.id,kind:'bless',playerId:p.id});while(s.phase==='placement'&&s.round===round)s=applyAction(s,{type:'endTurn',playerId:s.turnOrder[s.currentPlayerIndex]});expect(deserializeGame(serializeGame(s)).pendingResolution).toEqual(s.pendingResolution)});
 it('rejects pre-penalty saves instead of fabricating placement effects',()=>{expect(()=>deserializeGame(JSON.stringify({...game(),schemaVersion:6}))).toThrow(/schema v9/)});
 it('bot selects one of the legal queued placements without mutating live state',()=>{const s=game(),before=serializeGame(s),legal=getLegalActions(s),choice=evaluateBotAction(s,'balanced');expect(legal).toContainEqual(choice.action);expect(serializeGame(s)).toBe(before);const counts=choice.diagnostics.legalCandidateCounts;expect(counts.totalPlacements).toBe(legal.filter(a=>a.type!=='endTurn').length);expect(counts.blessTile+counts.blessEdge+counts.smiteTile+counts.smiteEdge).toBe(counts.totalPlacements);expect(choice.diagnostics.topCandidates.length).toBeGreaterThan(0);expect(choice.diagnostics.topCandidates[0].score).toBeGreaterThanOrEqual(choice.diagnostics.topCandidates.at(-1)!.score);const next=commitBotAction(s,choice);expect(next.actionQueue).toHaveLength(choice.action.type==='endTurn'?0:1);if(choice.action.type!=='endTurn'){const aiDecision=next.history.events.at(-1)!.data.aiDecision as typeof choice.diagnostics;expect(aiDecision.legalCandidateCounts).toEqual(counts);expect(aiDecision.selected.label).toBe(choice.diagnostics.selected.label)}expect(serializeGame(s)).toBe(before)});
 it('same seed reproduces the same simulation',()=>{const options={seed:'repeat',players:['random','random'] as ('random')[],maxRounds:5,maxActions:100,trace:true};expect(simulateGame(options).trace).toEqual(simulateGame(options).trace)});
 it('headless AI progresses without a DOM',()=>{const r=simulateGame({seed:'smoke',players:['balanced','growth'],maxRounds:5,maxActions:100,trace:true});expect(r.totalActions).toBeGreaterThan(0);expect(r.errors).toEqual([])});
 it('exports parseable structured placement history',()=>{let s=game(),p=player(s);s=applyAction(s,{type:'placeTile',cellId:'1,1',kind:'bless',playerId:p.id});const parsed=JSON.parse(JSON.stringify(exportPlayByPlay(s)));expect(parsed.schemaVersion).toBe(9);expect(parsed.events[0]).toMatchObject({type:'placement',queuedActionId:'R1-Q01',playerId:p.id});expect(playByPlayFilename(s)).toMatch(/^worship-me-playbyplay-\d{4}-\d{2}-\d{2}-seed-test\.json$/)});
 it('preserves directed Bless Edge origin and destination in state and history',()=>{let s=game(),p=player(s);reveal(s,'1,1');reveal(s,'1,2');s=applyAction(s,{type:'placeEdge',from:'1,1',to:'1,2',kind:'bless',playerId:p.id});expect(s.actionQueue[0].placement).toMatchObject({from:'1,1',to:'1,2'});expect(s.history.events[0].data).toMatchObject({targetType:'edge',origin:'1,1',destination:'1,2'})});
 it('bots can complete and expose placement and resolution intelligence',()=>{const r=simulateGame({seed:'strategy-validation-0',players:['balanced','growth','templeRush','random'],maxRounds:150,maxActions:5000,trace:true});expect(r.stalled).toBe(false);expect(r.winnerId).toBeTruthy();expect(r.history?.events.some(e=>e.type==='victoryCheck'&&(e.data.result as {winnerId?:string}).winnerId===r.winnerId)).toBe(true);const placements=r.history!.events.filter(e=>e.type==='placement'),decisions=r.history!.events.filter(e=>e.type==='resolutionDecision');expect(placements.length).toBeGreaterThan(0);expect(placements.every(e=>!!e.data.aiDecision)).toBe(true);expect(decisions.length).toBeGreaterThan(0);expect(decisions.every(e=>!!e.data.aiResolution)).toBe(true);expect(()=>JSON.parse(JSON.stringify(r.history))).not.toThrow()});
 it('safety limit marks an unfinished game stalled',()=>{expect(simulateGame({seed:'limit',players:['random','random'],maxRounds:1,maxActions:1}).stalled).toBe(true)});
});
