import {describe,expect,it} from 'vitest';import {applyAction} from '../src/games/worship-me/engine/reducer';import {edgeKey} from '../src/games/worship-me/engine/board';import {game,player,reveal} from './helpers';
describe('queued placement phase',()=>{
 it('keeps the same player for both normal placements then advances',()=>{let s=game(),p=player(s);s=applyAction(s,{type:'placeTile',cellId:'1,1',kind:'bless',playerId:p.id});expect(s.turnOrder[s.currentPlayerIndex]).toBe(p.id);s=applyAction(s,{type:'placeTile',cellId:'1,2',kind:'bless',playerId:p.id});expect(s.turnOrder[s.currentPlayerIndex]).toBe(player(s,1).id);expect(s.actionQueue.map(x=>x.sequence)).toEqual([1,2])});
 it('permits only one Smite',()=>{let s=game(),p=player(s);reveal(s,'1,1');reveal(s,'1,2');s=applyAction(s,{type:'placeTile',cellId:'1,1',kind:'smite',playerId:p.id});expect(()=>applyAction(s,{type:'placeTile',cellId:'1,2',kind:'smite',playerId:p.id})).toThrow(/Smite/)});
 it('does not allow Smite Tile on face-down land',()=>{const s=game(),p=player(s);expect(()=>applyAction(s,{type:'placeTile',cellId:'1,1',kind:'smite',playerId:p.id})).toThrow(/Face-down/)});
 it('ending early advances without queueing an action',()=>{let s=game(),p=player(s);s=applyAction(s,{type:'endTurn',playerId:p.id});expect(s.actionQueue).toHaveLength(0);expect(s.turnOrder[s.currentPlayerIndex]).toBe(player(s,1).id)});
 it('preserves exact placement order',()=>{let s=game(),a=player(s),b=player(s,1);for(const id of ['1,1','1,2'])s=applyAction(s,{type:'placeTile',cellId:id,kind:'bless',playerId:a.id});for(const id of ['1,3','1,4'])s=applyAction(s,{type:'placeTile',cellId:id,kind:'bless',playerId:b.id});expect(s.eventLog.filter(x=>x.includes(' placed ')).map(x=>x.split(' ')[1])).toEqual([a.id,a.id,b.id,b.id])});
 it('Bless Tile immediately locks tile and incident edges from opponents',()=>{let s=game(),a=player(s),b=player(s,1);reveal(s,'1,1');reveal(s,'1,2');s=applyAction(s,{type:'placeTile',cellId:'1,1',kind:'bless',playerId:a.id});s=applyAction(s,{type:'endTurn',playerId:a.id});expect(()=>applyAction(s,{type:'placeEdge',from:'1,1',to:'1,2',kind:'bless',playerId:b.id})).toThrow(/claim/)});
 it('Bless Edge locks that edge',()=>{let s=game(),a=player(s),b=player(s,1);reveal(s,'1,1');reveal(s,'1,2');s=applyAction(s,{type:'placeEdge',from:'1,1',to:'1,2',kind:'bless',playerId:a.id});s=applyAction(s,{type:'endTurn',playerId:a.id});expect(s.edgeClaims[edgeKey('1,1','1,2')]).toBeTruthy();expect(()=>applyAction(s,{type:'placeEdge',a:'1,2',b:'1,1',kind:'smite',playerId:b.id})).toThrow(/already/)});
 it('Smite Edge locks both endpoint tiles from opponents',()=>{let s=game(),a=player(s),b=player(s,1);reveal(s,'1,1');reveal(s,'1,2');s=applyAction(s,{type:'placeEdge',a:'1,1',b:'1,2',kind:'smite',playerId:a.id});s=applyAction(s,{type:'endTurn',playerId:a.id});expect(()=>applyAction(s,{type:'placeTile',cellId:'1,1',kind:'bless',playerId:b.id})).toThrow(/Smite Edge/)});
 it('targets each Temple at most once each round',()=>{let s=game(),a=player(s),b=player(s,1),id=b.templeCellId;s=applyAction(s,{type:'placeTile',cellId:id,kind:'bless',playerId:a.id});s=applyAction(s,{type:'endTurn',playerId:a.id});expect(()=>applyAction(s,{type:'placeTile',cellId:id,kind:'smite',playerId:b.id})).toThrow(/already/)});
});
