import {describe,expect,it} from 'vitest';import {resolveProduction} from '../src/games/worship-me/engine/production';import {resolveHomeBirths} from '../src/games/worship-me/engine/homeBirth';import {createPriests} from '../src/games/worship-me/engine/priests';import {validatePlacement} from '../src/games/worship-me/engine/placementLegality';import {game,player,reveal} from './helpers';
describe('production and Priests',()=>{
 it('normal and Blessed Farms produce once at their rates',()=>{let s=game(),p=player(s),a=reveal(s,'1,1'),b=reveal(s,'1,2');a.villagers.push(p.color);b.villagers.push(p.color);b.tileModifier={kind:'bless',playerId:p.id};resolveProduction(s);expect(a.wheat).toBe(1);expect(b.wheat).toBe(2)});
 it('Smited Farm and Bakery produce zero',()=>{let s=game(),p=player(s),a=reveal(s,'1,1'),b=reveal(s,'1,2','bakery');a.villagers.push(p.color);b.villagers.push(p.color);b.wheat=2;a.tileModifier=b.tileModifier={kind:'smite',playerId:p.id};resolveProduction(s);expect(a.wheat).toBe(0);expect(b.bread).toBe(0)});
 it('Priest boosts Farm and Bakery but does not stack with Bless',()=>{let s=game(),p=player(s),a=reveal(s,'1,1'),b=reveal(s,'1,2','bakery');a.priests.push(p.color);a.tileModifier={kind:'bless',playerId:p.id};b.priests.push(p.color);b.wheat=2;resolveProduction(s);expect(a.wheat).toBe(2);expect(b.bread).toBe(1);expect(b.wheat).toBe(1)});
 it('Priest-only Home has normal birth and no owner bonus',()=>{let s=game(),p=player(s),h=reveal(s,'1,1','home');h.priests.push(p.color);h.villagers.push(p.color);h.bread=1;resolveHomeBirths(s);expect(s.newVillagerBag.filter(x=>x===p.color).length).toBeLessThanOrEqual(1)});
 it('explicitly Blessed Home adds the Blessing player color',()=>{let s=game(),a=player(s),b=player(s,1),h=reveal(s,'1,1','home');h.villagers.push(a.color,b.color);h.bread=1;h.tileModifier={kind:'bless',playerId:a.id};resolveHomeBirths(s);expect(s.newVillagerBag.filter(x=>x===a.color).length).toBeGreaterThanOrEqual(1)});
 it('opponent Priest protects tile and incident edge absolutely',()=>{let s=game(),a=player(s),b=player(s,1),c=reveal(s,'1,1');reveal(s,'1,2');c.priests.push(b.color);expect(()=>validatePlacement(s,{type:'placeTile',cellId:c.id,kind:'bless',playerId:a.id})).toThrow(/Priest/);expect(()=>validatePlacement(s,{type:'placeEdge',a:c.id,b:'1,2',kind:'smite',playerId:a.id})).toThrow(/Priest/)});
 it('creates one Priest and leaves it in a full Square',()=>{let s=game(),p=player(s),t=s.board.find(c=>c.id===p.templeCellId)!,q=s.board.find(c=>c.visibleKind==='square')!;t.villagers.push(p.color,p.color,p.color);q.villagers=Array(s.players.length+2).fill('neutral');createPriests(s);expect(t.priests).toContain(p.color);expect(p.priestsCreated).toBe(1)});
 it('distinguishes Home production that enters the board from a blocked entry',()=>{let s=game(),p=player(s),h=reveal(s,'1,1','home'),q=s.board.find(c=>c.visibleKind==='square')!;q.villagers=[];h.villagers.push(p.color,p.color);h.bread=1;let [open]=resolveHomeBirths(s);expect(open).toMatchObject({homeProductionTriggered:true,entryAttempted:true,enteredBoard:true});h.bread=1;q.villagers=Array(s.players.length+2).fill('neutral');const before=s.newVillagerBag.length;let [blocked]=resolveHomeBirths(s);expect(blocked).toMatchObject({homeProductionTriggered:true,entryAttempted:true,enteredBoard:false,blockedReason:'village-square-full'});expect(s.newVillagerBag.length).toBeGreaterThan(before)});
});
