import {readFileSync,readdirSync} from 'node:fs';
import {describe,expect,it,vi} from 'vitest';
import type {SupabaseClient} from '@supabase/supabase-js';
import type {Lobby} from '../src/platform/rooms/lobby';
import {createRoomLobbySyncCoordinator} from '../src/platform/rooms/roomLobbySync';
import {subscribeRoomLobbyUpdates,type RoomLobbySyncStatus,type SubscribeRoomLobbyUpdatesOptions} from '../src/platform/rooms/subscribeRoomLobbyUpdates';

const migrationUrl=new URL('../supabase/migrations/',import.meta.url);
const migration=readFileSync(new URL('../supabase/migrations/20260922000001_realtime_lobby_sync.sql',import.meta.url),'utf8');
const gameMigration=readFileSync(new URL('../supabase/migrations/20260922000000_realtime_game_sync.sql',import.meta.url),'utf8');
const subscriptionSource=readFileSync(new URL('../src/platform/rooms/subscribeRoomLobbyUpdates.ts',import.meta.url),'utf8');
const coordinatorSource=readFileSync(new URL('../src/platform/rooms/roomLobbySync.ts',import.meta.url),'utf8');
const shell=readFileSync(new URL('../src/platform/shell.ts',import.meta.url),'utf8');
const lobbySource=readFileSync(new URL('../src/platform/rooms/lobby.ts',import.meta.url),'utf8');
const lobby=(code='ABC234',players=1,status='lobby'):Lobby=>({room:{id:`room-${code}`,code,status,gameId:'game-1',maxPlayers:8,joinMode:'public',isCurrentUserHost:true},players:Array.from({length:players},(_,index)=>({control:'human' as const,participantId:`user-${index+1}`,userId:`user-${index+1}`,displayName:index?'Bob':'Alice',playerColor:index?'blue':'red',turnOrder:null,isReady:index===0,isHost:index===0,isCurrentUser:index===0}))});
const deferred=<T>()=>{let resolve!:(value:T)=>void,reject!:(reason?:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no;});return{promise,resolve,reject};};

function realtimeClient(){
 let change:((payload:{new:Record<string,unknown>})=>void)|undefined,status:((value:'SUBSCRIBED'|'CHANNEL_ERROR'|'TIMED_OUT'|'CLOSED')=>void)|undefined;
 const channel={on:vi.fn((_kind:string,_filter:unknown,callback:(payload:{new:Record<string,unknown>})=>void)=>{change=callback;return channel;}),subscribe:vi.fn((callback:typeof status)=>{status=callback;return channel;})};
 const client={auth:{getSession:vi.fn().mockResolvedValue({data:{session:{user:{id:'user-1'}}},error:null})},channel:vi.fn(()=>channel),removeChannel:vi.fn().mockResolvedValue('ok')} as unknown as SupabaseClient;
 return{client,channel,emit:(row:Record<string,unknown>)=>change?.({new:row}),status:(value:'SUBSCRIBED'|'CHANNEL_ERROR'|'TIMED_OUT'|'CLOSED')=>status?.(value)};
}

function harness(fetchLobby=vi.fn<(roomCode:string)=>Promise<Lobby>>()){
 const subscriptions:SubscribeRoomLobbyUpdatesOptions[]=[],removed:ReturnType<typeof vi.fn>[]=[];
 const subscribe=vi.fn(async(options:SubscribeRoomLobbyUpdatesOptions)=>{subscriptions.push(options);const unsubscribe=vi.fn().mockResolvedValue(undefined);removed.push(unsubscribe);options.onStatus('live');return{roomCode:options.roomCode,ready:Promise.resolve<RoomLobbySyncStatus>('live'),unsubscribe};});
 const lobbies:Lobby[]=[],statuses:RoomLobbySyncStatus[]=[],errors:unknown[]=[];
 const coordinator=createRoomLobbySyncCoordinator({onLobby:value=>lobbies.push(value),onStatus:value=>statuses.push(value),onError:value=>errors.push(value)},{fetchLobby,subscribe});
 return{coordinator,fetchLobby,subscribe,subscriptions,removed,lobbies,statuses,errors};
}

function unavailableHarness(fetchLobby=vi.fn<(roomCode:string)=>Promise<Lobby>>()){
 const subscriptions:SubscribeRoomLobbyUpdatesOptions[]=[],removed:ReturnType<typeof vi.fn>[]=[];
 const subscribe=vi.fn(async(options:SubscribeRoomLobbyUpdatesOptions)=>{subscriptions.push(options);const unsubscribe=vi.fn().mockResolvedValue(undefined);removed.push(unsubscribe);return{roomCode:options.roomCode,ready:Promise.resolve<RoomLobbySyncStatus>('unavailable'),unsubscribe};});
 const lobbies:Lobby[]=[],statuses:RoomLobbySyncStatus[]=[],errors:unknown[]=[];
 const coordinator=createRoomLobbySyncCoordinator({onLobby:value=>lobbies.push(value),onStatus:value=>statuses.push(value),onError:value=>errors.push(value)},{fetchLobby,subscribe});
 return{coordinator,fetchLobby,subscribe,subscriptions,removed,lobbies,statuses,errors};
}

describe('Milestone 10 safe lobby signal migration',()=>{
 it('retains the M10 migration before all forward migrations',()=>{const names=readdirSync(migrationUrl,{withFileTypes:true}).filter(entry=>!entry.isDirectory()&&entry.name.endsWith('.sql')).map(entry=>entry.name).sort();expect(names).toHaveLength(20);expect(names.at(-10)).toBe('20260922000000_realtime_game_sync.sql');expect(names.at(-9)).toBe('20260922000001_realtime_lobby_sync.sql');expect(names.at(-8)).toBe('20260922000002_multiplayer_ai_players.sql');expect(names.at(-7)).toBe('20260923000000_fix_multiplayer_ai_sql_ambiguity.sql');expect(names.at(-6)).toBe('20260923000001_fix_start_game_coalesce.sql');expect(names.at(-5)).toBe('20260923000002_active_player_ai_takeover.sql');expect(names.at(-4)).toBe('20260924000000_lobby_discovery_and_host_moderation.sql');expect(names.at(-3)).toBe('20260924000001_return_finished_game_to_lobby.sql');expect(names.at(-2)).toBe('20260924000002_fix_return_to_lobby_signal_read.sql');expect(names.at(-1)).toBe('20260924000003_lobby_presence_and_stale_directory.sql');expect(names.filter(name=>name.includes('realtime_lobby_sync'))).toEqual(['20260922000001_realtime_lobby_sync.sql']);});
 it('defines only safe synchronization metadata and safely backfills existing rooms',()=>{const table=migration.slice(migration.indexOf('create table public.room_lobby_updates'),migration.indexOf('insert into public.room_lobby_updates'));for(const column of ['room_id uuid primary key','room_code text not null unique','lobby_version bigint not null','updated_at timestamptz not null'])expect(table).toContain(column);expect(table).toContain('references public.rooms(id) on delete cascade');expect(table).toContain("room_code ~ '^[A-Z0-9]{6,10}$'");expect(table).toContain('lobby_version >= 0');for(const forbidden of ['host_user_id','user_id','display_name','player_color','is_ready','turn_order','game_state','board','bot','strategy'])expect(table).not.toContain(forbidden);const backfill=migration.slice(migration.indexOf('insert into public.room_lobby_updates'),migration.indexOf('alter table public.room_lobby_updates'));expect(backfill).toContain('select r.id, r.code, 0, pg_catalog.now()');expect(backfill).toContain('from public.rooms as r');expect(backfill).not.toContain('room_players');expect(backfill).not.toContain('game_state');});
 it('enables membership RLS and grants authenticated users SELECT only',()=>{expect(migration).toContain('alter table public.room_lobby_updates enable row level security');for(const role of ['public','anon','authenticated','service_role'])expect(migration).toContain(`revoke all on table public.room_lobby_updates from ${role}`);expect(migration).toContain('grant select on table public.room_lobby_updates to authenticated');expect(migration).toContain('to authenticated\nusing (ngsllc_private.is_room_member(room_id))');expect(migration).not.toMatch(/grant\s+(?:insert|update|delete|all)[\s\S]*?room_lobby_updates\s+to\s+(?:anon|authenticated)/i);});
 it('initializes every new room using a locked-down private trigger function',()=>{const fn=migration.slice(migration.indexOf('create function ngsllc_private.initialize_room_lobby_update'),migration.indexOf('create trigger rooms_initialize_lobby_update'));expect(fn).toContain('security definer');expect(fn).toContain("set search_path = ''");expect(fn).toContain('values (new.id, new.code, 0, pg_catalog.now())');for(const role of ['public','anon','authenticated','service_role'])expect(fn).toContain(`revoke all on function ngsllc_private.initialize_room_lobby_update() from ${role}`);expect(migration).toContain('after insert on public.rooms');});
 it('terminates both private PL/pgSQL trigger function bodies before their revoke statements',()=>{for(const name of ['initialize_room_lobby_update','bump_room_lobby_update']){const start=migration.indexOf(`create function ngsllc_private.${name}()`),revoke=migration.indexOf(`revoke all on function ngsllc_private.${name}()`,start),fn=migration.slice(start,revoke);expect(start).toBeGreaterThanOrEqual(0);expect(revoke).toBeGreaterThan(start);expect(fn).toMatch(/end;\r?\n\$\$;\r?\n\s*$/);}});
 it('bumps only visible player and room mutations and ignores last-seen and turn-order updates',()=>{expect(migration).toContain('after insert or delete or update of display_name, player_color, is_ready');expect(migration).toContain('after update of host_user_id, status on public.rooms');expect(migration).toContain('new.display_name is distinct from old.display_name');expect(migration).toContain('new.player_color is distinct from old.player_color');expect(migration).toContain('new.is_ready is distinct from old.is_ready');expect(migration).toContain('new.host_user_id is distinct from old.host_user_id');expect(migration).toContain('new.status is distinct from old.status');const declarations=migration.match(/create trigger[\s\S]*?execute function ngsllc_private\.bump_room_lobby_update\(\);/g)?.join('\n')??'';expect(declarations).not.toContain('last_seen_at');expect(declarations).not.toContain('turn_order');});
 it('increments the version server-side with no client-provided or canonical state data',()=>{const fn=migration.slice(migration.indexOf('create function ngsllc_private.bump_room_lobby_update'),migration.indexOf('create trigger room_players_bump_lobby_update'));expect(fn).toContain('signal.lobby_version + 1');expect(fn).toContain('updated_at = pg_catalog.now()');expect(fn).toContain('security definer');expect(fn).toContain("set search_path = ''");for(const role of ['public','anon','authenticated','service_role'])expect(fn).toContain(`revoke all on function ngsllc_private.bump_room_lobby_update() from ${role}`);expect(fn).not.toContain('game_state');});
 it('publishes only both safe signal tables, never lobby or canonical source tables',()=>{expect(gameMigration).toContain('alter publication supabase_realtime add table public.room_game_updates');expect(migration).toContain('alter publication supabase_realtime add table public.room_lobby_updates');expect(migration).not.toMatch(/add table public\.(?:rooms|room_players|room_states)\b/);expect(`${gameMigration}\n${migration}`).not.toMatch(/replica identity full/i);});
});

describe('safe lobby update subscription',()=>{
 it('authenticates, normalizes, and subscribes to exact UPDATE-only version signals',async()=>{const rt=realtimeClient(),signals:unknown[]=[],statuses:RoomLobbySyncStatus[]=[];const subscription=await subscribeRoomLobbyUpdates({roomCode:' abc234 ',onSignal:value=>signals.push(value),onStatus:value=>statuses.push(value)},rt.client);expect(rt.client.auth.getSession).toHaveBeenCalled();expect(rt.client.channel).toHaveBeenCalledWith('room-lobby-updates:ABC234');expect(rt.channel.on).toHaveBeenCalledWith('postgres_changes',{event:'UPDATE',schema:'public',table:'room_lobby_updates',filter:'room_code=eq.ABC234'},expect.any(Function));rt.status('SUBSCRIBED');await expect(subscription.ready).resolves.toBe('live');expect(statuses).toEqual(['connecting','live']);await subscription.unsubscribe();expect(rt.client.removeChannel).toHaveBeenCalledTimes(1);});
 it('ignores malformed, wrong-room, negative, fractional, and string versions',async()=>{const rt=realtimeClient(),signals:unknown[]=[],subscription=await subscribeRoomLobbyUpdates({roomCode:'ABC234',onSignal:value=>signals.push(value),onStatus:()=>{}},rt.client);rt.status('SUBSCRIBED');rt.emit({room_code:'ABC234',lobby_version:4});for(const row of [{room_code:'XYZ789',lobby_version:5},{room_code:'ABC234',lobby_version:-1},{room_code:'ABC234',lobby_version:1.5},{room_code:'ABC234',lobby_version:'6'},{lobby_version:7}])rt.emit(row);expect(signals).toEqual([{roomCode:'ABC234',lobbyVersion:4}]);await subscription.unsubscribe();});
 it('reports connection failure while exposing no roster-shaped payload',async()=>{const rt=realtimeClient(),signals=vi.fn(),statuses:RoomLobbySyncStatus[]=[],subscription=await subscribeRoomLobbyUpdates({roomCode:'ABC234',onSignal:signals,onStatus:value=>statuses.push(value)},rt.client);rt.status('CHANNEL_ERROR');await expect(subscription.ready).resolves.toBe('unavailable');expect(statuses).toEqual(['connecting','unavailable']);for(const secret of ['display_name','player_color','is_ready','host_user_id','game_state'])expect(subscriptionSource).not.toContain(secret);await subscription.unsubscribe();});
});

describe('lobby synchronization coordinator',()=>{
 it('establishes one subscription before the initial/manual trusted fetch',async()=>{const h=harness(vi.fn().mockResolvedValue(lobby()));await h.coordinator.enter('abc234');expect(h.subscribe).toHaveBeenCalledTimes(1);expect(h.fetchLobby).not.toHaveBeenCalled();await h.coordinator.enter('ABC234');expect(h.subscribe).toHaveBeenCalledTimes(1);await h.coordinator.refresh();expect(h.fetchLobby).toHaveBeenCalledWith('ABC234');});
 it('refreshes for a newer signal and ignores equal or older handled versions',async()=>{const h=harness(vi.fn().mockResolvedValue(lobby()));await h.coordinator.enter('ABC234');h.subscriptions[0].onSignal({roomCode:'ABC234',lobbyVersion:3});await vi.waitFor(()=>expect(h.coordinator.handledVersion).toBe(3));h.subscriptions[0].onSignal({roomCode:'ABC234',lobbyVersion:2});h.subscriptions[0].onSignal({roomCode:'ABC234',lobbyVersion:3});await Promise.resolve();expect(h.fetchLobby).toHaveBeenCalledTimes(1);});
 it('captures the target version and runs exactly one catch-up for signals arriving in flight',async()=>{const first=deferred<Lobby>(),fetchLobby=vi.fn().mockImplementationOnce(()=>first.promise).mockResolvedValueOnce(lobby('ABC234',2)),h=harness(fetchLobby);await h.coordinator.enter('ABC234');h.subscriptions[0].onSignal({roomCode:'ABC234',lobbyVersion:5});h.subscriptions[0].onSignal({roomCode:'ABC234',lobbyVersion:6});h.subscriptions[0].onSignal({roomCode:'ABC234',lobbyVersion:7});expect(fetchLobby).toHaveBeenCalledTimes(1);first.resolve(lobby());await vi.waitFor(()=>expect(h.coordinator.handledVersion).toBe(7));expect(fetchLobby).toHaveBeenCalledTimes(2);expect(h.lobbies.at(-1)?.players).toHaveLength(2);});
 it('never overlaps reads during a burst',async()=>{const pending=deferred<Lobby>(),fetchLobby=vi.fn(()=>pending.promise),h=harness(fetchLobby);await h.coordinator.enter('ABC234');for(const lobbyVersion of [1,2,3,4])h.subscriptions[0].onSignal({roomCode:'ABC234',lobbyVersion});expect(fetchLobby).toHaveBeenCalledTimes(1);pending.resolve(lobby());await vi.waitFor(()=>expect(fetchLobby).toHaveBeenCalledTimes(2));});
 it('performs one catch-up after a live connection gap but not after normal initial live',async()=>{const h=harness(vi.fn().mockResolvedValue(lobby()));await h.coordinator.enter('ABC234');h.coordinator.markInitialFetchComplete();expect(h.fetchLobby).not.toHaveBeenCalled();h.subscriptions[0].onStatus('unavailable');h.subscriptions[0].onStatus('live');await vi.waitFor(()=>expect(h.fetchLobby).toHaveBeenCalledTimes(1));h.subscriptions[0].onStatus('live');await Promise.resolve();expect(h.fetchLobby).toHaveBeenCalledTimes(1);});
 it('defers unavailable-to-live recovery until the initial fetch completes',async()=>{const h=unavailableHarness(vi.fn().mockResolvedValue(lobby()));await h.coordinator.enter('ABC234');h.subscriptions[0].onStatus('live');expect(h.fetchLobby).not.toHaveBeenCalled();h.coordinator.markInitialFetchComplete();await vi.waitFor(()=>expect(h.fetchLobby).toHaveBeenCalledTimes(1));expect(h.lobbies).toHaveLength(1);h.coordinator.markInitialFetchComplete();await Promise.resolve();expect(h.fetchLobby).toHaveBeenCalledTimes(1);});
 it('unsubscribes on leave/room change and ignores delayed old-room signals',async()=>{const h=harness(vi.fn().mockResolvedValue(lobby('XYZ789')));await h.coordinator.enter('ABC234');const old=h.subscriptions[0];await h.coordinator.enter('XYZ789');expect(h.removed[0]).toHaveBeenCalledTimes(1);old.onSignal({roomCode:'ABC234',lobbyVersion:9});expect(h.fetchLobby).not.toHaveBeenCalled();await h.coordinator.leave();expect(h.removed[1]).toHaveBeenCalledTimes(1);});
 it('ignores an old-room fetch that completes after changing rooms',async()=>{const old=deferred<Lobby>(),fetchLobby=vi.fn().mockImplementationOnce(()=>old.promise).mockResolvedValueOnce(lobby('XYZ789')),h=harness(fetchLobby);await h.coordinator.enter('ABC234');const request=h.coordinator.refresh();await h.coordinator.enter('XYZ789');old.resolve(lobby('ABC234',2));await request;expect(h.lobbies).toHaveLength(0);await h.coordinator.refresh();expect(h.lobbies.map(value=>value.room.code)).toEqual(['XYZ789']);});
 it('keeps the last valid snapshot on failure and leaves manual refresh usable',async()=>{const fetchLobby=vi.fn().mockResolvedValueOnce(lobby()).mockRejectedValueOnce(Error('offline')).mockResolvedValueOnce(lobby('ABC234',2)),h=harness(fetchLobby);await h.coordinator.enter('ABC234');await h.coordinator.refresh();await h.coordinator.refresh();expect(h.errors).toHaveLength(1);expect(h.lobbies).toHaveLength(1);await h.coordinator.refresh();expect(h.lobbies.at(-1)?.players).toHaveLength(2);});
});

describe('lobby UI and trust boundary integration',()=>{
 it('starts both subscriptions together before the initial lobby read',()=>{const enter=shell.indexOf('await Promise.all([roomSync.enter(route.code),roomLobbySync.enter(route.code)])'),read=shell.indexOf('return renderLobby(route.code)',enter);expect(enter).toBeGreaterThan(0);expect(read).toBeGreaterThan(enter);});
 it('renders joins, leaves, colors, Ready, host controls, and Start eligibility from fresh participant snapshots',()=>{expect(shell).toContain('onLobby:lobby=>handleLobbySnapshot(lobby,pendingLobbyNotice)');expect(shell).toContain('renderLobbyPlayerRows(lobby.players,lobby.room.isCurrentUserHost)');expect(shell).toContain('allReadyPreview=lobby.players.length>=defaultConfig.playerMin');expect(shell).toContain('lobby.room.isCurrentUserHost');expect(shell).toContain('WORSHIP_ME_PLAYER_COLORS.includes');});
 it('uses one coordinator for automatic and manual refresh without adding subscriptions on rerender',()=>{expect(shell).toContain("'[data-refresh]')!.onclick=()=>{pendingLobbyNotice='';void roomLobbySync.refresh();}");expect(shell).not.toContain('createRoomLobbySyncCoordinator({\n   onLobby');expect((shell.match(/createRoomLobbySyncCoordinator\(/g)??[])).toHaveLength(1);});
 it('aggregates both lobby channels and keeps lobby sync alive during active play',()=>{expect(shell).toContain("gameSyncStatus==='unavailable'||lobbySyncStatus==='unavailable'");expect(shell).toContain("gameSyncStatus==='connecting'||lobbySyncStatus==='connecting'");expect(shell).toContain('data-sync-status="lobby"');expect(shell).toContain('data-sync-status="game"');expect(shell).toContain('onState:result=>renderActiveGameState');expect(shell).not.toContain('void roomLobbySync.leave();renderActiveGameState');expect(shell).toContain('if(roomSync.latestTrustedVersion>0)return');});
 it('uses Realtime only as a version signal and snapshots only through getLobby',()=>{const browser=`${subscriptionSource}\n${coordinatorSource}\n${shell}`;expect(coordinatorSource).toContain('fetchLobby:getLobby');expect(lobbySource).toContain("from('rooms')");expect(lobbySource).toContain("from('room_players')");for(const table of ['rooms','room_players','room_states'])expect(subscriptionSource).not.toContain(`table:'${table}'`);for(const forbidden of ["from('room_lobby_updates')",'.insert(','.update(','.delete(','displayName','playerColor','isReady','hostUserId'])expect(`${subscriptionSource}\n${coordinatorSource}`).not.toContain(forbidden);expect(browser).not.toContain('setInterval');});
});
