import {readFileSync,readdirSync} from 'node:fs';
import {describe,expect,it,vi} from 'vitest';
import type {SupabaseClient} from '@supabase/supabase-js';
import {createGame} from '../src/games/worship-me/engine/setup';
import {buildWorshipMePublicGameView} from '../src/games/worship-me/publicGameView';
import {createRoomGameSyncCoordinator} from '../src/platform/rooms/roomGameSync';
import {subscribeRoomGameUpdates,type RoomGameSyncStatus,type SubscribeRoomGameUpdatesOptions} from '../src/platform/rooms/subscribeRoomGameUpdates';
import type {ActiveGameStateResult} from '../src/platform/types';

const migrationUrl=new URL('../supabase/migrations/',import.meta.url);
const migration=readFileSync(new URL('../supabase/migrations/20260922000000_realtime_game_sync.sql',import.meta.url),'utf8');
const subscriptionSource=readFileSync(new URL('../src/platform/rooms/subscribeRoomGameUpdates.ts',import.meta.url),'utf8');
const coordinatorSource=readFileSync(new URL('../src/platform/rooms/roomGameSync.ts',import.meta.url),'utf8');
const shell=readFileSync(new URL('../src/platform/shell.ts',import.meta.url),'utf8');
const getClient=readFileSync(new URL('../src/platform/rooms/getActiveGameState.ts',import.meta.url),'utf8');
const result=(version:number,roomCode='ABC234'):ActiveGameStateResult=>({roomCode,status:'active',stateVersion:version,viewerPlayerId:'p1',gameView:buildWorshipMePublicGameView(createGame(2,`sync-${version}`))});
const deferred=<T>()=>{let resolve!:(value:T)=>void,reject!:(reason?:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no;});return{promise,resolve,reject};};

function realtimeClient(){
 let change:((payload:{new:Record<string,unknown>})=>void)|undefined,status:((value:'SUBSCRIBED'|'CHANNEL_ERROR'|'TIMED_OUT'|'CLOSED')=>void)|undefined;
 const channel={on:vi.fn((_kind:string,_filter:unknown,callback:(payload:{new:Record<string,unknown>})=>void)=>{change=callback;return channel;}),subscribe:vi.fn((callback:typeof status)=>{status=callback;return channel;})};
 const client={auth:{getSession:vi.fn().mockResolvedValue({data:{session:{user:{id:'user-1'}}},error:null})},channel:vi.fn(()=>channel),removeChannel:vi.fn().mockResolvedValue('ok')} as unknown as SupabaseClient;
 return{client,channel,emit:(row:Record<string,unknown>)=>change?.({new:row}),status:(value:'SUBSCRIBED'|'CHANNEL_ERROR'|'TIMED_OUT'|'CLOSED')=>status?.(value)};
}

function syncHarness(fetchState=vi.fn<(request:{roomCode:string})=>Promise<ActiveGameStateResult|undefined>>()){
 const subscriptions:SubscribeRoomGameUpdatesOptions[]=[],removed:ReturnType<typeof vi.fn>[]=[];
 const subscribe=vi.fn(async(options:SubscribeRoomGameUpdatesOptions)=>{subscriptions.push(options);const unsubscribe=vi.fn().mockResolvedValue(undefined);removed.push(unsubscribe);options.onStatus('live');return{roomCode:options.roomCode,ready:Promise.resolve<RoomGameSyncStatus>('live'),unsubscribe};});
 const states:ActiveGameStateResult[]=[],statuses:RoomGameSyncStatus[]=[],errors:unknown[]=[];
 const coordinator=createRoomGameSyncCoordinator({onState:value=>states.push(value),onStatus:value=>statuses.push(value),onError:value=>errors.push(value)},{fetchState,subscribe});
 return{coordinator,fetchState,subscribe,subscriptions,removed,states,statuses,errors};
}

function unavailableSyncHarness(fetchState=vi.fn<(request:{roomCode:string})=>Promise<ActiveGameStateResult|undefined>>()){
 const subscriptions:SubscribeRoomGameUpdatesOptions[]=[],removed:ReturnType<typeof vi.fn>[]=[];
 const subscribe=vi.fn(async(options:SubscribeRoomGameUpdatesOptions)=>{subscriptions.push(options);const unsubscribe=vi.fn().mockResolvedValue(undefined);removed.push(unsubscribe);return{roomCode:options.roomCode,ready:Promise.resolve<RoomGameSyncStatus>('unavailable'),unsubscribe};});
 const states:ActiveGameStateResult[]=[],statuses:RoomGameSyncStatus[]=[],errors:unknown[]=[];
 const coordinator=createRoomGameSyncCoordinator({onState:value=>states.push(value),onStatus:value=>statuses.push(value),onError:value=>errors.push(value)},{fetchState,subscribe});
 return{coordinator,fetchState,subscribe,subscriptions,removed,states,statuses,errors};
}

describe('Milestone 9 safe signal migration',()=>{
 it('retains exactly one M9 migration before the M10 lobby-sync migration',()=>{const names=readdirSync(migrationUrl,{withFileTypes:true}).filter(entry=>!entry.isDirectory()&&entry.name.endsWith('.sql')).map(entry=>entry.name).sort();expect(names).toHaveLength(12);expect(names.at(-2)).toBe('20260922000000_realtime_game_sync.sql');expect(names.at(-1)).toBe('20260922000001_realtime_lobby_sync.sql');expect(names.filter(name=>name.includes('realtime_game_sync'))).toEqual(['20260922000000_realtime_game_sync.sql']);for(const name of names.slice(0,-2))expect(readFileSync(new URL(`../supabase/migrations/${name}`,import.meta.url),'utf8')).not.toContain('alter publication supabase_realtime');});
 it('creates only the four safe signal columns and constraints',()=>{const table=migration.slice(migration.indexOf('create table public.room_game_updates'),migration.indexOf('insert into public.room_game_updates'));for(const column of ['room_id uuid primary key','room_code text not null unique','state_version bigint not null','updated_at timestamptz not null'])expect(table).toContain(column);for(const forbidden of ['game_state','player_id','player_color','hiddenKind','seed','rngState','newVillagerBag','history','eventLog','actionQueue','pendingResolution','board'])expect(table).not.toContain(forbidden);expect(table).toContain("room_code ~ '^[A-Z0-9]{6,10}$'");expect(table).toContain('state_version >= 0');});
 it('backfills metadata only from existing room state rows',()=>{const backfill=migration.slice(migration.indexOf('insert into public.room_game_updates'),migration.indexOf('alter table public.room_game_updates'));expect(backfill).toContain('select rs.room_id, r.code, rs.state_version, rs.updated_at');expect(backfill).toContain('from public.room_states as rs');expect(backfill).not.toContain('game_state');});
 it('uses RLS membership reads and denies every browser write privilege',()=>{expect(migration).toContain('alter table public.room_game_updates enable row level security');expect(migration).toContain('revoke all on table public.room_game_updates from public');expect(migration).toContain('revoke all on table public.room_game_updates from anon');expect(migration).toContain('revoke all on table public.room_game_updates from authenticated');expect(migration).toContain('grant select on table public.room_game_updates to authenticated');expect(migration).toContain('to authenticated\nusing (ngsllc_private.is_room_member(room_id))');expect(migration).not.toMatch(/grant\s+(?:insert|update|delete|all)[\s\S]*?room_game_updates\s+to\s+(?:anon|authenticated)/i);});
 it('mirrors inserts and changed versions without inspecting or copying canonical state',()=>{const fn=migration.slice(migration.indexOf('create function ngsllc_private.sync_room_game_update'),migration.indexOf('create trigger room_states_sync_room_game_update'));expect(fn).toContain('security definer');expect(fn).toContain("set search_path = ''");expect(fn).toContain("tg_op = 'INSERT' or new.state_version is distinct from old.state_version");expect(fn).toContain('new.room_id, r.code, new.state_version, new.updated_at');expect(fn).not.toContain('game_state');for(const role of ['public','anon','authenticated','service_role'])expect(fn).toContain(`revoke all on function ngsllc_private.sync_room_game_update() from ${role}`);expect(migration).toContain('after insert or update of state_version on public.room_states');});
 it('publishes only the safe table with normal primary-key replication identity',()=>{expect(migration).toContain('alter publication supabase_realtime add table public.room_game_updates');expect(migration).not.toContain('add table public.room_states');expect(migration).not.toMatch(/replica identity full/i);});
});

describe('safe room update subscription',()=>{
 it('subscribes only to normalized room UPDATE signals after authentication',async()=>{const rt=realtimeClient(),signals:unknown[]=[],statuses:RoomGameSyncStatus[]=[];const pending=subscribeRoomGameUpdates({roomCode:' abc234 ',onSignal:value=>signals.push(value),onStatus:value=>statuses.push(value)},rt.client);const subscription=await pending;expect(rt.client.auth.getSession).toHaveBeenCalled();expect(rt.client.channel).toHaveBeenCalledWith('room-game-updates:ABC234');expect(rt.channel.on).toHaveBeenCalledWith('postgres_changes',{event:'UPDATE',schema:'public',table:'room_game_updates',filter:'room_code=eq.ABC234'},expect.any(Function));rt.status('SUBSCRIBED');await expect(subscription.ready).resolves.toBe('live');expect(statuses).toEqual(['connecting','live']);await subscription.unsubscribe();expect(rt.client.removeChannel).toHaveBeenCalledTimes(1);});
 it('accepts only matching nonnegative safe-integer version rows',async()=>{const rt=realtimeClient(),signals:unknown[]=[],subscription=await subscribeRoomGameUpdates({roomCode:'ABC234',onSignal:value=>signals.push(value),onStatus:()=>{}},rt.client);rt.status('SUBSCRIBED');rt.emit({room_code:'ABC234',state_version:4});for(const row of [{room_code:'XYZ789',state_version:5},{room_code:'ABC234',state_version:-1},{room_code:'ABC234',state_version:1.5},{room_code:'ABC234',state_version:'6'},{state_version:7}])rt.emit(row);expect(signals).toEqual([{roomCode:'ABC234',stateVersion:4}]);await subscription.unsubscribe();});
 it('reports connection failures without treating payloads as game state',async()=>{const rt=realtimeClient(),signals=vi.fn(),statuses:RoomGameSyncStatus[]=[],subscription=await subscribeRoomGameUpdates({roomCode:'ABC234',onSignal:signals,onStatus:value=>statuses.push(value)},rt.client);rt.status('CHANNEL_ERROR');await expect(subscription.ready).resolves.toBe('unavailable');expect(statuses).toEqual(['connecting','unavailable']);expect(subscriptionSource).not.toMatch(/gameView|game_state|hiddenKind|seed|rngState|newVillagerBag/);await subscription.unsubscribe();});
});

describe('version synchronization coordinator',()=>{
 it('establishes the subscription before any trusted fetch and keeps one subscription per room',async()=>{const h=syncHarness(vi.fn().mockResolvedValue(result(1)));await h.coordinator.enter('abc234');expect(h.subscribe).toHaveBeenCalledTimes(1);expect(h.fetchState).not.toHaveBeenCalled();await h.coordinator.enter('ABC234');expect(h.subscribe).toHaveBeenCalledTimes(1);await h.coordinator.refresh();expect(h.fetchState).toHaveBeenCalledWith({roomCode:'ABC234'});});
 it('turns a 0-to-1 start signal into a trusted active-state fetch',async()=>{const h=syncHarness(vi.fn().mockResolvedValue(result(1)));await h.coordinator.enter('ABC234');h.subscriptions[0].onSignal({roomCode:'ABC234',stateVersion:1});await vi.waitFor(()=>expect(h.states.at(-1)?.stateVersion).toBe(1));expect(h.fetchState).toHaveBeenCalledTimes(1);});
 it('refreshes for newer versions and ignores equal or older versions',async()=>{const h=syncHarness(vi.fn().mockResolvedValue(result(4)));await h.coordinator.enter('ABC234');h.coordinator.acceptTrusted(result(3));h.subscriptions[0].onSignal({roomCode:'ABC234',stateVersion:2});h.subscriptions[0].onSignal({roomCode:'ABC234',stateVersion:3});expect(h.fetchState).not.toHaveBeenCalled();h.subscriptions[0].onSignal({roomCode:'ABC234',stateVersion:4});await vi.waitFor(()=>expect(h.coordinator.latestTrustedVersion).toBe(4));expect(h.fetchState).toHaveBeenCalledTimes(1);});
 it('coalesces a 5/6/7 burst into one in-flight fetch plus one catch-up',async()=>{const first=deferred<ActiveGameStateResult|undefined>(),fetchState=vi.fn().mockImplementationOnce(()=>first.promise).mockResolvedValueOnce(result(7)),h=syncHarness(fetchState);await h.coordinator.enter('ABC234');for(const stateVersion of [5,6,7])h.subscriptions[0].onSignal({roomCode:'ABC234',stateVersion});expect(fetchState).toHaveBeenCalledTimes(1);first.resolve(result(5));await vi.waitFor(()=>expect(h.coordinator.latestTrustedVersion).toBe(7));expect(fetchState).toHaveBeenCalledTimes(2);});
 it('suppresses a redundant self-event after accepting the trusted action response',async()=>{const h=syncHarness(vi.fn().mockResolvedValue(result(6)));await h.coordinator.enter('ABC234');expect(h.coordinator.acceptTrusted(result(5))).toBe(true);h.subscriptions[0].onSignal({roomCode:'ABC234',stateVersion:5});expect(h.fetchState).not.toHaveBeenCalled();expect(h.states.map(state=>state.stateVersion)).toEqual([5]);});
 it('never regresses when Realtime arrives before the action response',async()=>{const pending=deferred<ActiveGameStateResult|undefined>(),h=syncHarness(vi.fn(()=>pending.promise));await h.coordinator.enter('ABC234');h.subscriptions[0].onSignal({roomCode:'ABC234',stateVersion:4});h.coordinator.acceptTrusted(result(4));pending.resolve(result(3));await pending.promise;await Promise.resolve();expect(h.coordinator.latestTrustedVersion).toBe(4);expect(h.states.map(state=>state.stateVersion)).toEqual([4]);});
 it('performs a trusted reconnect catch-up after the initial room fetch',async()=>{const h=syncHarness(vi.fn().mockResolvedValue(result(8)));await h.coordinator.enter('ABC234');h.coordinator.markInitialFetchComplete();h.subscriptions[0].onStatus('unavailable');h.subscriptions[0].onStatus('live');await vi.waitFor(()=>expect(h.coordinator.latestTrustedVersion).toBe(8));expect(h.fetchState).toHaveBeenCalledTimes(1);});
 it('defers an unavailable-to-live recovery catch-up until the initial room fetch completes',async()=>{const h=unavailableSyncHarness(vi.fn().mockResolvedValue(result(1)));await h.coordinator.enter('ABC234');h.subscriptions[0].onStatus('live');expect(h.fetchState).not.toHaveBeenCalled();h.coordinator.markInitialFetchComplete();await vi.waitFor(()=>expect(h.coordinator.latestTrustedVersion).toBe(1));expect(h.fetchState).toHaveBeenCalledTimes(1);expect(h.states.map(state=>state.stateVersion)).toEqual([1]);h.coordinator.markInitialFetchComplete();await Promise.resolve();expect(h.fetchState).toHaveBeenCalledTimes(1);});
 it('does not schedule a recovery fetch for a normal initial connecting-to-live subscription',async()=>{const h=syncHarness(vi.fn().mockResolvedValue(result(1)));await h.coordinator.enter('ABC234');h.coordinator.markInitialFetchComplete();await Promise.resolve();expect(h.fetchState).not.toHaveBeenCalled();expect(h.states).toHaveLength(0);});
 it('clears deferred recovery on leave',async()=>{const h=unavailableSyncHarness(vi.fn().mockResolvedValue(result(1)));await h.coordinator.enter('ABC234');h.subscriptions[0].onStatus('live');await h.coordinator.leave();h.coordinator.markInitialFetchComplete();await Promise.resolve();expect(h.fetchState).not.toHaveBeenCalled();expect(h.states).toHaveLength(0);});
 it('cannot carry an old-room deferred recovery into a new room',async()=>{const h=unavailableSyncHarness(vi.fn().mockResolvedValue(result(1)));await h.coordinator.enter('ABC234');const old=h.subscriptions[0];old.onStatus('live');await h.coordinator.enter('XYZ789');h.coordinator.markInitialFetchComplete();old.onStatus('live');await Promise.resolve();expect(h.fetchState).not.toHaveBeenCalled();expect(h.states).toHaveLength(0);expect(h.coordinator.isCurrent('XYZ789')).toBe(true);});
 it('keeps failures non-destructive and permits later manual refresh',async()=>{const fetchState=vi.fn().mockRejectedValueOnce(Error('offline')).mockResolvedValueOnce(result(2)),h=syncHarness(fetchState);await h.coordinator.enter('ABC234');await h.coordinator.refresh();expect(h.errors).toHaveLength(1);expect(h.states).toHaveLength(0);await h.coordinator.refresh();expect(h.states.at(-1)?.stateVersion).toBe(2);});
 it('unsubscribes on room changes and ignores delayed signals from the old room',async()=>{const h=syncHarness(vi.fn().mockResolvedValue(result(2,'XYZ789')));await h.coordinator.enter('ABC234');const old=h.subscriptions[0];await h.coordinator.enter('XYZ789');expect(h.removed[0]).toHaveBeenCalledTimes(1);old.onSignal({roomCode:'ABC234',stateVersion:9});expect(h.fetchState).not.toHaveBeenCalled();h.subscriptions[1].onSignal({roomCode:'XYZ789',stateVersion:2});await vi.waitFor(()=>expect(h.states.at(-1)?.roomCode).toBe('XYZ789'));});
 it('unsubscribes on route exit',async()=>{const h=syncHarness();await h.coordinator.enter('ABC234');await h.coordinator.leave();expect(h.removed[0]).toHaveBeenCalledTimes(1);expect(h.coordinator.isCurrent('ABC234')).toBe(false);});
});

describe('shell and browser trust boundary',()=>{
 it('starts room sync before the initial lobby fetch and protects stale room callbacks',()=>{const enter=shell.indexOf('roomSync.enter(route.code)'),lobby=shell.indexOf('return renderLobby(route.code)',enter);expect(enter).toBeGreaterThan(0);expect(enter).toBeLessThan(lobby);expect(shell).toContain('if(!roomSync.isCurrent(route.code)');expect(shell).toContain('if(!roomSync.isCurrent(code)');});
 it('automatically accepts trusted action responses and preserves manual Refresh Game',()=>{expect(shell).toContain('roomSync.acceptTrusted(next)');expect(shell).toContain('await roomSync.refresh()');expect(shell).toContain('REFRESH GAME');expect(shell).toContain('LIVE SYNC');expect(shell).toContain('LIVE SYNC UNAVAILABLE · USE REFRESH');});
 it('contains no polling and keeps actual state on the existing trusted Edge path',()=>{expect(`${subscriptionSource}\n${coordinatorSource}\n${shell}`).not.toContain('setInterval');expect(coordinatorSource).toContain('fetchState:getActiveGameState');expect(getClient).toContain("functions.invoke('get-game-state'");expect(subscriptionSource).toContain("table:'room_game_updates'");expect(subscriptionSource).not.toContain("table:'room_states'");});
 it('never adds browser canonical table/RPC access or renders Realtime payloads',()=>{const browser=`${subscriptionSource}\n${coordinatorSource}`;for(const forbidden of ["from('room_states')","rpc('get_active_game_state_server')","rpc('commit_game_action_server')",'game_state','hiddenKind','rngState','newVillagerBag','removedVillageTiles'])expect(browser).not.toContain(forbidden);expect(coordinatorSource).toContain('noteSignal');expect(coordinatorSource).toContain('dependencies.fetchState({roomCode})');});
});
