import {describe,expect,it} from 'vitest';import {applyAction,resolvePendingDecision} from '../src/games/worship-me/engine/reducer';import {countNeutralsInPlay} from '../src/games/worship-me/engine/neutrals';import {blessEdgeOptions} from '../src/games/worship-me/engine/resolution';import {game,player,reveal} from './helpers';
function finishPlacement(s:ReturnType<typeof game>){const round=s.round;while(s.phase==='placement'&&s.round===round)s=applyAction(s,{type:'endTurn',playerId:s.turnOrder[s.currentPlayerIndex]});return s}
describe('ordered resolution',()=>{
 it('Bless reveals a face-down tile only during resolution',()=>{let s=game(),p=player(s);s=applyAction(s,{type:'placeTile',cellId:'1,1',kind:'bless',playerId:p.id});expect(s.board.find(c=>c.id==='1,1')!.visibleKind).toBe('hidden');s=finishPlacement(s);expect(s.board.find(c=>c.id==='1,1')!.visibleKind).not.toBe('hidden')});
 it('empty revealed Smite hides the tile',()=>{let s=game(),p=player(s);reveal(s,'1,1');s=applyAction(s,{type:'placeTile',cellId:'1,1',kind:'smite',playerId:p.id});s=finishPlacement(s);expect(s.board.find(c=>c.id==='1,1')!.visibleKind).toBe('hidden')});
 it('Smite resource choice pauses at resolution and never ejects villagers',()=>{let s=game(),p=player(s),c=reveal(s,'1,1');c.wheat=1;c.bread=1;c.villagers.push(p.color);s=applyAction(s,{type:'placeTile',cellId:c.id,kind:'smite',playerId:p.id});s=finishPlacement(s);expect(s.pendingResolution?.type).toBe('smiteResource');s=resolvePendingDecision(s,{type:'resolveSmiteResource',playerId:p.id,resource:'bread'});expect(c.villagers).toHaveLength(1);expect(s.board.find(x=>x.id===c.id)!.bread).toBe(0)});
 it('Bless Edge keeps placed direction while choosing pawn at resolution',()=>{let s=game(),p=player(s),a=reveal(s,'1,1'),b=reveal(s,'1,2');a.villagers.push(p.color);s=applyAction(s,{type:'placeEdge',from:a.id,to:b.id,kind:'bless',playerId:p.id});expect(a.villagers).toHaveLength(1);s=finishPlacement(s);expect(s.pendingResolution?.type).toBe('blessEdgeMove');s=resolvePendingDecision(s,{type:'resolveBlessEdge',playerId:p.id,optionIndex:0});expect(s.board.find(c=>c.id===b.id)!.villagers).toContain(p.color)});
 it('offers opponent pawn movement only when own and Neutral candidates are absent',()=>{let s=game(),p=player(s),a=reveal(s,'1,1'),b=reveal(s,'1,2');a.villagers.push(player(s,1).color);s=applyAction(s,{type:'placeEdge',from:a.id,to:b.id,kind:'bless',playerId:p.id});s=finishPlacement(s);expect(s.pendingResolution?.type).toBe('blessEdgeMove');expect(s.pendingResolution?.type==='blessEdgeMove'&&s.pendingResolution.options.every(o=>o.opponent)).toBe(true)});
 it('offers Neutral movement only without own color and converts influence',()=>{let s=game(),p=player(s),a=reveal(s,'1,1'),b=reveal(s,'1,2');a.villagers.push('neutral');const total=countNeutralsInPlay(s);s=applyAction(s,{type:'placeEdge',from:a.id,to:b.id,kind:'bless',playerId:p.id});s=finishPlacement(s);expect(s.pendingResolution?.type).toBe('blessEdgeMove');s=resolvePendingDecision(s,{type:'resolveBlessEdge',playerId:p.id,optionIndex:0});expect(s.board.find(c=>c.id===b.id)!.villagers).toContain(p.color);expect(countNeutralsInPlay(s)).toBe(total+1);expect(s.history.events.find(e=>e.id==='R2-START')?.data.neutralAdded).toBe(1)});
 it('resolves blocked/no-choice Bless Edge as a no-op',()=>{let s=game(),p=player(s);reveal(s,'1,1');reveal(s,'1,2');s=applyAction(s,{type:'placeEdge',from:'1,1',to:'1,2',kind:'bless',playerId:p.id});s=finishPlacement(s);expect(s.eventLog.some(x=>x.includes('no-op'))).toBe(true)});
 it('moves Wheat resource-only while preserving own villagers at both endpoints',()=>{let s=game(),p=player(s),a=reveal(s,'1,1'),b=reveal(s,'1,2','bakery');a.villagers.push(p.color);b.villagers.push(p.color);a.wheat=1;s=applyAction(s,{type:'placeEdge',from:a.id,to:b.id,kind:'bless',playerId:p.id});s=finishPlacement(s);const pending=s.pendingResolution!;if(pending.type!=='blessEdgeMove')throw Error('expected move');const i=pending.options.findIndex(o=>o.resourceOnly&&o.resource==='wheat'&&o.from===a.id);s=resolvePendingDecision(s,{type:'resolveBlessEdge',playerId:p.id,optionIndex:i});expect(s.board.find(c=>c.id===a.id)!.villagers).toEqual([p.color]);expect(s.board.find(c=>c.id===b.id)!.villagers).toEqual([p.color]);expect(s.board.find(c=>c.id===b.id)!.wheat).toBe(1)});
 it('moves Bread resource-only into an exactly-two Home without changing occupancy',()=>{let s=game(),p=player(s),a=reveal(s,'1,1','bakery'),b=reveal(s,'1,2','home');a.villagers.push(p.color);b.villagers.push(p.color,p.color);a.bread=1;s=applyAction(s,{type:'placeEdge',from:a.id,to:b.id,kind:'bless',playerId:p.id});s=finishPlacement(s);const pending=s.pendingResolution!;if(pending.type!=='blessEdgeMove')throw Error('expected move');const i=pending.options.findIndex(o=>o.resourceOnly&&o.resource==='bread'&&o.from===a.id);s=resolvePendingDecision(s,{type:'resolveBlessEdge',playerId:p.id,optionIndex:i});expect(s.board.find(c=>c.id===b.id)!.villagers).toHaveLength(2);const event=s.history.events.find(e=>e.type==='resolutionDecision')!;expect(event.data.movementOutcome).toMatchObject({resource:'bread',noVillagerMoved:true,origin:a.id,destination:b.id})});
 it('enforces own then Neutral then opponent pawn priority',()=>{const s=game(),p=player(s),a=reveal(s,'1,1'),b=reveal(s,'1,2');a.villagers.push(p.color,'neutral',player(s,1).color);const action={type:'placeEdge' as const,from:a.id,to:b.id,kind:'bless' as const,playerId:p.id};const own=requireOptions(s,action);expect(own.every(o=>!o.neutral&&!o.opponent&&o.moverColor===p.color)).toBe(true);a.villagers.splice(a.villagers.indexOf(p.color),1);const neutral=requireOptions(s,action);expect(neutral.every(o=>o.neutral)).toBe(true);a.villagers.splice(a.villagers.indexOf('neutral'),1);const opponent=requireOptions(s,action);expect(opponent.every(o=>o.opponent)).toBe(true)});
 it('opponent conversion reaches Neutral 10 but never creates 11',()=>{for(const capped of [false,true]){let s=game(),p=player(s),opp=player(s,1),a=reveal(s,'1,1'),b=reveal(s,'1,2');a.villagers.push(opp.color);while(countNeutralsInPlay(s)<(capped?10:9))s.newVillagerBag.push('neutral');s=applyAction(s,{type:'placeEdge',from:a.id,to:b.id,kind:'bless',playerId:p.id});s=finishPlacement(s);const pending=s.pendingResolution!;if(pending.type!=='blessEdgeMove')throw Error('expected move');s=resolvePendingDecision(s,{type:'resolveBlessEdge',playerId:p.id,optionIndex:0});const dest=s.board.find(c=>c.id===b.id)!;expect(countNeutralsInPlay(s)).toBe(10);expect(dest.villagers).toContain(capped?opp.color:'neutral');if(capped)expect(s.newVillagerBag).not.toContain(opp.color);else expect(s.newVillagerBag).toContain(opp.color)}});
 it('uses only origin occupants for own-neutral-opponent priority',()=>{const s=game(),red=player(s),purple=player(s,1),origin=reveal(s,'1,1'),destination=reveal(s,'1,2');origin.villagers.push('neutral',purple.color);destination.villagers.push(red.color);let options=blessEdgeOptions(s,{type:'placeEdge',from:origin.id,to:destination.id,kind:'bless',playerId:red.id});expect(options.every(o=>o.neutral&&o.from===origin.id&&o.to===destination.id)).toBe(true);origin.villagers.splice(origin.villagers.indexOf('neutral'),1);options=blessEdgeOptions(s,{type:'placeEdge',from:origin.id,to:destination.id,kind:'bless',playerId:red.id});expect(options.every(o=>o.opponent&&o.moverColor===purple.color)).toBe(true)});
 it('never offers reverse movement or destination cargo',()=>{const s=game(),p=player(s),origin=reveal(s,'1,1'),destination=reveal(s,'1,2');origin.villagers.push(p.color);destination.villagers.push(p.color);destination.wheat=1;const options=blessEdgeOptions(s,{type:'placeEdge',from:origin.id,to:destination.id,kind:'bless',playerId:p.id});expect(options.every(o=>o.from===origin.id&&o.to===destination.id)).toBe(true);expect(options.some(o=>o.resource==='wheat')).toBe(false)});
 it('Adjacent Tile to Temple cannot resolve in the reverse direction',()=>{const s=game(),p=player(s),temple=s.board.find(c=>c.id===p.templeCellId)!,adjacent=s.board.find(c=>Math.abs(c.row-temple.row)+Math.abs(c.col-temple.col)===1)!;adjacent.visibleKind=adjacent.hiddenKind!;adjacent.villagers.push(p.color);const inward=blessEdgeOptions(s,{type:'placeEdge',from:adjacent.id,to:temple.id,kind:'bless',playerId:p.id}),outward=blessEdgeOptions(s,{type:'placeEdge',from:temple.id,to:adjacent.id,kind:'bless',playerId:p.id});expect(inward.some(o=>o.to===temple.id)).toBe(true);expect(inward.some(o=>o.from===temple.id)).toBe(false);expect(outward).toHaveLength(0)});
});
function requireOptions(s:ReturnType<typeof game>,a:{type:'placeEdge';from:string;to:string;kind:'bless';playerId:string}){return blessEdgeOptions(s,a)}
