import {readFileSync,readdirSync} from 'node:fs';
import {describe,expect,it,vi} from 'vitest';
import type {Lobby} from '../src/platform/rooms/lobby';
import {createActiveRoomLobbyLifecycle} from '../src/platform/rooms/activeRoomLobbyLifecycle';
import {createReturnToLobbyAction,returnToLobby} from '../src/platform/rooms/returnToLobby';

const migrationUrl=new URL('../supabase/migrations/',import.meta.url);
const migration=readFileSync(new URL('../supabase/migrations/20260924000001_return_finished_game_to_lobby.sql',import.meta.url),'utf8');
const signalReadFix=readFileSync(new URL('../supabase/migrations/20260924000002_fix_return_to_lobby_signal_read.sql',import.meta.url),'utf8');
const realtimeLobbyMigration=readFileSync(new URL('../supabase/migrations/20260922000001_realtime_lobby_sync.sql',import.meta.url),'utf8');
const edge=readFileSync(new URL('../supabase/functions/return-to-lobby/index.ts',import.meta.url),'utf8');
const shell=readFileSync(new URL('../src/platform/shell.ts',import.meta.url),'utf8');
const config=readFileSync(new URL('../supabase/config.toml',import.meta.url),'utf8');
const oldHashes:Record<string,string>={
 '20260919190346_create_ngsllc_core.sql':'dfa5c612e9edc4c58b685d3a80c4ebd826f0c0450df3d5ed0689005f01029840','20260919190347_restrict_rls_auto_enable.sql':'16f698e12a5b68c5aa1022d37311ff127fe8350f8ed965eee08c8cf4a5fd592b','20260919190348_create_room_server_command.sql':'ca25b2ddda8a351ad526a7884f0d8920fb137652f77a7235d4679fbb8941dd81','20260920000000_join_room_server_command.sql':'bb96b67025475877d89a335e278dc6ce9b8b733d3c9858fd49dbdbd5a17aef79','20260920000001_lobby_lifecycle.sql':'5ec1beccbe16f9a267806ddd155d08a349286a4d6625a0de3ac6eb94d592af96','20260920000002_player_color_selection.sql':'0887a28b155576694e22f339e82fd1951c7ce9978da439661a217bbdeffc2230','20260920000003_player_ready_state.sql':'73ac0263ec0f0af59da1394bdc00b687a47ac7f8c7e7587577813c5718de9f47','20260920000004_start_game.sql':'5bc2bd51cdb12166ad1285740a60760974925593d0b5b0e40be2140ce2230706','20260921000000_active_game_state_read.sql':'3956a00b749e0475e56b910e88671580ff4934b484498e05e875fcdf358359cb','20260921000001_gameplay_mutation.sql':'a80840b9a2cade11645b7360c31ec401e900cc06413f5335e62c67a642dffaab','20260922000000_realtime_game_sync.sql':'53d6e92e41b06371bab2be49dc8e05cf0f609e2d49addc258e135b6dae8696b6','20260922000001_realtime_lobby_sync.sql':'783559b6fcfd841a5dbda98bf21a27bccce2899a9687c644a914955114bbc27a','20260922000002_multiplayer_ai_players.sql':'68481194f0c79ea8b5729db7088e9fd4bacce03bf5ac76c902af0c69c1b418ff','20260923000000_fix_multiplayer_ai_sql_ambiguity.sql':'3d684ce2b4285b1cce4747f27679d5693071a47fbef091d837c373cd83e5ba6d','20260923000001_fix_start_game_coalesce.sql':'5139fda069f56017e9fcbccd8ce73a29dd05804494c6c9a01829ef816ffe8afb','20260923000002_active_player_ai_takeover.sql':'1fca1fc0096a6cd37c53e5e7462569b34709b0094e636218e2575fe889e13905','20260924000000_lobby_discovery_and_host_moderation.sql':'42b08a785f5c289639211df0c03344909f005f76b8e1848c65e5c99ad5efe568','20260924000001_return_finished_game_to_lobby.sql':'af563be022bac9166854cf75a03841cdaf0159f14ceecb6f722661720a5a8a9a'};
const lobby=(code:string,status:'active'|'lobby',host=true):Lobby=>({room:{id:`room-${code}`,code,status,gameId:'game-1',maxPlayers:8,joinMode:'public',isCurrentUserHost:host},players:[{control:'human',participantId:'user-1',userId:'user-1',displayName:'Alice',playerColor:'red',turnOrder:status==='active'?0:null,isReady:status==='active',isHost:host,isCurrentUser:true}]});

describe('return-to-lobby migration #18 STATIC CONTRACT (not PostgreSQL execution)',()=>{
 it('adds only migration 19 and pins migrations 1-18 unchanged',async()=>{const names=readdirSync(migrationUrl,{withFileTypes:true}).filter(entry=>!entry.isDirectory()&&entry.name.endsWith('.sql')).map(entry=>entry.name).sort();expect(names).toHaveLength(19);expect(names.at(-2)).toBe('20260924000001_return_finished_game_to_lobby.sql');expect(names.at(-1)).toBe('20260924000002_fix_return_to_lobby_signal_read.sql');for(const[name,hash]of Object.entries(oldHashes)){const bytes=new TextEncoder().encode(readFileSync(new URL(`../supabase/migrations/${name}`,import.meta.url),'utf8')),digest=await crypto.subtle.digest('SHA-256',bytes),actual=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,'0')).join('');expect(actual).toBe(hash);}});
 it('grants service_role only SELECT on the lobby signal table',()=>{expect(signalReadFix).toMatch(/^--[^\n]*\n--[^\n]*\ngrant select\non table public\.room_lobby_updates\nto service_role;\s*$/i);expect(signalReadFix).not.toMatch(/\b(?:insert|update|delete|truncate|references|trigger)\b/i);expect(signalReadFix.match(/\bgrant\b/gi)).toHaveLength(1);});
 it('preserves authenticated SELECT with membership RLS while anon retains no privileges',()=>{expect(realtimeLobbyMigration).toContain('revoke all on table public.room_lobby_updates from anon');expect(realtimeLobbyMigration).toContain('revoke all on table public.room_lobby_updates from authenticated');expect(realtimeLobbyMigration).toContain('grant select on table public.room_lobby_updates to authenticated');expect(realtimeLobbyMigration).toContain('to authenticated\nusing (ngsllc_private.is_room_member(room_id))');expect(signalReadFix).not.toMatch(/\b(?:anon|authenticated)\b/i);});
 it('keeps the Realtime publication limited to the three established signal tables',()=>{const published=readdirSync(migrationUrl,{withFileTypes:true}).filter(entry=>!entry.isDirectory()&&entry.name.endsWith('.sql')).flatMap(entry=>[...readFileSync(new URL(`../supabase/migrations/${entry.name}`,import.meta.url),'utf8').matchAll(/alter publication supabase_realtime add table public\.([a-z_]+)/gi)].map(match=>match[1])).sort();expect(published).toEqual(['room_game_updates','room_kicks','room_lobby_updates']);expect(signalReadFix).not.toMatch(/\bpublication\b/i);});
 it('locks the room, authorizes the current human host, and validates a canonical completed state',()=>{expect(migration).toContain('for update of r');expect(migration).toContain('member.user_id = p_user_id');expect(migration).toContain('v_host_user_id is distinct from p_user_id');expect(migration).toContain("v_room_status is distinct from 'active'");expect(migration).toContain("v_game_state->'schemaVersion' is distinct from '9'::jsonb");expect(migration).toContain("v_game_state->>'phase' is distinct from 'gameOver'");expect(migration).toContain("player.value->>'id' = v_game_state->>'winnerId'");expect(migration).toContain('for update of state');});
 it('atomically resets only rematch state while preserving room and participant identity',()=>{expect(migration).toContain('update public.room_players as member');expect(migration).toContain('set turn_order = null,\n      is_ready = false');expect(migration).toContain('update public.room_ai_players as ai\n  set turn_order = null');expect(migration).toContain('set game_state = null,\n      state_version = 0');expect(migration).toContain("set status = 'lobby'");for(const forbidden of ['delete from public.room_players','delete from public.room_ai_players','insert into public.room_players','insert into public.room_ai_players','delete from public.room_kicks','update public.room_kicks','set join_mode','set player_color','set display_name','set bot_strategy','set bot_number'])expect(migration).not.toContain(forbidden);});
 it('is service-only SECURITY INVOKER with an empty search path',()=>{expect(migration).toContain('security invoker');expect(migration).toContain("set search_path = ''");expect(migration).toContain('revoke execute on function public.return_finished_game_to_lobby_server(text,uuid)\nfrom public, anon, authenticated, service_role');expect(migration).toContain('grant execute on function public.return_finished_game_to_lobby_server(text,uuid)\nto service_role');});
 it('serializes duplicate Return, Leave, host transfer, stale actions, and stale AI through existing locked status checks',()=>{const leave=readFileSync(new URL('../supabase/migrations/20260923000002_active_player_ai_takeover.sql',import.meta.url),'utf8'),actions=readFileSync(new URL('../supabase/migrations/20260921000001_gameplay_mutation.sql',import.meta.url),'utf8'),ai=readFileSync(new URL('../supabase/migrations/20260922000002_multiplayer_ai_players.sql',import.meta.url),'utf8');expect(migration).toContain('for update of r');expect(leave).toContain('for update of r');expect(actions).toMatch(/commit_game_action_server[\s\S]*for update of r/);expect(ai).toMatch(/commit_ai_action_server[\s\S]*for update of r/);expect(migration).toContain("room.status = 'active'");});
 it('passes SQL-special-form and output-collision review',()=>{for(const invalid of ['pg_catalog.coalesce','pg_catalog.nullif','pg_catalog.greatest','pg_catalog.least'])expect(migration.toLowerCase()).not.toContain(invalid);expect(migration).not.toMatch(/pg_catalog\.substring\([^)]*\sfrom\s/i);for(const alias of ['public.rooms as r','public.room_players as member','public.room_states as state','public.room_ai_players as ai','public.rooms as room','public.room_lobby_updates as signal'])expect(migration).toContain(alias);expect(migration).toMatch(/end;\r?\n\$\$;/);});
});

describe('return-to-lobby Edge and browser client',()=>{
 it('uses verified JWT identity, an exact roomCode-only payload, and safe error mappings',()=>{expect(config).toContain('[functions.return-to-lobby]\nverify_jwt = true');expect(edge).toContain('auth.getUser(token)');expect(edge).toContain("exact(body,['roomCode'])");expect(edge).toContain('p_user_id:user.id');expect(edge).toContain("error.code==='P0003'");expect(edge).toContain("error.code==='P0004'");for(const forbidden of ['gameState','winnerId','stateVersion','hostUserId','targetStatus'])expect(edge).not.toContain(forbidden);});
 it('sends only normalized roomCode and validates the narrow result',async()=>{const invoke=vi.fn(async()=>({data:{roomCode:'ABC234',status:'lobby',lobbyVersion:9},error:null})),client={auth:{getSession:vi.fn(async()=>({data:{session:{user:{id:'user-1'}}},error:null}))},functions:{invoke}};await expect(returnToLobby({roomCode:' abc234 '},client as never)).resolves.toEqual({roomCode:'ABC234',status:'lobby',lobbyVersion:9});expect(invoke).toHaveBeenCalledWith('return-to-lobby',{body:{roomCode:'ABC234'}});});
 it('prevents duplicate submissions',async()=>{let resolve!:(value:{roomCode:string;status:'lobby';lobbyVersion:number})=>void;const command=vi.fn(()=>new Promise<{roomCode:string;status:'lobby';lobbyVersion:number}>(yes=>{resolve=yes;})),action=createReturnToLobbyAction(command),first=action({roomCode:'ABC234'}),second=action({roomCode:'ABC234'});expect(command).toHaveBeenCalledOnce();await expect(second).resolves.toBeUndefined();resolve({roomCode:'ABC234',status:'lobby',lobbyVersion:1});await first;});
});

describe('active room M10 lifecycle',()=>{
 it('keeps active metadata without transitioning and performs one trusted lobby transition',async()=>{const activeMetadata=vi.fn(),returned=vi.fn().mockResolvedValue(undefined),lifecycle=createActiveRoomLobbyLifecycle({onActiveMetadata:activeMetadata,onReturnedLobby:returned});lifecycle.enter('abc234');lifecycle.accept(lobby('ABC234','active',false));expect(activeMetadata).toHaveBeenCalledOnce();expect(returned).not.toHaveBeenCalled();lifecycle.accept(lobby('ABC234','lobby',false));lifecycle.accept(lobby('ABC234','lobby',false));expect(returned).toHaveBeenCalledOnce();});
 it('ignores old-room snapshots and clears pending authority on leave/new room',()=>{const activeMetadata=vi.fn(),returned=vi.fn(),lifecycle=createActiveRoomLobbyLifecycle({onActiveMetadata:activeMetadata,onReturnedLobby:returned});lifecycle.enter('ABC234');lifecycle.leave();lifecycle.accept(lobby('ABC234','lobby'));lifecycle.enter('XYZ789');lifecycle.accept(lobby('ABC234','active'));expect(activeMetadata).not.toHaveBeenCalled();expect(returned).not.toHaveBeenCalled();expect(lifecycle.isCurrent('XYZ789')).toBe(true);});
 it('keeps M10 active, resets M9 before lobby render, and restores ordinary lobby cleanup',()=>{expect(shell).toContain('onState:result=>renderActiveGameState');expect(shell).not.toContain('void roomLobbySync.leave();renderActiveGameState');expect(shell).toContain('activeRoomLifecycle.accept(lobby)');const transition=shell.slice(shell.indexOf('onReturnedLobby:async lobby=>'),shell.indexOf('const roomKickSync'));expect(transition.indexOf('await roomSync.leave()')).toBeLessThan(transition.indexOf('renderLobbyState(lobby'));expect(transition).toContain('gamePresence.leave()');expect(transition).toContain('aiAdvanceToken++');expect(transition).toContain('roomSync.markInitialFetchComplete()');expect(shell).toContain('void roomKickSync.enter(lobby.room.id)');});
 it('renders host and non-host game-over UX without exposing authority identifiers',()=>{expect(shell).toContain('data-return-to-lobby');expect(shell).toContain('RETURN TO LOBBY');expect(shell).toContain('RETURNING TO LOBBY…');expect(shell).toContain('Waiting for the host to return the room to the lobby.');expect(shell).toContain('returnLobby({roomCode:code})');expect(shell).toContain("result.gameView.phase!=='gameOver'");expect(shell).not.toContain('activeLobbySnapshot.room.hostUserId');});
});
