import {readFileSync,readdirSync} from 'node:fs';
import {describe,expect,it,vi} from 'vitest';
import type {SupabaseClient} from '@supabase/supabase-js';
import type {RoomChatMessage,RoomChatSyncStatus} from '../src/platform/types';
import {sendRoomChatMessage,RoomChatSendError} from '../src/platform/rooms/sendRoomChatMessage';
import {getRoomChatMessages,ROOM_CHAT_HISTORY_LIMIT} from '../src/platform/rooms/getRoomChatMessages';
import {createRoomChatSyncCoordinator,ROOM_CHAT_MEMORY_LIMIT} from '../src/platform/rooms/roomChatSync';
import {isRoomChatMessage} from '../src/platform/rooms/roomChatMessage';
import {subscribeRoomChatMessages,type RoomChatSubscription,type SubscribeRoomChatMessagesOptions} from '../src/platform/rooms/subscribeRoomChatMessages';
import {escapeHtml} from '../src/platform/shell';

const migrations=new URL('../supabase/migrations/',import.meta.url),migration=readFileSync(new URL('../supabase/migrations/20260924000005_room_chat.sql',import.meta.url),'utf8'),activeTakeoverMigration=readFileSync(new URL('../supabase/migrations/20260923000002_active_player_ai_takeover.sql',import.meta.url),'utf8'),moderationMigration=readFileSync(new URL('../supabase/migrations/20260924000000_lobby_discovery_and_host_moderation.sql',import.meta.url),'utf8'),presenceMigration=readFileSync(new URL('../supabase/migrations/20260924000003_lobby_presence_and_stale_directory.sql',import.meta.url),'utf8'),edge=readFileSync(new URL('../supabase/functions/send-chat-message/index.ts',import.meta.url),'utf8'),subscriptionSource=readFileSync(new URL('../src/platform/rooms/subscribeRoomChatMessages.ts',import.meta.url),'utf8'),historySource=readFileSync(new URL('../src/platform/rooms/getRoomChatMessages.ts',import.meta.url),'utf8'),shell=readFileSync(new URL('../src/platform/shell.ts',import.meta.url),'utf8'),config=readFileSync(new URL('../supabase/config.toml',import.meta.url),'utf8');
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const message=(n:number,roomId=id(99),text=`Message ${n}`):RoomChatMessage=>({id:id(n),roomId,senderDisplayName:'Alice',messageText:text,createdAt:`2026-09-24T00:00:${String(n).padStart(2,'0')}.000Z`});
const authenticated=(invoke:ReturnType<typeof vi.fn>)=>({auth:{getSession:vi.fn(async()=>({data:{session:{user:{id:id(1)}}},error:null}))},functions:{invoke}}) as unknown as SupabaseClient;
const functionBody=(source:string,signature:string)=>{const start=source.indexOf(signature),end=source.indexOf('\n$$;',start);expect(start).toBeGreaterThanOrEqual(0);expect(end).toBeGreaterThan(start);return source.slice(start,end);};

describe('room chat migration #22 STATIC CONTRACT (not PostgreSQL execution)',()=>{
 it('adds only migration 22 and pins migration 21 unchanged',async()=>{const names=readdirSync(migrations,{withFileTypes:true}).filter(entry=>!entry.isDirectory()&&entry.name.endsWith('.sql')).map(entry=>entry.name).sort();expect(names).toHaveLength(22);expect(names.at(-2)).toBe('20260924000004_room_naming.sql');expect(names.at(-1)).toBe('20260924000005_room_chat.sql');const bytes=new TextEncoder().encode(readFileSync(new URL('../supabase/migrations/20260924000004_room_naming.sql',import.meta.url),'utf8')),digest=await crypto.subtle.digest('SHA-256',bytes),hash=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,'0')).join('');expect(hash).toBe('5a1b88e0674afc7beebd966aff324c6d83294c685b414237c84f4ebde728e0fd');});
 it('creates an intrinsically safe persistent message table, constraints, and deterministic history index',()=>{for(const token of ['create table public.room_chat_messages','id uuid primary key default pg_catalog.gen_random_uuid()','room_id uuid not null references public.rooms(id) on delete cascade','sender_display_name text not null','message_text text not null','created_at timestamptz not null default pg_catalog.now()','sender_display_name = pg_catalog.btrim(sender_display_name)','pg_catalog.char_length(sender_display_name) between 1 and 50','message_text = pg_catalog.btrim(message_text)','pg_catalog.char_length(message_text) between 1 and 500',"message_text !~ '[[:cntrl:]]'",'on public.room_chat_messages (room_id, created_at desc, id desc)'])expect(migration).toContain(token);for(const forbidden of ['sender_user_id','host_user_id','last_seen_at','game_state','unique (message_text','unique (sender_display_name'])expect(migration).not.toContain(forbidden);});
 it('keeps sender snapshots compatible with the authoritative room-player name domain',()=>{const senderConstraint=migration.match(/constraint room_chat_messages_sender_name_valid check \(([\s\S]*?)\n  \),/)?.[1]??'';expect(senderConstraint).toContain('sender_display_name = pg_catalog.btrim(sender_display_name)');expect(senderConstraint).toContain('pg_catalog.char_length(sender_display_name) between 1 and 50');expect(senderConstraint).not.toContain("!~ '[[:cntrl:]]'");const messageConstraint=migration.match(/constraint room_chat_messages_text_valid check \(([\s\S]*?)\n  \)/)?.[1]??'';expect(messageConstraint).toContain("message_text !~ '[[:cntrl:]]'");});
 it('enables membership RLS with authenticated SELECT only and minimum service grants',()=>{expect(migration).toContain('alter table public.room_chat_messages enable row level security');expect(migration).toContain('to authenticated\nusing (ngsllc_private.is_room_member(room_id))');expect(migration).toContain('grant select on table public.room_chat_messages to authenticated');expect(migration).toContain('grant select, insert on table public.room_chat_messages to service_role');expect(migration).not.toMatch(/grant\s+(?:insert|update|delete)[^;]*authenticated/i);});
 it('keeps per-user rate state private and atomically enforces one second',()=>{for(const token of ['create table ngsllc_private.room_chat_rate_limits','primary key (room_id, user_id)','pg_catalog.clock_timestamp()','on conflict on constraint room_chat_rate_limits_pkey do update',"rate_limit.last_sent_at <= excluded.last_sent_at - interval '1 second'","errcode = 'P0008'"])expect(migration).toContain(token);expect(migration).toContain('grant select, insert, update on table ngsllc_private.room_chat_rate_limits to service_role');expect(migration).not.toMatch(/grant[^;]+room_chat_rate_limits[^;]+authenticated/i);});
 it('locks current human membership and derives sender identity while allowing lobby and active only',()=>{for(const token of ['member.user_id = p_user_id','member.display_name','for key share of member',"v_room_status not in ('lobby', 'active')",'v_sender_display_name','insert into public.room_chat_messages'])expect(migration).toContain(token);expect(migration).not.toContain('p_sender');});
 it('uses the deadlock-safe room -> membership -> rate -> message order',()=>{const body=functionBody(migration,'create function public.send_room_chat_message_server');const roomLock=body.indexOf('for key share of r;'),membershipLock=body.indexOf('for key share of member;'),rateMutation=body.indexOf('insert into ngsllc_private.room_chat_rate_limits'),messageInsert=body.indexOf('insert into public.room_chat_messages as inserted_message');expect(roomLock).toBeGreaterThanOrEqual(0);expect(membershipLock).toBeGreaterThan(roomLock);expect(rateMutation).toBeGreaterThan(membershipLock);expect(messageInsert).toBeGreaterThan(rateMutation);expect(body.slice(0,roomLock)).not.toContain('for key share of member');expect(body).not.toContain('for update of r');expect(body).not.toContain('pg_advisory_xact_lock');});
 it('matches lifecycle room-first ordering without cross-room locks (STATIC CONTRACT)',()=>{const send=functionBody(migration,'create function public.send_room_chat_message_server'),leave=functionBody(activeTakeoverMigration,'create or replace function public.leave_room_server'),kick=functionBody(moderationMigration,'create function public.kick_room_player_server'),presence=functionBody(presenceMigration,'create function public.touch_lobby_presence_server');expect(send.indexOf('for key share of r;')).toBeLessThan(send.indexOf('for key share of member;'));expect(leave.indexOf('for update of r;')).toBeLessThan(leave.indexOf('ngsllc_private.takeover_active_player_with_ai'));expect(kick.indexOf('for update of r;')).toBeLessThan(kick.indexOf('delete from public.room_players as target'));expect(presence.indexOf('for update of r;')).toBeLessThan(presence.indexOf('update public.room_players as caller'));expect(send).not.toMatch(/order by r\.id|pg_advisory_xact_lock|unnest\(/);});
 it('is service-only SECURITY INVOKER and does not couple chat to M9/M10/GameState',()=>{expect(migration).toContain('security invoker');expect(migration).toContain("set search_path = ''");expect(migration).toContain('revoke execute on function public.send_room_chat_message_server(text,uuid,text)\nfrom public, anon, authenticated, service_role');expect(migration).toContain('grant execute on function public.send_room_chat_message_server(text,uuid,text)\nto service_role');for(const forbidden of ['room_game_updates','room_lobby_updates','room_states','state_version','update public.rooms','update public.room_players'])expect(migration).not.toContain(forbidden);});
 it('qualifies inserted-message RETURNING fields and avoids output-variable conflict inference',()=>{expect(migration).toContain('insert into public.room_chat_messages as inserted_message');expect(migration).toContain('returning inserted_message.id, inserted_message.created_at');expect(migration).not.toContain('on conflict (room_id, user_id)');});
 it('publishes exactly four safe tables and never the private rate table',()=>{const published=readdirSync(migrations,{withFileTypes:true}).filter(entry=>!entry.isDirectory()&&entry.name.endsWith('.sql')).flatMap(entry=>[...readFileSync(new URL(`../supabase/migrations/${entry.name}`,import.meta.url),'utf8').matchAll(/alter publication supabase_realtime add table public\.([a-z_]+)/g)].map(match=>match[1])).sort();expect(published).toEqual(['room_chat_messages','room_game_updates','room_kicks','room_lobby_updates']);expect(published).not.toContain('room_chat_rate_limits');});
});

describe('chat send and history trust boundary',()=>{
 it('sends only canonical roomCode/messageText and accepts a safe trusted DTO',async()=>{const accepted=message(1),invoke=vi.fn(async()=>({data:accepted,error:null}));await expect(sendRoomChatMessage({roomCode:' abc234 ',messageText:'  Good move!  '},authenticated(invoke))).resolves.toEqual(accepted);expect(invoke).toHaveBeenCalledWith('send-chat-message',{body:{roomCode:'ABC234',messageText:'Good move!'}});});
 it('accepts the authoritative sender-name domain but keeps message text strict',async()=>{const accepted={...message(1),senderDisplayName:'Ali\tce'},invoke=vi.fn(async()=>({data:accepted,error:null}));await expect(sendRoomChatMessage({roomCode:'ABC234',messageText:'Hello'},authenticated(invoke))).resolves.toEqual(accepted);expect(isRoomChatMessage(accepted)).toBe(true);for(const senderDisplayName of ['', ' Alice ', 'x'.repeat(51), 42])expect(isRoomChatMessage({...message(1),senderDisplayName})).toBe(false);expect(isRoomChatMessage({...accepted,messageText:'bad\ttext'})).toBe(false);});
 it('accepts Unicode and inert HTML-looking text but rejects blank, controls, and overlong text',async()=>{const invoke=vi.fn(async(_name:string,{body}:{body:{messageText:string}})=>({data:message(1,id(99),body.messageText),error:null})),client=authenticated(invoke);for(const text of ['Hello!','🔥','Gods & "Kings"',"Alice's Room",'<script>alert(1)</script>'])await expect(sendRoomChatMessage({roomCode:'ABC234',messageText:text},client)).resolves.toMatchObject({messageText:text});for(const text of ['','   ','x'.repeat(501),'bad\ntext','bad\ttext','bad\rtext',`bad${String.fromCharCode(127)}text`])await expect(sendRoomChatMessage({roomCode:'ABC234',messageText:text},client)).rejects.toBeInstanceOf(RoomChatSendError);});
 it('maps rate limit to safe UX and derives user/name/time server-side',()=>{expect(config).toContain('[functions.send-chat-message]\nverify_jwt = true');expect(edge).toContain("exact(body,['roomCode','messageText'])");expect(edge).toContain('p_user_id:user.id');expect(edge).toContain("error.code==='P0008'");expect(edge).toContain('429');for(const forbidden of ['senderDisplayName:body','p_sender','p_created_at','senderUserId'])expect(edge).not.toContain(forbidden);});
 it('maps an Edge 429 to the safe rate-limit message',async()=>{const error={context:{status:429},message:'internal'};await expect(sendRoomChatMessage({roomCode:'ABC234',messageText:'Again'},authenticated(vi.fn(async()=>({data:null,error}))))).rejects.toEqual(new RoomChatSendError("You're sending messages too quickly."));});
 it('reads explicit latest-100 room history and reverses it into deterministic chronology',async()=>{const calls:string[]=[];const rows=[message(2),message(1)].map(value=>({id:value.id,room_id:value.roomId,sender_display_name:value.senderDisplayName,message_text:value.messageText,created_at:value.createdAt}));const chain={select:(fields:string)=>{calls.push(`select:${fields}`);return chain;},eq:(field:string,value:string)=>{calls.push(`eq:${field}:${value}`);return chain;},order:(field:string,options:unknown)=>{calls.push(`order:${field}:${JSON.stringify(options)}`);return chain;},limit:async(value:number)=>{calls.push(`limit:${value}`);return{data:rows,error:null};}};const client={auth:{getSession:vi.fn(async()=>({data:{session:{user:{id:id(1)}}},error:null}))},from:(table:string)=>{calls.push(`from:${table}`);return chain;}} as unknown as SupabaseClient;await expect(getRoomChatMessages(id(99),client)).resolves.toEqual([message(1),message(2)]);expect(ROOM_CHAT_HISTORY_LIMIT).toBe(100);expect(calls).toEqual(['from:room_chat_messages','select:id,room_id,sender_display_name,message_text,created_at',`eq:room_id:${id(99)}`,'order:created_at:{"ascending":false}','order:id:{"ascending":false}','limit:100']);expect(historySource).not.toContain('select(\'*\')');});
 it('accepts an authoritative sender snapshot containing an internal control character in history',async()=>{const trusted={...message(1),senderDisplayName:'Ali\tce'},row={id:trusted.id,room_id:trusted.roomId,sender_display_name:trusted.senderDisplayName,message_text:trusted.messageText,created_at:trusted.createdAt},chain={select:()=>chain,eq:()=>chain,order:()=>chain,limit:async()=>({data:[row],error:null})},client={auth:{getSession:vi.fn(async()=>({data:{session:{user:{id:id(1)}}},error:null}))},from:()=>chain} as unknown as SupabaseClient;await expect(getRoomChatMessages(id(99),client)).resolves.toEqual([trusted]);});
 it('fails the history read closed when any returned DTO is malformed',async()=>{const chain={select:()=>chain,eq:()=>chain,order:()=>chain,limit:async()=>({data:[{id:id(1),room_id:id(99),sender_display_name:'Alice',message_text:'bad\ntext',created_at:new Date().toISOString()}],error:null})};const client={auth:{getSession:vi.fn(async()=>({data:{session:{user:{id:id(1)}}},error:null}))},from:()=>chain} as unknown as SupabaseClient;await expect(getRoomChatMessages(id(99),client)).rejects.toThrow('Unable to load chat history.');});
});

describe('chat Realtime subscription boundary',()=>{
 it('subscribes to current-room INSERT only, ignores invalid/other-room rows, reports status, and unsubscribes',async()=>{let handler!:(payload:{new:unknown})=>void,status!:(value:string)=>void;const channel={on:vi.fn((_type:string,_filter:unknown,next:typeof handler)=>{handler=next;return channel;}),subscribe:vi.fn((next:typeof status)=>{status=next;return channel;})},removeChannel=vi.fn(async()=>{}),client={auth:{getSession:vi.fn(async()=>({data:{session:{user:{id:id(1)}}},error:null}))},channel:vi.fn(()=>channel),removeChannel} as unknown as SupabaseClient,onMessage=vi.fn(),onStatus=vi.fn();const subscription=await subscribeRoomChatMessages({roomId:id(99),onMessage,onStatus,connectionTimeoutMs:1000},client);expect(channel.on).toHaveBeenCalledWith('postgres_changes',{event:'INSERT',schema:'public',table:'room_chat_messages',filter:`room_id=eq.${id(99)}`},expect.any(Function));handler({new:{id:id(1),room_id:id(99),sender_display_name:'Alice',message_text:'Hello',created_at:'2026-09-24T00:00:01.000Z'}});handler({new:{id:id(2),room_id:id(98),sender_display_name:'Mallory',message_text:'Other room',created_at:'2026-09-24T00:00:02.000Z'}});handler({new:{id:'bad'}});expect(onMessage).toHaveBeenCalledTimes(1);status('SUBSCRIBED');await expect(subscription.ready).resolves.toBe('live');expect(onStatus).toHaveBeenNthCalledWith(1,'connecting');expect(onStatus).toHaveBeenLastCalledWith('live');await subscription.unsubscribe();expect(removeChannel).toHaveBeenCalledWith(channel);});
 it('reports readiness timeout as unavailable and performs one late-live recovery fetch',async()=>{vi.useFakeTimers();try{let status!:(value:string)=>void;const channel={on:vi.fn(()=>channel),subscribe:vi.fn((next:typeof status)=>{status=next;return channel;})},client={auth:{getSession:vi.fn(async()=>({data:{session:{user:{id:id(1)}}},error:null}))},channel:vi.fn(()=>channel),removeChannel:vi.fn(async()=>{})} as unknown as SupabaseClient,initial=message(1),missed=message(2),statuses:RoomChatSyncStatus[]=[],fetchHistory=vi.fn().mockResolvedValueOnce([initial]).mockResolvedValueOnce([initial,missed]),coordinator=createRoomChatSyncCoordinator({onMessages:vi.fn(),onStatus:value=>statuses.push(value),onError:vi.fn()},{fetchHistory,subscribe:options=>subscribeRoomChatMessages({...options,connectionTimeoutMs:25},client)}),entering=coordinator.enter(id(99),'ABC234');await vi.advanceTimersByTimeAsync(25);await entering;expect(statuses).toContain('unavailable');expect(statuses.at(-1)).toBe('unavailable');expect(fetchHistory).toHaveBeenCalledOnce();expect(coordinator.messages).toEqual([initial]);status('SUBSCRIBED');await vi.advanceTimersByTimeAsync(0);expect(statuses.at(-1)).toBe('live');expect(fetchHistory).toHaveBeenCalledTimes(2);expect(coordinator.messages).toEqual([initial,missed]);status('SUBSCRIBED');await vi.advanceTimersByTimeAsync(0);expect(fetchHistory).toHaveBeenCalledTimes(2);expect(subscriptionSource).not.toMatch(/setInterval/);await coordinator.leave();}finally{vi.useRealTimers();}});
 it('accepts an authoritative sender snapshot containing an internal control character from Realtime',async()=>{let handler!:(payload:{new:unknown})=>void;const channel={on:vi.fn((_type:string,_filter:unknown,next:typeof handler)=>{handler=next;return channel;}),subscribe:vi.fn(()=>channel)},client={auth:{getSession:vi.fn(async()=>({data:{session:{user:{id:id(1)}}},error:null}))},channel:vi.fn(()=>channel),removeChannel:vi.fn(async()=>{})} as unknown as SupabaseClient,onMessage=vi.fn();const subscription=await subscribeRoomChatMessages({roomId:id(99),onMessage,onStatus:vi.fn(),connectionTimeoutMs:1000},client);handler({new:{id:id(1),room_id:id(99),sender_display_name:'Ali\tce',message_text:'Hello',created_at:'2026-09-24T00:00:01.000Z'}});expect(onMessage).toHaveBeenCalledWith({...message(1),senderDisplayName:'Ali\tce',messageText:'Hello'});await subscription.unsubscribe();});
});

describe('chat Realtime coordinator behavior',()=>{
 const harness=(history:RoomChatMessage[]=[])=>{const subscriptions:SubscribeRoomChatMessagesOptions[]=[],statuses:RoomChatSyncStatus[]=[],snapshots:RoomChatMessage[][]=[],fetchHistory=vi.fn(async()=>history),subscribe=vi.fn(async(options:SubscribeRoomChatMessagesOptions)=>{subscriptions.push(options);options.onStatus('live');return{roomId:options.roomId,ready:Promise.resolve('live' as const),unsubscribe:vi.fn(async()=>{})} as RoomChatSubscription;}),coordinator=createRoomChatSyncCoordinator({onMessages:value=>snapshots.push(value),onStatus:value=>statuses.push(value),onError:vi.fn()},{fetchHistory,subscribe});return{coordinator,subscriptions,statuses,snapshots,fetchHistory};};
 it('subscribes before history, buffers overlap, and deduplicates by trusted id',async()=>{const shared=message(1),realtime=message(2),subscriptions:SubscribeRoomChatMessagesOptions[]=[],snapshots:RoomChatMessage[][]=[];const subscribe=vi.fn(async(options:SubscribeRoomChatMessagesOptions)=>{subscriptions.push(options);options.onMessage(realtime);options.onStatus('live');return{roomId:options.roomId,ready:Promise.resolve('live' as const),unsubscribe:vi.fn(async()=>{})} as RoomChatSubscription;}),coordinator=createRoomChatSyncCoordinator({onMessages:value=>snapshots.push(value),onStatus:vi.fn(),onError:vi.fn()},{subscribe,fetchHistory:vi.fn(async()=>[shared,realtime])});await coordinator.enter(id(99),'ABC234');expect(coordinator.messages).toEqual([shared,realtime]);expect(snapshots.at(-1)).toEqual([shared,realtime]);});
 it('deduplicates trusted send acknowledgements from later Realtime and bounds memory',async()=>{const h=harness();await h.coordinator.enter(id(99),'ABC234');const accepted=message(1);expect(h.coordinator.acceptTrusted(accepted)).toBe(true);h.subscriptions[0].onMessage(accepted);expect(h.coordinator.messages.filter(value=>value.id===accepted.id)).toHaveLength(1);for(let n=2;n<=ROOM_CHAT_MEMORY_LIMIT+5;n++)h.coordinator.acceptTrusted(message(n));expect(h.coordinator.messages).toHaveLength(ROOM_CHAT_MEMORY_LIMIT);});
 it('performs one trusted recovery fetch after a connection gap without polling',async()=>{const h=harness([message(1)]);await h.coordinator.enter(id(99),'ABC234');expect(h.fetchHistory).toHaveBeenCalledTimes(1);h.subscriptions[0].onStatus('unavailable');h.subscriptions[0].onStatus('live');await vi.waitFor(()=>expect(h.fetchHistory).toHaveBeenCalledTimes(2));expect(subscriptionSource).not.toMatch(/setInterval|setTimeout\([^,]+,\s*\d+\).*fetch/i);});
 it('queues exactly one recovery fetch when unavailable-to-live occurs before initial history completes',async()=>{let resolveHistory!:(value:RoomChatMessage[])=>void;const history=new Promise<RoomChatMessage[]>(resolve=>{resolveHistory=resolve;}),subscriptions:SubscribeRoomChatMessagesOptions[]=[],fetchHistory=vi.fn().mockImplementationOnce(()=>history).mockResolvedValue([message(2)]),coordinator=createRoomChatSyncCoordinator({onMessages:vi.fn(),onStatus:vi.fn(),onError:vi.fn()},{fetchHistory,subscribe:async options=>{subscriptions.push(options);return{roomId:options.roomId,ready:Promise.resolve('unavailable'),unsubscribe:vi.fn(async()=>{})};}});const entering=coordinator.enter(id(99),'ABC234');await vi.waitFor(()=>expect(fetchHistory).toHaveBeenCalledOnce());subscriptions[0].onStatus('unavailable');subscriptions[0].onStatus('live');expect(fetchHistory).toHaveBeenCalledOnce();resolveHistory([message(1)]);await entering;await vi.waitFor(()=>expect(fetchHistory).toHaveBeenCalledTimes(2));expect(coordinator.messages).toEqual([message(1),message(2)]);});
 it('protects new-room and same-room generations from stale completions and unsubscribes',async()=>{let resolveOld!:(value:RoomChatMessage[])=>void;const old=new Promise<RoomChatMessage[]>(resolve=>{resolveOld=resolve;}),unsub=vi.fn(async()=>{}),subscriptions:SubscribeRoomChatMessagesOptions[]=[],fetchHistory=vi.fn().mockImplementationOnce(()=>old).mockResolvedValue([]),coordinator=createRoomChatSyncCoordinator({onMessages:vi.fn(),onStatus:vi.fn(),onError:vi.fn()},{fetchHistory,subscribe:async options=>{subscriptions.push(options);options.onStatus('live');return{roomId:options.roomId,ready:Promise.resolve('live'),unsubscribe:unsub};}});const entering=coordinator.enter(id(99),'ABC234');await vi.waitFor(()=>expect(fetchHistory).toHaveBeenCalledOnce());await coordinator.enter(id(98),'XYZ789');resolveOld([message(1,id(99))]);await entering;expect(coordinator.isCurrent(id(98))).toBe(true);expect(coordinator.messages).toEqual([]);await coordinator.leave();expect(unsub).toHaveBeenCalled();});
 it('rejects stale same-room completions after leave and a new generation',async()=>{let resolveOld!:(value:RoomChatMessage[])=>void;const old=new Promise<RoomChatMessage[]>(resolve=>{resolveOld=resolve;}),fetchHistory=vi.fn().mockImplementationOnce(()=>old).mockResolvedValue([message(2)]),subscribe=async(options:SubscribeRoomChatMessagesOptions)=>{options.onStatus('live');return{roomId:options.roomId,ready:Promise.resolve('live' as const),unsubscribe:vi.fn(async()=>{})};},coordinator=createRoomChatSyncCoordinator({onMessages:vi.fn(),onStatus:vi.fn(),onError:vi.fn()},{fetchHistory,subscribe});const first=coordinator.enter(id(99),'ABC234');await vi.waitFor(()=>expect(fetchHistory).toHaveBeenCalledOnce());await coordinator.leave();await coordinator.enter(id(99),'ABC234');resolveOld([message(1)]);await first;expect(coordinator.messages).toEqual([message(2)]);});
});

describe('chat shell UI and escaping',()=>{
 it('renders one shared room chat in lobby and active/gameOver paints with trusted send/refresh lifecycle',()=>{for(const token of ['ROOM CHAT','data-chat-input','maxlength="500"','data-chat-send','SEND','data-refresh-chat','Chat connection unavailable.','roomChatSync.acceptTrusted','roomChatSync.refresh()','roomChatSync.leave()'])expect(shell).toContain(token);expect(shell).toContain('${chatPanel()}');expect(shell).not.toContain('Chat will appear here');});
 it('escapes names and all plain-text message content without Markdown/HTML rendering',()=>{for(const value of ['<script>alert(1)</script>','<img src=x onerror=alert(1)>','Gods & "Kings"',"Alice's Room",'<Temple>'])expect(escapeHtml(value)).not.toContain('<');expect(shell).toContain('escapeHtml(message.senderDisplayName)');expect(shell).toContain('escapeHtml(message.messageText)');expect(shell).not.toMatch(/marked\(|innerHTML\s*=\s*message\.messageText/);});
 it('keeps chat independent from M9/M10 and canonical gameplay',()=>{expect(shell).not.toMatch(/roomSync\.acceptTrusted\([^)]*chat|roomLobbySync\.noteSignal\([^)]*chat/i);expect(migration).not.toMatch(/create trigger[\s\S]*room_chat_messages/i);});
});
