import {readdirSync,readFileSync} from 'node:fs';
import {describe,expect,it,vi} from 'vitest';
import type {SupabaseClient} from '@supabase/supabase-js';
import {manageLobby,ManageLobbyError} from '../src/platform/rooms/manageLobby';
import {listJoinableRooms,RoomDirectoryError} from '../src/platform/rooms/listJoinableRooms';
import {escapeHtml} from '../src/platform/shell';

const migrationUrl=new URL('../supabase/migrations/',import.meta.url);
const migration=readFileSync(new URL('../supabase/migrations/20260924000004_room_naming.sql',import.meta.url),'utf8');
const m20=readFileSync(new URL('../supabase/migrations/20260924000003_lobby_presence_and_stale_directory.sql',import.meta.url),'utf8');
const core=readFileSync(new URL('../supabase/migrations/20260919190346_create_ngsllc_core.sql',import.meta.url),'utf8');
const start=readFileSync(new URL('../supabase/migrations/20260920000004_start_game.sql',import.meta.url),'utf8');
const returnLobby=readFileSync(new URL('../supabase/migrations/20260924000001_return_finished_game_to_lobby.sql',import.meta.url),'utf8');
const manageEdge=readFileSync(new URL('../supabase/functions/manage-lobby/index.ts',import.meta.url),'utf8');
const listEdge=readFileSync(new URL('../supabase/functions/list-rooms/index.ts',import.meta.url),'utf8');
const manageClient=readFileSync(new URL('../src/platform/rooms/manageLobby.ts',import.meta.url),'utf8');
const listClient=readFileSync(new URL('../src/platform/rooms/listJoinableRooms.ts',import.meta.url),'utf8');
const lobby=readFileSync(new URL('../src/platform/rooms/lobby.ts',import.meta.url),'utf8');
const shell=readFileSync(new URL('../src/platform/shell.ts',import.meta.url),'utf8');
const priorHashes:Record<string,string>={
 '20260919190346_create_ngsllc_core.sql':'dfa5c612e9edc4c58b685d3a80c4ebd826f0c0450df3d5ed0689005f01029840','20260919190347_restrict_rls_auto_enable.sql':'16f698e12a5b68c5aa1022d37311ff127fe8350f8ed965eee08c8cf4a5fd592b','20260919190348_create_room_server_command.sql':'ca25b2ddda8a351ad526a7884f0d8920fb137652f77a7235d4679fbb8941dd81','20260920000000_join_room_server_command.sql':'bb96b67025475877d89a335e278dc6ce9b8b733d3c9858fd49dbdbd5a17aef79','20260920000001_lobby_lifecycle.sql':'5ec1beccbe16f9a267806ddd155d08a349286a4d6625a0de3ac6eb94d592af96','20260920000002_player_color_selection.sql':'0887a28b155576694e22f339e82fd1951c7ce9978da439661a217bbdeffc2230','20260920000003_player_ready_state.sql':'73ac0263ec0f0af59da1394bdc00b687a47ac7f8c7e7587577813c5718de9f47','20260920000004_start_game.sql':'5bc2bd51cdb12166ad1285740a60760974925593d0b5b0e40be2140ce2230706','20260921000000_active_game_state_read.sql':'3956a00b749e0475e56b910e88671580ff4934b484498e05e875fcdf358359cb','20260921000001_gameplay_mutation.sql':'a80840b9a2cade11645b7360c31ec401e900cc06413f5335e62c67a642dffaab','20260922000000_realtime_game_sync.sql':'53d6e92e41b06371bab2be49dc8e05cf0f609e2d49addc258e135b6dae8696b6','20260922000001_realtime_lobby_sync.sql':'783559b6fcfd841a5dbda98bf21a27bccce2899a9687c644a914955114bbc27a','20260922000002_multiplayer_ai_players.sql':'68481194f0c79ea8b5729db7088e9fd4bacce03bf5ac76c902af0c69c1b418ff','20260923000000_fix_multiplayer_ai_sql_ambiguity.sql':'3d684ce2b4285b1cce4747f27679d5693071a47fbef091d837c373cd83e5ba6d','20260923000001_fix_start_game_coalesce.sql':'5139fda069f56017e9fcbccd8ce73a29dd05804494c6c9a01829ef816ffe8afb','20260923000002_active_player_ai_takeover.sql':'1fca1fc0096a6cd37c53e5e7462569b34709b0094e636218e2575fe889e13905','20260924000000_lobby_discovery_and_host_moderation.sql':'42b08a785f5c289639211df0c03344909f005f76b8e1848c65e5c99ad5efe568','20260924000001_return_finished_game_to_lobby.sql':'af563be022bac9166854cf75a03841cdaf0159f14ceecb6f722661720a5a8a9a','20260924000002_fix_return_to_lobby_signal_read.sql':'2eccc6391230116a28c6a3b19be44bb56c29412f1efcc6d48cb50f360f765e42','20260924000003_lobby_presence_and_stale_directory.sql':'1864a73135e82f553c3c500a10676e7ffcc7239971eb6cd831b2c35dfa01f86a',
};
const functionBody=(name:string)=>migration.match(new RegExp(`create function ${name.replace('.','\\.')}\\([\\s\\S]*?\\n\\$\\$;`))?.[0]??'';
const rename=functionBody('public.set_room_name_server');
const directory=functionBody('public.list_joinable_rooms_server');
const trigger=migration.match(/create or replace function ngsllc_private\.bump_room_lobby_update\(\)[\s\S]*?\n\$\$;/)?.[0]??'';
const authenticatedClient=(invoke:(name:string,options:{body:unknown})=>Promise<unknown>)=>({auth:{getSession:vi.fn(async()=>({data:{session:{user:{id:'user-1'}}},error:null}))},functions:{invoke:vi.fn(invoke)}}) as unknown as SupabaseClient;

describe('room naming migration #21 STATIC CONTRACT (not PostgreSQL execution)',()=>{
 it('adds exactly migration 21 and pins migrations 1-20 unchanged',async()=>{const names=readdirSync(migrationUrl,{withFileTypes:true}).filter(entry=>!entry.isDirectory()&&entry.name.endsWith('.sql')).map(entry=>entry.name).sort();expect(names).toHaveLength(21);expect(names.at(-1)).toBe('20260924000004_room_naming.sql');for(const[name,hash]of Object.entries(priorHashes)){const bytes=new TextEncoder().encode(readFileSync(new URL(`../supabase/migrations/${name}`,import.meta.url),'utf8')),digest=await crypto.subtle.digest('SHA-256',bytes),actual=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,'0')).join('');expect(actual).toBe(hash);}});
 it('adds nullable non-unique room_name with null default and canonical storage constraints',()=>{expect(migration).toContain('add column room_name text default null');expect(migration).toContain('constraint rooms_room_name_valid');expect(migration).toContain('room_name is null');expect(migration).toContain('room_name = pg_catalog.btrim(room_name)');expect(migration).toContain('pg_catalog.char_length(room_name) between 1 and 50');expect(migration).toContain("room_name !~ '[[:cntrl:]]'");expect(migration).not.toMatch(/unique[^;]*room_name|room_name[^;]*unique/i);});
 it('normalizes, validates, locks, authorizes current host membership, and permits lobby-only mutation',()=>{for(const token of ['pg_catalog.upper(pg_catalog.btrim(p_room_code))','v_requested_room_name := pg_catalog.btrim(p_room_name)',"p_room_name ~ '[[:cntrl:]]'",'for update of r','requester.user_id = p_user_id','v_host_user_id <> p_user_id',"v_room_status is distinct from 'lobby'"])expect(rename).toContain(token);expect(rename.indexOf('for update of r')).toBeLessThan(rename.indexOf('v_host_user_id <> p_user_id'));});
 it('implements clear and no-op semantics without touching unrelated state',()=>{expect(rename).toContain('if p_room_name is null then');expect(rename).toContain('v_requested_room_name := null');expect(rename).toContain('v_current_room_name is not distinct from v_requested_room_name');expect(rename.indexOf('is not distinct from')).toBeLessThan(rename.indexOf('update public.rooms as r'));expect(rename).toContain('set room_name = v_requested_room_name');for(const forbidden of ['room_players','room_ai_players','room_kicks','room_states','join_mode =','last_seen_at','is_ready','player_color','turn_order'])expect(rename.slice(rename.indexOf('update public.rooms as r'))).not.toContain(forbidden);});
 it('is SECURITY INVOKER with empty path and service-role-only execution',()=>{expect(rename).toContain('security invoker');expect(rename).toContain("set search_path = ''");expect(migration).toContain('revoke execute on function public.set_room_name_server(text,uuid,text)\nfrom public, anon, authenticated, service_role');expect(migration).toContain('grant execute on function public.set_room_name_server(text,uuid,text)\nto service_role');expect(core).toContain('grant select, insert, update, delete on table public.rooms to service_role');expect(migration).not.toMatch(/grant\s+update\s+on\s+(?:table\s+)?public\.rooms/i);});
 it('extends exactly one rooms M10 trigger while preserving human, AI, host, status, mode, and last-seen behavior',()=>{for(const token of ['new.display_name is distinct from old.display_name','new.player_color is distinct from old.player_color','new.is_ready is distinct from old.is_ready','new.bot_strategy is distinct from old.bot_strategy','new.host_user_id is distinct from old.host_user_id','new.status is distinct from old.status','new.join_mode is distinct from old.join_mode','new.room_name is distinct from old.room_name'])expect(trigger).toContain(token);expect(trigger).not.toContain('last_seen_at');expect(migration).toContain('drop trigger rooms_bump_lobby_update on public.rooms');expect(migration.match(/create trigger rooms_bump_lobby_update/g)).toHaveLength(1);expect(migration).toContain('after update of host_user_id, status, join_mode, room_name on public.rooms');});
 it('recreates the expanded directory safely and preserves every freshness/privacy filter',()=>{expect(migration).toContain('drop function public.list_joinable_rooms_server(text,uuid);');expect(migration).not.toMatch(/drop function[^;]*cascade/i);for(const token of ['room_code text','room_name text','host_display_name text','r.room_name',"g.status = 'active'","r.status = 'lobby'","r.join_mode = 'public'",'host_player.user_id = r.host_user_id',"host_player.last_seen_at >= pg_catalog.now() - interval '90 seconds'",'counts.human_count + counts.ai_count < g.max_players','rk.user_id = p_user_id','order by r.created_at desc, r.code asc'])expect(directory).toContain(token);for(const forbidden of ['host_user_id text','last_seen_at timestamptz','room_id uuid','game_state'])expect(directory).not.toContain(forbidden);expect(migration).toContain('grant execute on function public.list_joinable_rooms_server(text,uuid)\nto service_role');});
 it('keeps naming metadata out of Start/canonical state and preserves it through Return to Lobby',()=>{expect(start).not.toContain('room_name');expect(returnLobby).not.toContain('room_name');expect(rename).not.toContain('game_state');expect(rename).not.toContain('state_version');});
 it('serializes rename with Start, Leave, Kick, join mode, and presence through the room row',()=>{expect(rename).toContain('for update of r');for(const token of ['for update of r','set_room_join_mode_server','kick_room_player_server'])expect(readFileSync(new URL('../supabase/migrations/20260924000000_lobby_discovery_and_host_moderation.sql',import.meta.url),'utf8')).toContain(token);expect(m20).toContain('for update of r');expect(returnLobby).toContain('for update of r');});
 it('does not alter publication or use invalid special SQL forms',()=>{expect(migration).not.toMatch(/\b(?:alter|create)\s+publication\b/i);expect(migration).not.toMatch(/\bdrop\s+function\b[^;]*\bcascade\b/i);for(const bad of ['pg_catalog.greatest','pg_catalog.least','pg_catalog.coalesce','pg_catalog.nullif'])expect(migration.toLowerCase()).not.toContain(bad);expect(migration).not.toMatch(/pg_catalog\.substring\([^)]*\sfrom\s/i);expect((migration.match(/end;\r?\n\$\$;/g)??[])).toHaveLength(3);});
});

describe('room naming browser trust boundary and DTOs',()=>{
 it('canonicalizes and sends a setRoomName command with no authority fields',async()=>{const invoke=vi.fn(async()=>({data:{roomCode:'ABC234'},error:null}));await manageLobby({roomCode:'abc234',command:{type:'setRoomName',roomName:'  The Last Temple  '}},authenticatedClient(invoke));expect(invoke).toHaveBeenCalledWith('manage-lobby',{body:{roomCode:'ABC234',command:{type:'setRoomName',roomName:'The Last Temple'}}});});
 it('sends null only for explicit clear and accepts ordinary punctuation',async()=>{const invoke=vi.fn(async()=>({data:{roomCode:'ABC234'},error:null})),client=authenticatedClient(invoke);await manageLobby({roomCode:'ABC234',command:{type:'setRoomName',roomName:null}},client);await manageLobby({roomCode:'ABC234',command:{type:'setRoomName',roomName:"Gods & Villagers: Bob's Round 2!"}},client);expect(invoke).toHaveBeenNthCalledWith(1,'manage-lobby',{body:{roomCode:'ABC234',command:{type:'setRoomName',roomName:null}}});});
 it('rejects blank, overlong, and control-containing names client-side',async()=>{const client=authenticatedClient(vi.fn());for(const roomName of ['   ','x'.repeat(51),'Bad\nName','Bad\tName'])await expect(manageLobby({roomCode:'ABC234',command:{type:'setRoomName',roomName}},client)).rejects.toBeInstanceOf(ManageLobbyError);});
 it('extends the existing Edge command with exact shape and verified identity',()=>{expect(manageEdge).toContain("command.type==='setRoomName'");expect(manageEdge).toContain("exact(command,['type','roomName'])");expect(manageEdge).toContain("rpc='set_room_name_server'");expect(manageEdge).toContain('p_user_id:user.id');expect(manageEdge).toContain('auth.getUser(token)');});
 it('accepts named and unnamed exact directory DTOs and rejects noncanonical names',async()=>{const base={roomCode:'ABC234',hostDisplayName:'Alice',humanPlayers:2,aiPlayers:1,totalPlayers:3,maxPlayers:8,createdAt:'2026-09-24T00:00:00Z'};for(const roomName of ['The Last Temple',null]){const client=authenticatedClient(vi.fn(async()=>({data:{rooms:[{...base,roomName}]},error:null})));await expect(listJoinableRooms({gameSlug:'worship-me'},client)).resolves.toEqual({rooms:[{...base,roomName}]});}for(const roomName of [' bad','Bad\nName','x'.repeat(51)]){const client=authenticatedClient(vi.fn(async()=>({data:{rooms:[{...base,roomName}]},error:null})));await expect(listJoinableRooms({gameSlug:'worship-me'},client)).rejects.toBeInstanceOf(RoomDirectoryError);}});
 it('uses explicit safe directory projection and strict client keys',()=>{expect(listEdge).toContain('roomName:row.room_name');expect(listEdge).not.toMatch(/\.\.\.row/);expect(listClient).toContain("'aiPlayers,createdAt,hostDisplayName,humanPlayers,maxPlayers,roomCode,roomName,totalPlayers'");expect(lobby).toContain('join_mode,room_name');expect(lobby).toContain('roomName:room.room_name');});
});

describe('room naming UI and escaping',()=>{
 it('renders prominent escaped name plus persistent code/copy and host-only editor controls',()=>{for(const token of ['lobby-room-name','ROOM CODE','data-copy','data-room-name','maxlength="50"','data-save-room-name','SAVE NAME','data-clear-room-name','CLEAR NAME'])expect(shell).toContain(token);expect(shell).toContain('${escapeHtml(roomName)}');expect(shell).toContain("const nameRoom=lobby.room.isCurrentUserHost?");});
 it('shows names in the public directory and preserves unnamed fallback',()=>{expect(shell).toContain('room.roomName?');expect(shell).toContain('${escapeHtml(room.roomName)}');expect(shell).toContain('Host: ${escapeHtml(room.hostDisplayName)}');});
 it('escapes hostile and punctuation-rich names as plain text',()=>{expect(escapeHtml('<script>alert(1)</script>')).toBe('&lt;script&gt;alert(1)&lt;/script&gt;');expect(escapeHtml('Gods & "Kings"')).toBe('Gods &amp; &quot;Kings&quot;');expect(escapeHtml("Alice's Room")).toBe('Alice&#39;s Room');expect(escapeHtml('<Temple>')).toBe('&lt;Temple&gt;');});
 it('refreshes authoritative M10 state after save/clear and never adds active-game naming controls',()=>{expect(shell).toContain("command:{type:'setRoomName',roomName:value}");expect(shell).toMatch(/submitRoomName[\s\S]*roomLobbySync\.refresh\(\)/);const active=shell.slice(shell.indexOf('function renderActiveGameState'));expect(active).not.toContain('data-room-name');});
});
