import {describe,expect,it} from 'vitest';import {applyAction} from '../src/games/worship-me/engine/reducer';import {deserializeGame,serializeGame} from '../src/games/worship-me/engine/serialization';import {game,player} from './helpers';
function roundWith(s:ReturnType<typeof game>,action:Parameters<typeof applyAction>[1]){const round=s.round;s=applyAction(s,action);while(s.phase==='placement'&&s.round===round)s=applyAction(s,{type:'endTurn',playerId:s.turnOrder[s.currentPlayerIndex]});return s}
describe('next-round Temple effects',()=>{
 it('own Temple Bless earns one extra Bless placement next round',()=>{let s=game(),p=player(s);s=roundWith(s,{type:'placeTile',cellId:p.templeCellId,kind:'bless',playerId:p.id});expect(s.extraBlessThisRound[p.id]).toBe(1)});
 it('opponent Temple Bless sets persistent first player',()=>{let s=game(),a=player(s),b=player(s,1);s=roundWith(s,{type:'placeTile',cellId:b.templeCellId,kind:'bless',playerId:a.id});expect(s.persistentFirstPlayerId).toBe(b.id);expect(s.turnOrder[s.currentPlayerIndex]).toBe(b.id)});
 it('persistent first player survives later rounds',()=>{let s=game(),a=player(s),b=player(s,1);s=roundWith(s,{type:'placeTile',cellId:b.templeCellId,kind:'bless',playerId:a.id});s=roundWith(s,{type:'endTurn',playerId:b.id});expect(s.persistentFirstPlayerId).toBe(b.id)});
 it('own Temple Smite reverses next round',()=>{let s=game(),p=player(s);s=roundWith(s,{type:'placeTile',cellId:p.templeCellId,kind:'smite',playerId:p.id});expect(s.direction).toBe(-1)});
 it('opponent Temple Smite removes exactly one placement next round, then expires',()=>{let s=game(),a=player(s),b=player(s,1);s=roundWith(s,{type:'placeTile',cellId:b.templeCellId,kind:'smite',playerId:a.id});expect(s.placementPenaltyThisRound[b.id]).toBe(1);expect(2+(s.extraBlessThisRound[b.id]??0)-s.placementPenaltyThisRound[b.id]).toBe(1);s=roundWith(s,{type:'endTurn',playerId:s.turnOrder[s.currentPlayerIndex]});expect(s.placementPenaltyThisRound[b.id]).toBe(0)});
 it('penalty subtracts one from an earned extra Bless without changing Smite maximum',()=>{let s=game(),a=player(s),b=player(s,1);s.extraBlessNextRound[b.id]=1;s=roundWith(s,{type:'placeTile',cellId:b.templeCellId,kind:'smite',playerId:a.id});expect(2+s.extraBlessThisRound[b.id]-s.placementPenaltyThisRound[b.id]).toBe(2);expect(s.smiteUsed[b.id]).toBe(false)});
 it('pending placement penalties survive serialization',()=>{const s=game(),b=player(s,1);s.nextRoundPlacementPenalty[b.id]=1;const loaded=deserializeGame(serializeGame(s));expect(loaded.nextRoundPlacementPenalty[b.id]).toBe(1)});
});
