import {next} from '../engine/rng.ts';
import type {AIResolutionCandidateDiagnostic,BotStrategy,GameAction,GameState,ResolutionDecision,ScoreComponents} from '../engine/types.ts';
import {scoreActionDetailed,scoreResolutionOption,scoreSmiteResourceChoice,weights,type StrategyWeights} from './scoring.ts';
import {buildDiagnostics} from './diagnostics.ts';
import type {BotChoice,BotPolicy,ResolutionChoice} from './types.ts';
function pick(rngState:number,length:number){let n;[n,rngState]=next(rngState);return{index:Math.floor(n*length),rngState}}
const zero=():ScoreComponents=>({base:0,templeProgress:0,templePreservation:0,endTriggerValue:0,resourceValue:0,productionValue:0,populationGrowth:0,priestValue:0,disruption:0,exploration:0,mobility:0,resourceRemovalValue:0,productionPreventedValue:0,strategicDisruptionValue:0,populationReleaseValue:0,squareCongestionValue:0,terminalPressure:0,resourceSaturationPenalty:0,stagnationPenalty:0,reversalPenalty:0,riskPenalty:0});
function resolutionLabel(state:GameState,index:number){const p=state.pendingResolution!;if(p.type==='smiteResource')return`Remove 1 ${p.options[index]}`;const o=p.options[index];return`${o.resourceOnly?'Move':o.neutral?'Influence Neutral':'Move'} ${o.moverRole??''}${o.resource?` + ${o.resource}`:''} ${o.from} → ${o.to}`.replace(/\s+/g,' ').trim()}
function strategicPending(state:GameState,strategy:Exclude<BotStrategy,'random'>,w:StrategyWeights):ResolutionChoice{const pending=state.pendingResolution;if(!pending)throw Error('No pending decision');if(pending.type==='blessEdgeMove'){const scored=pending.options.map((option,index)=>({index,label:resolutionLabel(state,index),...scoreResolutionOption(state,pending.playerId,option,w)})).sort((a,b)=>b.score-a.score||a.label.localeCompare(b.label)),max=scored[0].score,best=scored.filter(x=>x.score===max),chosen=pick(state.rngState,best.length),selected=best[chosen.index],candidates:AIResolutionCandidateDiagnostic[]=scored.slice(0,5).map((x,rank)=>({rank:rank+1,choice:x.label,score:x.score,components:x.components,optionIndex:x.index}));return{decision:{type:'resolveBlessEdge',playerId:pending.playerId,optionIndex:selected.index},rngState:chosen.rngState,diagnostics:{strategy,resolutionType:pending.type,resolutionCandidates:candidates,selectedResolution:selected.label,selectedScore:selected.score}}}const scored=pending.options.map((resource,index)=>({index,resource,label:resolutionLabel(state,index),...scoreSmiteResourceChoice(state,pending.cellId,resource,w)})).sort((a,b)=>b.score-a.score||a.label.localeCompare(b.label)),max=scored[0].score,best=scored.filter(x=>x.score===max),chosen=pick(state.rngState,best.length),selected=best[chosen.index],candidates:AIResolutionCandidateDiagnostic[]=scored.map((x,rank)=>({rank:rank+1,choice:x.label,score:x.score,components:x.components,resource:x.resource}));return{decision:{type:'resolveSmiteResource',playerId:pending.playerId,resource:selected.resource},rngState:chosen.rngState,diagnostics:{strategy,resolutionType:pending.type,resolutionCandidates:candidates,selectedResolution:selected.label,selectedScore:selected.score}}}
function randomPending(state:GameState):ResolutionChoice{const pending=state.pendingResolution;if(!pending)throw Error('No pending decision');const chosen=pick(state.rngState,pending.options.length),decision:ResolutionDecision=pending.type==='blessEdgeMove'?{type:'resolveBlessEdge',playerId:pending.playerId,optionIndex:chosen.index}:{type:'resolveSmiteResource',playerId:pending.playerId,resource:pending.options[chosen.index]};return{decision,rngState:chosen.rngState,diagnostics:{strategy:'random',resolutionType:pending.type,resolutionCandidates:pending.options.slice(0,5).map((_,i)=>({rank:i+1,choice:resolutionLabel(state,i),score:0,components:zero(),...(pending.type==='blessEdgeMove'?{optionIndex:i}:{resource:pending.options[i]})})),selectedResolution:resolutionLabel(state,chosen.index),selectedScore:0}}}
function randomChoice(state:GameState,actions:GameAction[]):BotChoice{const chosen=pick(state.rngState,actions.length),action=actions[chosen.index],scores=new Map(actions.map(a=>[a,{score:0,components:zero()}]));return{action,rngState:chosen.rngState,diagnostics:buildDiagnostics(state,'random',actions,scores,action)}}
function heuristic(id:Exclude<BotStrategy,'random'>,name:string):BotPolicy{return{id,name,chooseAction(state,actions){const scored=actions.map(action=>({action,...scoreActionDetailed(state,action,weights[id])})),max=Math.max(...scored.map(x=>x.score)),best=scored.filter(x=>x.score===max),chosen=pick(state.rngState,best.length),action=best[chosen.index].action,scores=new Map(scored.map(x=>[x.action,{score:x.score,components:x.components}]));return{action,rngState:chosen.rngState,score:max,diagnostics:buildDiagnostics(state,id,actions,scores,action)}},choosePendingResolution(state){return strategicPending(state,id,weights[id])}}}
export const policies:Record<BotStrategy,BotPolicy>={random:{id:'random',name:'Random',chooseAction:randomChoice,choosePendingResolution:randomPending},growth:heuristic('growth','Growth'),templeRush:heuristic('templeRush','Temple Rush'),balanced:heuristic('balanced','Balanced')};
export const getPolicy=(id:BotStrategy)=>policies[id];
