import {createClient} from 'npm:@supabase/supabase-js@2.116.0';

const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'};
const response=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers});
const key=(name:string):string|undefined=>{try{const value=(JSON.parse(Deno.env.get(name)??'{}') as Record<string,unknown>).default;return typeof value==='string'&&value.trim()?value:undefined;}catch{return;}};
const exact=(value:Record<string,unknown>,keys:string[])=>Object.keys(value).sort().join(',')===[...keys].sort().join(',');
const uuid=(value:unknown)=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);

Deno.serve(async request=>{
 if(request.method==='OPTIONS')return new Response(null,{status:204,headers});if(request.method!=='POST')return response(405,{error:'Method not allowed'});
 const authorization=request.headers.get('Authorization'),token=authorization?.match(/^Bearer\s+(.+)$/i)?.[1];if(!token)return response(401,{error:'Authentication required'});
 const url=Deno.env.get('SUPABASE_URL'),publishableKey=key('SUPABASE_PUBLISHABLE_KEYS'),secretKey=key('SUPABASE_SECRET_KEYS');if(!url||!publishableKey||!secretKey)return response(500,{error:'Server configuration error'});
 const userClient=createClient(url,publishableKey,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data:{user},error:authError}=await userClient.auth.getUser(token);if(authError||!user)return response(401,{error:'Invalid or expired authentication'});
 let payload:unknown;try{payload=await request.json();}catch{return response(400,{error:'Invalid lobby management request'});}if(!payload||typeof payload!=='object'||Array.isArray(payload))return response(400,{error:'Invalid lobby management request'});const body=payload as Record<string,unknown>;if(!exact(body,['roomCode','command'])||typeof body.roomCode!=='string'||!body.command||typeof body.command!=='object'||Array.isArray(body.command))return response(400,{error:'Invalid lobby management request'});const roomCode=body.roomCode.trim().toUpperCase(),command=body.command as Record<string,unknown>;if(!/^[A-Z0-9]{6,10}$/.test(roomCode))return response(400,{error:'Invalid lobby management request'});
 let rpc:string,args:Record<string,unknown>={p_room_code:roomCode,p_user_id:user.id};if(command.type==='setJoinMode'&&exact(command,['type','joinMode'])&&(command.joinMode==='public'||command.joinMode==='code')){rpc='set_room_join_mode_server';args={...args,p_join_mode:command.joinMode};}else if(command.type==='setRoomName'&&exact(command,['type','roomName'])&&(command.roomName===null||typeof command.roomName==='string')){rpc='set_room_name_server';args={...args,p_room_name:command.roomName};}else if(command.type==='kickPlayer'&&exact(command,['type','targetUserId'])&&uuid(command.targetUserId)){rpc='kick_room_player_server';args={...args,p_target_user_id:command.targetUserId};}else return response(400,{error:'Invalid lobby management request'});
 const server=createClient(url,secretKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data,error}=await server.rpc(rpc,args);if(error){if(error.code==='22023')return response(400,{error:'Invalid lobby management request'});if(error.code==='P0002')return response(404,{error:'Room or player not found or unavailable'});if(error.code==='P0003')return response(403,{error:'Only the host can manage the lobby.'});if(error.code==='P0004')return response(409,{error:'Lobby is unavailable.'});return response(500,{error:'Unable to manage lobby'});}const row=(Array.isArray(data)?data[0]:data) as Record<string,unknown>|undefined;if(!row||typeof row.room_code!=='string')return response(500,{error:'Unable to manage lobby'});return response(200,{roomCode:row.room_code});
});
