import type {RoomChatMessage,RoomChatSyncStatus} from '../types';
import {getRoomChatMessages} from './getRoomChatMessages';
import {compareRoomChatMessages} from './roomChatMessage';
import {subscribeRoomChatMessages,type RoomChatSubscription,type SubscribeRoomChatMessagesOptions} from './subscribeRoomChatMessages';

export const ROOM_CHAT_MEMORY_LIMIT=200;
export interface RoomChatSyncCallbacks{onMessages(messages:RoomChatMessage[]):void;onStatus(status:RoomChatSyncStatus):void;onError(error:unknown):void}
export interface RoomChatSyncDependencies{fetchHistory(roomId:string):Promise<RoomChatMessage[]>;subscribe(options:SubscribeRoomChatMessagesOptions):Promise<RoomChatSubscription>}
export interface RoomChatSyncCoordinator{enter(roomId:string,roomCode:string):Promise<void>;leave():Promise<void>;refresh():Promise<RoomChatMessage[]|undefined>;acceptTrusted(message:RoomChatMessage):boolean;isCurrent(roomId:string):boolean;readonly messages:RoomChatMessage[];readonly status:RoomChatSyncStatus}
export function createRoomChatSyncCoordinator(callbacks:RoomChatSyncCallbacks,dependencies:RoomChatSyncDependencies={fetchHistory:getRoomChatMessages,subscribe:subscribeRoomChatMessages}):RoomChatSyncCoordinator{let generation=0,currentRoomId:string|undefined,subscription:RoomChatSubscription|undefined,status:RoomChatSyncStatus='unavailable',initialized=false,hadGap=false,recoveryPending=false,refreshInFlight:Promise<RoomChatMessage[]|undefined>|undefined;let values:RoomChatMessage[]=[];
 const emit=()=>callbacks.onMessages([...values]);
 const merge=(incoming:RoomChatMessage[])=>{const byId=new Map(values.map(message=>[message.id,message]));for(const message of incoming)if(message.roomId===currentRoomId)byId.set(message.id,message);values=[...byId.values()].sort(compareRoomChatMessages).slice(-ROOM_CHAT_MEMORY_LIMIT);};
 const acceptTrusted=(message:RoomChatMessage)=>{if(!currentRoomId||message.roomId!==currentRoomId||values.some(existing=>existing.id===message.id))return false;merge([message]);if(initialized)emit();return true;};
 const refresh=()=>{if(!currentRoomId)return Promise.resolve(undefined);if(refreshInFlight)return refreshInFlight;const roomId=currentRoomId,token=generation;const request=dependencies.fetchHistory(roomId).then(history=>{if(token!==generation||currentRoomId!==roomId)return undefined;merge(history);initialized=true;emit();return[...values];}).catch(error=>{if(token===generation&&currentRoomId===roomId)callbacks.onError(error);return undefined;});refreshInFlight=request;void request.finally(()=>{if(refreshInFlight===request)refreshInFlight=undefined;if(token===generation&&currentRoomId===roomId&&status==='live'&&recoveryPending){recoveryPending=false;void refresh();}});return request;};
 const leave=async()=>{const old=subscription;generation++;currentRoomId=undefined;subscription=undefined;status='unavailable';initialized=false;hadGap=false;recoveryPending=false;refreshInFlight=undefined;values=[];if(old)await old.unsubscribe();};
 const enter=async(roomId:string,_roomCode:string)=>{if(currentRoomId===roomId&&subscription)return;await leave();const token=++generation;currentRoomId=roomId;status='connecting';callbacks.onStatus(status);try{const created=await dependencies.subscribe({roomId,onMessage:message=>{if(token===generation&&currentRoomId===roomId)acceptTrusted(message);},onStatus:next=>{if(token!==generation||currentRoomId!==roomId)return;status=next;callbacks.onStatus(next);if(next==='unavailable'){hadGap=true;return;}if(next==='live'&&hadGap){hadGap=false;if(initialized)void refresh();else recoveryPending=true;}}});if(token!==generation||currentRoomId!==roomId){await created.unsubscribe();return;}subscription=created;await created.ready;if(token!==generation||currentRoomId!==roomId)return;await refresh();}catch(error){if(token===generation&&currentRoomId===roomId){status='unavailable';callbacks.onStatus(status);callbacks.onError(error);await refresh();}}};
 return{enter,leave,refresh,acceptTrusted,isCurrent:roomId=>currentRoomId===roomId,get messages(){return[...values];},get status(){return status;}};
}
