import type {RealtimeChannel,SupabaseClient} from '@supabase/supabase-js';
import {ensureAnonymousSession} from '../auth/session';
import {getSupabaseClient} from '../supabase/client';
import type {RoomChatMessage,RoomChatSyncStatus} from '../types';
import {roomChatMessageFromRow} from './roomChatMessage';

export interface RoomChatSubscription{roomId:string;ready:Promise<RoomChatSyncStatus>;unsubscribe():Promise<void>}
export interface SubscribeRoomChatMessagesOptions{roomId:string;onMessage(message:RoomChatMessage):void;onStatus(status:RoomChatSyncStatus):void;connectionTimeoutMs?:number}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export async function subscribeRoomChatMessages(options:SubscribeRoomChatMessagesOptions,client:SupabaseClient=getSupabaseClient()):Promise<RoomChatSubscription>{if(!uuid.test(options.roomId))throw Error('Invalid room id.');await ensureAnonymousSession(client);let active=true,settled=false,resolveReady!:(status:RoomChatSyncStatus)=>void;const ready=new Promise<RoomChatSyncStatus>(resolve=>{resolveReady=resolve;});const settle=(status:RoomChatSyncStatus)=>{if(settled)return;settled=true;globalThis.clearTimeout(timeout);resolveReady(status);};const timeout=globalThis.setTimeout(()=>{if(!active||settled)return;options.onStatus('unavailable');settle('unavailable');},options.connectionTimeoutMs??4000);options.onStatus('connecting');const channel:RealtimeChannel=client.channel(`room-chat:${options.roomId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'room_chat_messages',filter:`room_id=eq.${options.roomId}`},payload=>{if(!active)return;const message=roomChatMessageFromRow(payload.new);if(message&&message.roomId===options.roomId)options.onMessage(message);}).subscribe(status=>{if(!active)return;if(status==='SUBSCRIBED'){options.onStatus('live');settle('live');return;}if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED'){options.onStatus('unavailable');settle('unavailable');}});return{roomId:options.roomId,ready,async unsubscribe(){if(!active)return;active=false;globalThis.clearTimeout(timeout);settle('unavailable');await client.removeChannel(channel);}};}
