import type {RealtimeChannel,SupabaseClient} from '@supabase/supabase-js';
import {ensureAnonymousSession} from '../auth/session';
import {getSupabaseClient} from '../supabase/client';
import type {RoomKickNotice} from '../types';

export interface RoomKickSubscription{roomId:string;unsubscribe():Promise<void>}
export interface SubscribeRoomKicksOptions{roomId:string;onKick(notice:RoomKickNotice):void}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export async function subscribeRoomKicks(options:SubscribeRoomKicksOptions,client:SupabaseClient=getSupabaseClient()):Promise<RoomKickSubscription>{if(!uuid.test(options.roomId))throw Error('Invalid room id.');const {user}=await ensureAnonymousSession(client);let active=true,settled=false,resolveReady!:()=>void;const ready=new Promise<void>(resolve=>{resolveReady=resolve;});const settle=()=>{if(!settled){settled=true;resolveReady();}};const channel:RealtimeChannel=client.channel(`room-kicks:${options.roomId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'room_kicks',filter:`room_id=eq.${options.roomId}`},payload=>{if(!active||!payload.new||typeof payload.new!=='object')return;const row=payload.new as Record<string,unknown>;if(row.room_id===options.roomId&&row.user_id===user.id&&typeof row.kicked_at==='string')options.onKick({roomId:options.roomId,kickedAt:row.kicked_at});}).subscribe(status=>{if(status==='SUBSCRIBED'||status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED')settle();});await Promise.race([ready,new Promise<void>(resolve=>globalThis.setTimeout(resolve,4000))]);if(active){const existing=await client.from('room_kicks').select('room_id,user_id,kicked_at').eq('room_id',options.roomId).maybeSingle();if(!existing.error&&existing.data&&existing.data.room_id===options.roomId&&existing.data.user_id===user.id&&typeof existing.data.kicked_at==='string')options.onKick({roomId:options.roomId,kickedAt:existing.data.kicked_at});}return{roomId:options.roomId,async unsubscribe(){if(!active)return;active=false;settle();await client.removeChannel(channel);}};}
