import {createClient} from 'npm:@supabase/supabase-js@2.116.0';

const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'};
const response=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers});
const key=(name:string):string|undefined=>{try{const value=(JSON.parse(Deno.env.get(name)??'{}') as Record<string,unknown>).default;return typeof value==='string'&&value.trim()?value:undefined;}catch{return;}};
const exact=(value:Record<string,unknown>,keys:string[])=>Object.keys(value).sort().join(',')===[...keys].sort().join(',');

Deno.serve(async request=>{
 if(request.method==='OPTIONS')return new Response(null,{status:204,headers});if(request.method!=='POST')return response(405,{error:'Method not allowed'});
 const authorization=request.headers.get('Authorization'),token=authorization?.match(/^Bearer\s+(.+)$/i)?.[1];if(!token)return response(401,{error:'Authentication required'});
 const url=Deno.env.get('SUPABASE_URL'),publishableKey=key('SUPABASE_PUBLISHABLE_KEYS'),secretKey=key('SUPABASE_SECRET_KEYS');if(!url||!publishableKey||!secretKey)return response(500,{error:'Server configuration error'});
 const userClient=createClient(url,publishableKey,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data:{user},error:authError}=await userClient.auth.getUser(token);if(authError||!user)return response(401,{error:'Invalid or expired authentication'});
 let payload:unknown;try{payload=await request.json();}catch{return response(400,{error:'Invalid room request'});}if(!payload||typeof payload!=='object'||Array.isArray(payload))return response(400,{error:'Invalid room request'});const body=payload as Record<string,unknown>;if(!exact(body,['roomCode','displayName'])||typeof body.roomCode!=='string'||typeof body.displayName!=='string')return response(400,{error:'Invalid room request'});const roomCode=body.roomCode.trim().toUpperCase(),displayName=body.displayName.trim();if(!/^[A-Z0-9]{6,10}$/.test(roomCode)||displayName.length<1||displayName.length>50)return response(400,{error:'Invalid room request'});
 const server=createClient(url,secretKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data,error}=await server.rpc('join_public_room_server',{p_room_code:roomCode,p_user_id:user.id,p_display_name:displayName});if(error){if(error.code==='22023')return response(400,{error:'Invalid room request'});if(error.code==='P0002'||error.code==='P0004')return response(404,{error:'Room not found or unavailable'});if(error.code==='P0003')return response(409,{error:'Room is full'});if(error.code==='P0007')return response(403,{error:'You were removed from this room by the host.'});return response(500,{error:'Unable to join room'});}const row=(Array.isArray(data)?data[0]:data) as Record<string,unknown>|undefined;if(!row||typeof row.room_id!=='string'||typeof row.room_code!=='string'||typeof row.game_id!=='string'||row.status!=='lobby'||typeof row.joined_new!=='boolean')return response(500,{error:'Unable to join room'});return response(200,{room:{id:row.room_id,code:row.room_code,gameId:row.game_id,status:'lobby'},joinedNew:row.joined_new});
});
