import {countNeutralsInPlay} from './neutrals.ts';
import {followerTotal,followersInOwnTemple} from './victory.ts';
import type {AIDecisionDiagnostics,Cell,GameHistory,GameState,HistoryEvent,HistoryEventType,PlacementAction} from './types.ts';
export const RULES_VERSION='directed-bless-edge-v3';
export function createHistory(direction:1|-1,firstPlayerId:string,startedAt=new Date().toISOString()):GameHistory{return{rulesVersion:RULES_VERSION,startedAt,initialDirection:direction,initialFirstPlayerId:firstPlayerId,nextOrdinal:1,events:[]}}
export function cellHistory(cell:Cell){return{id:cell.id,type:cell.visibleKind,hiddenType:cell.hiddenKind,occupants:{villagers:[...cell.villagers],priests:[...cell.priests]},wheat:cell.wheat,bread:cell.bread,modifier:cell.tileModifier?{...cell.tileModifier}:undefined}}
export function queueId(round:number,sequence:number){return`R${round}-Q${String(sequence).padStart(2,'0')}`}
export function recordHistory(state:GameState,type:HistoryEventType,description:string,data:Record<string,unknown>,options:{queuedActionId?:string;playerId?:string;id?:string}={}){const ordinal=state.history.nextOrdinal++,player=options.playerId?state.players.find(p=>p.id===options.playerId):undefined;const event:HistoryEvent={id:options.id??`R${state.round}-E${String(ordinal).padStart(4,'0')}`,ordinal,type,round:state.round,description,data,...(options.queuedActionId?{queuedActionId:options.queuedActionId}:{}),...(player?{playerId:player.id,playerName:player.name,playerColor:player.color,decisionSource:player.control,aiStrategy:player.botStrategy}: {})};state.history.events.push(event);return event}
export function placementHistory(state:GameState,placement:PlacementAction,sequence:number,aiDecision?:AIDecisionDiagnostics){const target=placement.type==='placeTile'?{targetType:'tile',coordinates:[placement.cellId],cells:[cellHistory(state.board.find(c=>c.id===placement.cellId)!)]}:placement.kind==='bless'?{targetType:'edge',origin:placement.from,destination:placement.to,coordinates:[placement.from,placement.to],cells:[cellHistory(state.board.find(c=>c.id===placement.from)!),cellHistory(state.board.find(c=>c.id===placement.to)!)]}:{targetType:'edge',coordinates:[placement.a,placement.b],cells:[cellHistory(state.board.find(c=>c.id===placement.a)!),cellHistory(state.board.find(c=>c.id===placement.b)!)]};const label=placement.type==='placeTile'?placement.cellId:placement.kind==='bless'?`${placement.from} → ${placement.to}`:`${placement.a}–${placement.b}`;recordHistory(state,'placement',`${placement.playerId} placed ${placement.kind} on ${label}.`,{sequence,actionClass:placement.kind,targetType:target.targetType,...('origin'in target?{origin:target.origin,destination:target.destination}:{}),targetCoordinates:target.coordinates,boardAtPlacement:target.cells,placementLegality:{legal:true},claimsCreated:true,...(aiDecision?{aiDecision}:{})},{playerId:placement.playerId,queuedActionId:queueId(state.round,sequence),id:`R${state.round}-P${placement.playerId.slice(1)}-A${state.placementsUsed[placement.playerId]??0}`})}
export function victorySnapshot(state:GameState){return state.players.map(p=>{const temple=state.board.find(c=>c.id===p.templeCellId)!,templePriests=temple.priests.filter(v=>v===p.color).length,templeFollowers=followersInOwnTemple(state,p);return{playerId:p.id,name:p.name,color:p.color,followers:followerTotal(state,p),templeFollowers,priestsInTemple:templePriests,templeTriggerSatisfied:templeFollowers>=state.config.templeTriggerFollowers}})}
export function exportPlayByPlay(state:GameState){const finalFollowers=Object.fromEntries(state.players.map(p=>[p.id,followerTotal(state,p)])),finalTempleFollowers=Object.fromEntries(victorySnapshot(state).map(p=>[p.playerId,p.templeFollowers]));return{format:'worship-me-play-by-play',schemaVersion:state.schemaVersion,rulesVersion:state.history.rulesVersion,metadata:{seed:state.seed,startedAt:state.history.startedAt,exportedAt:new Date().toISOString(),playerCount:state.players.length,players:state.players.map(p=>({id:p.id,name:p.name,color:p.color,control:p.control,aiStrategy:p.botStrategy})),initialDirection:state.history.initialDirection,initialFirstPlayerId:state.history.initialFirstPlayerId,winnerId:state.winnerId,totalRounds:state.round,finalFollowerTotals:finalFollowers,finalTempleFollowerTotals:finalTempleFollowers,priestsCreated:Object.fromEntries(state.players.map(p=>[p.id,p.priestsCreated])),finalNeutralCount:countNeutralsInPlay(state)},events:state.history.events}}
export function playByPlayFilename(state:GameState){const date=state.history.startedAt.slice(0,10),seed=state.seed.replace(/[^a-z0-9_-]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,48)||'game';return`worship-me-playbyplay-${date}-seed-${seed}.json`}
