import {adjacent,edgeKey,findCell,traversable} from './board.ts';import type {EdgePlacement,GameState,PlacementAction,TilePlacement} from './types.ts';
const player=(s:GameState,id:string)=>s.players.find(p=>p.id===id)!;
function opponentPriest(s:GameState,cellId:string,playerId:string){const c=findCell(s.board,cellId),color=player(s,playerId).color;return c.priests.some(x=>x!==color)}
function incidentEdgeClaims(s:GameState,cellId:string){return Object.entries(s.edgeClaims).filter(([key])=>key.split('|').includes(cellId)).map(([,v])=>v)}
export function validatePlacement(s:GameState,a:PlacementAction){
 if(s.phase!=='placement')throw Error('Placements are only legal during Placement Phase');if(a.playerId!==s.turnOrder[s.currentPlayerIndex])throw Error('It is not this player’s placement turn');
 const used=s.placementsUsed[a.playerId]??0,bonus=s.extraBlessThisRound[a.playerId]??0,max=2+bonus;if(used>=max)throw Error('No placements remain');if(a.kind==='smite'&&s.smiteUsed[a.playerId])throw Error('Smite placement already used');if(used>=2&&a.kind!=='bless')throw Error('Bonus placement must be Bless');
 if(a.type==='placeTile')validateTile(s,a);else validateEdge(s,a);
}
function validateTile(s:GameState,a:TilePlacement){const c=findCell(s.board,a.cellId);if(a.kind==='smite'&&c.visibleKind==='hidden')throw Error('Face-down land can only be targeted by Bless Tile');if(s.tileClaims[c.id])throw Error('Tile already targeted this round');if(c.visibleKind==='temple'&&s.templesTargeted.includes(c.id))throw Error('Temple already targeted this round');if(opponentPriest(s,c.id,a.playerId))throw Error('Opponent Priest protects this tile');if(incidentEdgeClaims(s,c.id).some(x=>x.playerId!==a.playerId&&x.kind==='smite'))throw Error('Opponent Smite Edge protects this endpoint')}
function endpoints(a:EdgePlacement):[string,string]{return a.kind==='bless'?[a.from,a.to]:[a.a,a.b]}
function validateEdge(s:GameState,a:EdgePlacement){const [first,second]=endpoints(a),x=findCell(s.board,first),y=findCell(s.board,second);if(!adjacent(x,y)||!traversable(x)||!traversable(y))throw Error('Edge must connect adjacent revealed tiles');const key=edgeKey(first,second);if(s.edgeClaims[key])throw Error('Edge already targeted this round');for(const c of [x,y]){if(opponentPriest(s,c.id,a.playerId))throw Error('Opponent Priest protects this edge');const claim=s.tileClaims[c.id];if(claim&&claim.playerId!==a.playerId)throw Error('Opponent tile claim protects this edge')}}
export function placementUnavailableReason(s:GameState,a:PlacementAction){try{validatePlacement(s,a);return''}catch(e){return(e as Error).message}}
export function claimPlacement(s:GameState,a:PlacementAction){const marker={playerId:a.playerId,kind:a.kind};if(a.type==='placeTile'){s.tileClaims[a.cellId]=marker;const c=findCell(s.board,a.cellId);if(c.visibleKind==='temple')s.templesTargeted.push(c.id)}else{const [first,second]=endpoints(a);s.edgeClaims[edgeKey(first,second)]=marker;if(a.kind==='smite')s.edgeMarkers.push({a:a.a,b:a.b,playerId:a.playerId,kind:'smite'})}}
