import {createHash} from 'node:crypto';
import {mkdirSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {createGame} from '../src/games/worship-me/engine/setup';
import {applyAction,resolvePendingDecision} from '../src/games/worship-me/engine/reducer';
import {getLegalActions} from '../src/games/worship-me/engine/legalActions';
import {placementUnavailableReason} from '../src/games/worship-me/engine/placementLegality';
import {adjacent,traversable} from '../src/games/worship-me/engine/board';
import {checkVictory,followersInOwnTemple,followerTotal} from '../src/games/worship-me/engine/victory';
import {countNeutralsInPlay} from '../src/games/worship-me/engine/neutrals';
import {occupancy} from '../src/games/worship-me/engine/priests';
import {blessEdgeOptions} from '../src/games/worship-me/engine/resolution';
import {getPolicy} from '../src/games/worship-me/ai/policies';
import {scoreActionDetailed,scoreResolutionOption,scoreSmiteResourceChoice,weights} from '../src/games/worship-me/ai/scoring';
import {describeBotAction} from '../src/games/worship-me/ai/simulate';
import type {BotStrategy,Cell,GameAction,GameState,MoveResolutionOption,PlacementAction,Player} from '../src/games/worship-me/engine/types';

const seed='five-test-2p-batch-0',outputDir='validation-results-2p-stall-audit',milestones=new Set([50,75,100,125,150]);
mkdirSync(outputDir,{recursive:true});

const stable=(value:unknown):string=>value===null||typeof value!=='object'?JSON.stringify(value):Array.isArray(value)?`[${value.map(stable).join(',')}]`:`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(',')}}`;
const hash=(value:unknown)=>createHash('sha256').update(stable(value)).digest('hex').slice(0,16);
const cellState=(c:Cell)=>({id:c.id,visibleKind:c.visibleKind,hiddenKind:c.hiddenKind,villagers:[...c.villagers].sort(),priests:[...c.priests].sort(),wheat:c.wheat,bread:c.bread,modifier:c.tileModifier});
function signatureData(s:GameState,includeRng=false){return{players:s.players.map(p=>({id:p.id,priestsCreated:p.priestsCreated})),board:s.board.map(cellState),bag:[...s.newVillagerBag].sort(),removed:[...s.removedVillageTiles].sort(),turnOrder:s.turnOrder,current:s.currentPlayerIndex,direction:s.direction,phase:s.phase,queue:s.actionQueue,pending:s.pendingResolution,placementsUsed:s.placementsUsed,smiteUsed:s.smiteUsed,extra:s.extraBlessThisRound,nextExtra:s.extraBlessNextRound,penalty:s.placementPenaltyThisRound,nextPenalty:s.nextRoundPlacementPenalty,first:s.persistentFirstPlayerId,flip:s.pendingDirectionFlip,claims:{tile:s.tileClaims,edge:s.edgeClaims,temples:s.templesTargeted},...(includeRng?{rngState:s.rngState}:{})}}
const sig=(s:GameState,includeRng=false)=>hash(signatureData(s,includeRng));
const boardSig=(s:GameState)=>hash({board:s.board.map(cellState),bag:[...s.newVillagerBag].sort(),direction:s.direction,first:s.persistentFirstPlayerId,nextPenalty:s.nextRoundPlacementPenalty,nextExtra:s.extraBlessNextRound});
const templeFollowers=(s:GameState,p:Player)=>followersInOwnTemple(s,p);
const locations=(s:GameState,color:string)=>s.board.filter(c=>c.villagers.includes(color as never)||c.priests.includes(color as never)).map(c=>({cell:c.id,ordinary:c.villagers.filter(v=>v===color).length,priests:c.priests.filter(v=>v===color).length}));
function concise(s:GameState){const victory=checkVictory(s),bagCounts=Object.fromEntries(['red','purple','blue','cyan','green','yellow','orange','black','neutral'].map(color=>[color,s.newVillagerBag.filter(v=>v===color).length]).filter(([,count])=>count));return{round:s.round,phase:s.phase,activePlayer:s.turnOrder[s.currentPlayerIndex],followers:Object.fromEntries(s.players.map(p=>[p.id,followerTotal(s,p)])),templeFollowers:Object.fromEntries(s.players.map(p=>[p.id,templeFollowers(s,p)])),priests:Object.fromEntries(s.players.map(p=>[p.id,{created:p.priestsCreated,locations:s.board.filter(c=>c.priests.includes(p.color)).map(c=>c.id)}])),neutralCount:countNeutralsInPlay(s),neutralLocations:s.board.filter(c=>c.villagers.includes('neutral')).map(c=>({cell:c.id,count:c.villagers.filter(v=>v==='neutral').length})),newVillagerBag:bagCounts,resources:{wheat:s.board.reduce((n,c)=>n+c.wheat,0),bread:s.board.reduce((n,c)=>n+c.bread,0),locations:s.board.filter(c=>c.wheat||c.bread).map(c=>({cell:c.id,type:c.visibleKind,wheat:c.wheat,bread:c.bread}))},victory:{allVillageTilesRevealed:victory.allVillageTilesRevealed,triggeringPlayerIds:victory.triggeringPlayerIds,gameEnds:victory.gameEnds,winnerId:victory.winnerId},gameplaySignature:sig(s),decisionSignature:sig(s,true),boardSignature:boardSig(s)}}
function actionLabel(a:GameAction){return describeBotAction(a)}
function rawPlacementAudit(s:GameState){const id=s.turnOrder[s.currentPlayerIndex],raw:PlacementAction[]=[];for(const c of s.board)for(const kind of ['bless','smite'] as const)raw.push({type:'placeTile',cellId:c.id,kind,playerId:id});for(let i=0;i<s.board.length;i++)for(let j=i+1;j<s.board.length;j++){const a=s.board[i],b=s.board[j];if(adjacent(a,b)&&traversable(a)&&traversable(b))raw.push({type:'placeEdge',from:a.id,to:b.id,kind:'bless',playerId:id},{type:'placeEdge',from:b.id,to:a.id,kind:'bless',playerId:id},{type:'placeEdge',a:a.id,b:b.id,kind:'smite',playerId:id})}const rejected=raw.map(action=>({action,reason:placementUnavailableReason(s,action)})).filter(x=>x.reason),reasonCounts:Record<string,number>={};for(const x of rejected)reasonCounts[x.reason]=(reasonCounts[x.reason]??0)+1;return{rejectedCount:rejected.length,reasonCounts,examples:rejected.slice(0,20).map(x=>({action:actionLabel(x.action),reason:x.reason}))}}
function legalAuditFor(s:GameState,p:Player){const copy=structuredClone(s);copy.phase='placement';copy.currentPlayerIndex=copy.turnOrder.indexOf(p.id);copy.placementsUsed[p.id]=0;copy.smiteUsed[p.id]=false;const actions=getLegalActions(copy),edges=actions.filter((a):a is Extract<PlacementAction,{type:'placeEdge';kind:'bless'}>=>a.type==='placeEdge'&&a.kind==='bless'),options=edges.flatMap(a=>blessEdgeOptions(copy,a));return{legalActions:actions.length,actionsThatCanChangeFollowerCount:edges.filter(a=>blessEdgeOptions(copy,a).some(o=>o.neutral||o.opponent)).length,actionsThatCanChangeTempleProgress:edges.filter(a=>blessEdgeOptions(copy,a).some(o=>o.moverColor===p.color&&o.to===p.templeCellId)).length,legalInfluenceOrConversionActions:edges.filter(a=>blessEdgeOptions(copy,a).some(o=>o.neutral||o.opponent)).length,resolutionOptions:{total:options.length,neutral:options.filter(o=>o.neutral).length,opponent:options.filter(o=>o.opponent).length,resourceOnly:options.filter(o=>o.resourceOnly).length}}}
function milestoneSnapshot(s:GameState){return{...concise(s),players:s.players.map(p=>({id:p.id,strategy:p.botStrategy,followers:followerTotal(s,p),templeFollowers:templeFollowers(s,p),resourcesOnTilesWithPresence:s.board.filter(c=>c.villagers.includes(p.color)||c.priests.includes(p.color)).reduce((x,c)=>({wheat:x.wheat+c.wheat,bread:x.bread+c.bread}),{wheat:0,bread:0}),villagerDistribution:locations(s,p.color),legal:legalAuditFor(s,p)})),homes:s.board.filter(c=>c.visibleKind==='home').map(c=>({cell:c.id,occupancy:occupancy(c),villagers:c.villagers,priests:c.priests,wheat:c.wheat,bread:c.bread})),allVillagers:s.board.filter(c=>c.villagers.length||c.priests.length).map(c=>({cell:c.id,villagers:c.villagers,priests:c.priests})),allResources:s.board.filter(c=>c.wheat||c.bread).map(c=>({cell:c.id,type:c.visibleKind,wheat:c.wheat,bread:c.bread}))}}

type LateRecord={round:number;kind:'placement'|'resolution';playerId:string;strategy:BotStrategy;chosen:string;selectedScore:number;legalCandidates:Array<{label:string;score:number;components:unknown}>;illegal?:unknown;before:ReturnType<typeof concise>;after?:ReturnType<typeof concise>;meaningful?:boolean;selectionReason:string};
const late:LateRecord[]=[],roundStarts:Array<{round:number;gameplaySignature:string;boardSignature:string;neutralCount:number;followers:Record<string,number>;templeFollowers:Record<string,number>}>=[],snapshots:Record<string,unknown>={},actionClasses:Record<string,Record<string,number>>={},movementOutcomes:Array<{round:number;playerId:string;option:MoveResolutionOption;before:ReturnType<typeof concise>;after:ReturnType<typeof concise>;score:number}>=[];
const exactOccurrences=new Map<string,number[]>(),boardOccurrences=new Map<string,number[]>();
function remember(map:Map<string,number[]>,key:string,round:number){const arr=map.get(key)??[];arr.push(round);map.set(key,arr)}
function addClass(playerId:string,kind:string){actionClasses[playerId]??={};actionClasses[playerId][kind]=(actionClasses[playerId][kind]??0)+1}
function classify(before:ReturnType<typeof concise>,after:ReturnType<typeof concise>,option?:MoveResolutionOption){const player=Object.keys(before.templeFollowers).find(id=>before.templeFollowers[id]!==after.templeFollowers[id]);if(player&&after.templeFollowers[player]>before.templeFollowers[player])return'increases victory progress';if(player&&after.templeFollowers[player]<before.templeFollowers[player])return'decreases victory progress';if(option?.resourceOnly)return'resource-only action';if(before.boardSignature===after.boardSignature)return'functionally redundant/no meaningful change';return'changes board state but leaves victory progress unchanged'}

let state=createGame([{name:'Player 1 Balanced AI',control:'ai',botStrategy:'balanced'},{name:'Player 2 Growth AI',control:'ai',botStrategy:'growth'}],seed),totalActions=0,lastRound=0;
while(state.phase!=='gameOver'&&state.round<=150&&totalActions<5000){
 if(state.round!==lastRound){lastRound=state.round;const r={round:state.round,gameplaySignature:sig(state),boardSignature:boardSig(state),neutralCount:countNeutralsInPlay(state),followers:Object.fromEntries(state.players.map(p=>[p.id,followerTotal(state,p)])),templeFollowers:Object.fromEntries(state.players.map(p=>[p.id,templeFollowers(state,p)]))};roundStarts.push(r);remember(exactOccurrences,r.gameplaySignature,state.round);remember(boardOccurrences,r.boardSignature,state.round);if(milestones.has(state.round))snapshots[String(state.round)]=milestoneSnapshot(state)}
 if(state.phase==='resolution'&&state.pendingResolution){const pending=state.pendingResolution,p=state.players.find(x=>x.id===pending.playerId)!,strategy=p.botStrategy!,policy=getPolicy(strategy),before=concise(state),choice=policy.choosePendingResolution(state),w=weights[strategy as Exclude<BotStrategy,'random'>],candidates=pending.type==='blessEdgeMove'?pending.options.map((o,index)=>({index,label:`${o.resourceOnly?'Resource only':o.neutral?'Influence Neutral':o.opponent?`Move opponent ${o.moverColor}`:`Move ${o.moverRole??''} ${o.moverColor??''}`}${o.resource?` + ${o.resource}`:''} ${o.from} → ${o.to}`,...scoreResolutionOption(state,p.id,o,w)})).sort((a,b)=>b.score-a.score):pending.options.map((resource,index)=>({index,label:`Remove ${resource}`,...scoreSmiteResourceChoice(state,pending.cellId,resource,w)})).sort((a,b)=>b.score-a.score),decision=choice.decision,selectedIndex=decision.type==='resolveBlessEdge'?decision.optionIndex:pending.options.indexOf(decision.resource),selected=candidates.find(x=>x.index===selectedIndex)!;const next=resolvePendingDecision({...state,rngState:choice.rngState},choice.decision,{aiResolution:choice.diagnostics}),after=concise(next),option=pending.type==='blessEdgeMove'?pending.options[selectedIndex] as MoveResolutionOption:undefined;if(state.round>=50){late.push({round:state.round,kind:'resolution',playerId:p.id,strategy,chosen:selected.label,selectedScore:selected.score,legalCandidates:candidates.map(x=>({label:x.label,score:x.score,components:x.components})),before,after,meaningful:before.boardSignature!==after.boardSignature,selectionReason:'highest strategy score; seeded tie-break among equal maxima'});const category=classify(before,after,option);addClass(p.id,category);if(option)movementOutcomes.push({round:state.round,playerId:p.id,option,before,after,score:selected.score})}state=next;continue}
 if(state.phase!=='placement')throw Error(`Unexpected engine pause in ${state.phase}`);
 const p=state.players.find(x=>x.id===state.turnOrder[state.currentPlayerIndex])!,strategy=p.botStrategy!,legal=getLegalActions(state),w=weights[strategy as Exclude<BotStrategy,'random'>],scored=legal.map(action=>({action,label:actionLabel(action),...scoreActionDetailed(state,action,w)})).sort((a,b)=>b.score-a.score||a.label.localeCompare(b.label)),choice=getPolicy(strategy).chooseAction(state,legal),selected=scored.find(x=>stable(x.action)===stable(choice.action))!,before=concise(state),illegal=rawPlacementAudit(state),next=applyAction({...state,rngState:choice.rngState},choice.action,{aiDecision:choice.diagnostics}),after=concise(next);if(choice.action.type!=='endTurn')totalActions++;if(state.round>=50)late.push({round:state.round,kind:'placement',playerId:p.id,strategy,chosen:selected.label,selectedScore:selected.score,legalCandidates:scored.map(x=>({label:x.label,score:x.score,components:x.components})),illegal,before,after,meaningful:before.gameplaySignature!==after.gameplaySignature,selectionReason:choice.action.type==='endTurn'?'end-turn candidate selected by strategy':'highest strategy score; seeded tie-break among equal maxima'});state=next;
}
if(!snapshots['150']&&state.round>=150)snapshots['150']=milestoneSnapshot(state);

const cycles=(map:Map<string,number[]>)=>[...map.entries()].filter(([,rounds])=>rounds.length>1).map(([signature,rounds])=>({signature,rounds,intervals:rounds.slice(1).map((r,i)=>r-rounds[i])})).sort((a,b)=>b.rounds.length-a.rounds.length);
const exactCycles=cycles(exactOccurrences),equivalentCycles=cycles(boardOccurrences);
const movementKey=(m:typeof movementOutcomes[number])=>`${m.playerId}:${m.option.from}->${m.option.to}:${m.option.moverColor??'none'}:${m.option.resource??'none'}:${m.option.resourceOnly?'resource':'pawn'}`;
const movementPatterns=Object.entries(movementOutcomes.reduce<Record<string,number>>((out,m)=>{const k=movementKey(m);out[k]=(out[k]??0)+1;return out},{})).sort((a,b)=>b[1]-a[1]);
let wheatProduced=0,breadProduced=0,wheatSpent=0,breadSpent=0,births=0;const birthsByRound:Record<string,number>={};for(const e of state.history.events)if(e.type==='production'){const before=e.data.before as {wheat:number;bread:number},after=e.data.after as {wheat:number;bread:number},tile=e.data.tileType;if(tile==='farm')wheatProduced+=Math.max(0,after.wheat-before.wheat);if(tile==='bakery'){breadProduced+=Math.max(0,after.bread-before.bread);wheatSpent+=Math.max(0,before.wheat-after.wheat)}if(tile==='home'){breadSpent+=Math.max(0,before.bread-after.bread);if(e.data.homeEligibility===true){births++;birthsByRound[String(e.round)]=(birthsByRound[String(e.round)]??0)+1}}}
const maxTemple=Object.fromEntries(state.players.map(p=>[p.id,Math.max(0,...state.history.events.filter(e=>e.type==='victoryCheck').map(e=>(e.data.players as Array<{playerId:string;templeFollowers:number}>).find(x=>x.playerId===p.id)?.templeFollowers??0))]));
const roundProgress=state.history.events.filter(e=>e.type==='victoryCheck').map(e=>({round:e.round,temple:Object.fromEntries((e.data.players as Array<{playerId:string;templeFollowers:number}>).map(x=>[x.playerId,x.templeFollowers])),followers:e.data.followerTotals}));
let firstNonProgressRound=50;for(let r=50;r<=150;r++){const future=roundProgress.filter(x=>x.round>=r),progressValues=future.map(x=>stable({temple:x.temple,followers:x.followers}));if(new Set(progressValues).size===1){firstNonProgressRound=r;break}}
const placementClassification=late.filter(r=>r.kind==='placement').reduce<Record<string,Record<string,Record<string,number>>>>((out,r)=>{out[r.playerId]??={};const type=r.chosen.split(' ').slice(0,2).join(' ');out[r.playerId][type]??={};out[r.playerId][type]['changes board state but leaves victory progress unchanged']=(out[r.playerId][type]['changes board state but leaves victory progress unchanged']??0)+1;return out},{}),firstNeutralCapRound=roundStarts.find(r=>r.neutralCount>=10)?.round,final=concise(state),summary={seed,strategies:Object.fromEntries(state.players.map(p=>[p.id,p.botStrategy])),stalled:state.phase!=='gameOver',finalRound:state.round,totalActions,winnerId:state.winnerId,firstNonProgressRound,cycleDetection:{exactGameplayCycles:exactCycles.slice(0,20),gameplayEquivalentBoardCycles:equivalentCycles.slice(0,20),exactCycleDetected:exactCycles.length>0,equivalentCycleDetected:equivalentCycles.length>0},actionClassificationTotals:actionClasses,placementActionTotalsByType:placementClassification,commonMovementPatterns:movementPatterns.slice(0,30),maximumVictoryProgress:maxTemple,resourceTotals:{wheatProduced,breadProduced,wheatSpent,breadSpent,births,birthsByRound,finalResources:final.resources,finalNewVillagerBag:final.newVillagerBag},neutralFinding:{final:final.neutralCount,firstCapRound:firstNeutralCapRound,capReached:final.neutralCount===10,capRejectedActions:late.reduce((n,r)=>n+((JSON.stringify(r.illegal??{}).match(/global-neutral-cap/g)?.length)??0),0)},finalState:final,suspectedCauseClassifications:['AI scoring/priority issue','population/occupancy deadlock','resource-routing deadlock','strategic equilibrium with no terminal pressure']};
const artifact={format:'worship-me-2p-stall-audit',generatedAt:new Date().toISOString(),summary,progressSnapshots:snapshots,roundStartSignatures:roundStarts,lateGameDecisionRecords:late,movementOutcomes,roundProgress,fullPlayByPlay:state.history};
writeFileSync(join(outputDir,`enhanced-play-by-play-seed-${seed}.json`),JSON.stringify(artifact,null,2));
writeFileSync(join(outputDir,'stall-summary.json'),JSON.stringify(summary,null,2));
console.log(JSON.stringify(summary,null,2));
