import './styles.css';import './layout.css';import './setup.css';
import {applyAction,createGame,deserializeGame,exportPlayByPlay,getLegalActions,playByPlayFilename,remainingPlacements,resolvePendingDecision,serializeGame,type BotStrategy,type GameAction,type GameState,type PlacementKind,type PlayerSetup,type ResolutionDecision} from './games/worship-me/engine';import {getPolicy} from './games/worship-me/ai/policies';import {renderBoard} from './games/worship-me/ui/renderBoard';import {renderSidebar} from './games/worship-me/ui/renderSidebar';import {renderLog} from './games/worship-me/ui/renderLog';import {renderRules} from './games/worship-me/ui/renderRules';
const root=document.querySelector<HTMLDivElement>('#app')!;
let state:GameState,mode:''|'blessTile'|'blessEdge'|'smiteTile'|'smiteEdge'='',firstEdgeCell:string|undefined,secondEdgeCell:string|undefined,botDelay=400,botTimer=0;
const cap=(x:string)=>x[0].toUpperCase()+x.slice(1);
function clear(){mode='';firstEdgeCell=undefined;secondEdgeCell=undefined}
function currentDecisionPlayer(){const id=state.pendingResolution?.playerId??state.turnOrder[state.currentPlayerIndex];return state.players.find(p=>p.id===id)}
function currentBot(){const p=currentDecisionPlayer();return p?.control==='ai'?p:undefined}
function showSetup(){clearTimeout(botTimer);root.innerHTML=`<section class="game-setup"><h1>New Worship Me! Game</h1><label>Players <select data-count>${Array.from({length:7},(_,i)=>`<option>${i+2}</option>`).join('')}</select></label><label>Seed <input data-seed value="${Date.now()}"></label><div data-players></div><button data-start>Start Game</button></section>`;const count=root.querySelector<HTMLSelectElement>('[data-count]')!,holder=root.querySelector<HTMLElement>('[data-players]')!;const rows=()=>holder.innerHTML=Array.from({length:+count.value},(_,i)=>`<label>Player ${i+1}<select data-control><option value="human">Human</option><option value="balanced">Balanced AI</option><option value="growth">Growth AI</option><option value="templeRush">Temple Rush AI</option><option value="random">Random AI</option></select></label>`).join('');count.onchange=rows;rows();root.querySelector<HTMLButtonElement>('[data-start]')!.onclick=()=>{const specs:PlayerSetup[]=[...root.querySelectorAll<HTMLSelectElement>('[data-control]')].map((x,i)=>({name:`Player ${i+1}${x.value==='human'?'':` ${cap(x.value)} AI`}`,control:x.value==='human'?'human':'ai',botStrategy:x.value==='human'?undefined:x.value as BotStrategy}));state=createGame(specs,root.querySelector<HTMLInputElement>('[data-seed]')!.value);draw()}}
function newGame(){showSetup()}
function scheduleBot(){clearTimeout(botTimer);if(currentBot()&&state.phase!=='gameOver')botTimer=window.setTimeout(botStep,botDelay)}
function botStep(){const player=currentBot();if(!player)return;try{const policy=getPolicy(player.botStrategy??'random');if(state.pendingResolution){const choice=policy.choosePendingResolution(state),copy={...state,rngState:choice.rngState};state=resolvePendingDecision(copy,choice.decision,{aiResolution:choice.diagnostics})}else{const choice=policy.chooseAction(state,getLegalActions(state)),copy={...state,rngState:choice.rngState};state=applyAction(copy,choice.action,{aiDecision:choice.diagnostics})}clear();draw()}catch(e){state.eventLog.push(`AI error: ${(e as Error).message}`);draw()}}
function selection(){return mode.endsWith('Edge')?{start:firstEdgeCell,end:secondEdgeCell}:mode?{start:undefined}:undefined}
function draw(){root.innerHTML=`<main>${renderRules()}<section class="center-gameplay">${actionBar()}${renderBoard(state,selection())}</section>${renderSidebar(state,currentBot()?.id)}${renderLog(state)}</main>`;root.querySelectorAll<HTMLElement>('[data-cell]').forEach(x=>x.onclick=()=>cellClick(x.dataset.cell!));bind();scheduleBot()}
function actionBar(){if(state.phase==='gameOver')return`<section class="action-panel"><h3>Game over</h3></section>`;if(state.pendingResolution){const p=state.pendingResolution;if(p.type==='blessEdgeMove')return`<section class="action-panel"><h3>Resolve Bless Edge</h3><label>Movement <select data-choice>${p.options.map((o,i)=>`<option value="${i}">${o.from} → ${o.to}${o.moverRole?` · ${o.moverRole}`:''}${o.resource?` + ${o.resource}`:''}${o.resourceOnly?' only':''}</option>`).join('')}</select></label><button data-resolve>Confirm</button></section>`;return`<section class="action-panel"><h3>Resolve Smite Tile</h3>${p.options.map(r=>`<button data-resource="${r}">Remove 1 ${cap(r)}</button>`).join('')}</section>`}if(state.phase==='resolution')return`<section class="action-panel"><h3>Resolving queue ${state.resolutionIndex+1}/${state.actionQueue.length}</h3></section>`;const p=currentDecisionPlayer()!,used=state.placementsUsed[p.id]??0,limit=used+remainingPlacements(state,p.id);return`<section class="action-panel"><h3>Placement Phase · ${p.name} · ${used+1}/${limit}</h3><p>Remaining: ${limit-used} · Smite ${state.smiteUsed[p.id]?'used':'available'}</p><div class="placement-buttons"><button data-mode="blessTile">Bless Tile</button><button data-mode="blessEdge">Bless Edge</button><button data-mode="smiteTile" ${state.smiteUsed[p.id]?'disabled':''}>Smite Tile</button><button data-mode="smiteEdge" ${state.smiteUsed[p.id]?'disabled':''}>Smite Edge</button></div><p>${mode?mode.endsWith('Edge')?(firstEdgeCell?(secondEdgeCell?`${mode==='blessEdge'?'Origin → Destination':'Edge'}: ${firstEdgeCell} ${mode==='blessEdge'?'→':'–'} ${secondEdgeCell}. Confirm placement.`:`Select the destination adjacent to origin ${firstEdgeCell}.`):'Select the origin tile.'):`Select a tile for ${cap(mode)}.`:'Choose a placement. Bless Edge direction is fixed by selecting origin, then destination; pawn and cargo are chosen during resolution.'}</p><button data-confirm-edge ${secondEdgeCell?'':'hidden'}>Confirm Edge</button><button data-cancel ${mode?'':'hidden'}>Cancel selection</button></section>`}
function cellClick(id:string){if(currentBot()||state.phase!=='placement'||!mode)return;if(mode.endsWith('Tile'))return commit({type:'placeTile',cellId:id,kind:mode.startsWith('bless')?'bless':'smite',playerId:currentDecisionPlayer()!.id});if(!firstEdgeCell){firstEdgeCell=id;draw()}else{secondEdgeCell=id;draw()}}
function commit(action:GameAction){try{state=applyAction(state,action);clear();draw()}catch(e){alert((e as Error).message)}}
function downloadJson(value:unknown,name:string){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
function bind(){root.querySelectorAll<HTMLElement>('[data-mode]').forEach(x=>x.onclick=()=>{mode=x.dataset.mode as typeof mode;firstEdgeCell=undefined;secondEdgeCell=undefined;draw()});const confirmEdge=root.querySelector<HTMLElement>('[data-confirm-edge]');if(confirmEdge)confirmEdge.onclick=()=>{const playerId=currentDecisionPlayer()!.id;if(!firstEdgeCell||!secondEdgeCell)return;commit(mode==='blessEdge'?{type:'placeEdge',from:firstEdgeCell,to:secondEdgeCell,kind:'bless',playerId}:{type:'placeEdge',a:firstEdgeCell,b:secondEdgeCell,kind:'smite',playerId})};const cancel=root.querySelector<HTMLElement>('[data-cancel]');if(cancel)cancel.onclick=()=>{clear();draw()};const resolve=root.querySelector<HTMLElement>('[data-resolve]');if(resolve)resolve.onclick=()=>{const p=state.pendingResolution!,decision:ResolutionDecision={type:'resolveBlessEdge',playerId:p.playerId,optionIndex:+root.querySelector<HTMLSelectElement>('[data-choice]')!.value};state=resolvePendingDecision(state,decision);clear();draw()};root.querySelectorAll<HTMLElement>('[data-resource]').forEach(x=>x.onclick=()=>{const p=state.pendingResolution!;state=resolvePendingDecision(state,{type:'resolveSmiteResource',playerId:p.playerId,resource:x.dataset.resource as 'wheat'|'bread'});clear();draw()});const q=(n:string)=>root.querySelector<HTMLElement>(`[data-command="${n}"]`);q('end-turn')!.onclick=()=>commit({type:'endTurn',playerId:currentDecisionPlayer()!.id});q('save')!.onclick=()=>localStorage.setItem('worship-me-save',serializeGame(state));q('resume')!.onclick=()=>{const x=localStorage.getItem('worship-me-save');if(x){state=deserializeGame(x);clear();draw()}};q('export')!.onclick=()=>downloadJson(state,'worship-me-schema-v9-save.json');q('export-playbyplay')!.onclick=()=>downloadJson(exportPlayByPlay(state),playByPlayFilename(state));root.querySelector<HTMLInputElement>('[data-command="import"]')!.onchange=async e=>{const f=(e.target as HTMLInputElement).files?.[0];if(f){state=deserializeGame(await f.text());draw()}};q('new')!.onclick=newGame;q('bot-delay')!.onclick=()=>{botDelay=botDelay?0:400;draw()}}
newGame();
