-- Forward-only repair for PostgreSQL's SQL-special COALESCE expression in Start Game.
-- The applied M11 and ambiguity-repair migrations remain immutable.

create or replace function public.start_game_server(p_room_code text,p_user_id uuid,p_expected_players jsonb,p_game_state jsonb)
returns table(room_id uuid,room_code text,room_status text,state_version bigint)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_game_id uuid;v_host_user_id uuid;v_room_status text;v_game_status text;v_min_players smallint;v_max_players smallint;v_player_count integer;v_human_count integer;v_roster jsonb;v_existing_state jsonb;v_state_version bigint;
begin
 if p_user_id is null then raise exception using errcode='22023',message='User is required';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' or pg_catalog.jsonb_typeof(p_expected_players)is distinct from 'array' or pg_catalog.jsonb_typeof(p_game_state)is distinct from 'object' then raise exception using errcode='22023',message='Invalid Start request';end if;
 select r.id,r.code,r.game_id,r.host_user_id,r.status into v_room_id,v_room_code,v_game_id,v_host_user_id,v_room_status from public.rooms r where r.code=v_room_code for update of r;if v_room_id is null or not exists(select 1 from public.room_players m where m.room_id=v_room_id and m.user_id=p_user_id)then raise exception using errcode='P0002',message='Room not found or unavailable';end if;if v_host_user_id<>p_user_id then raise exception using errcode='P0003',message='Only the host can start the game';end if;if v_room_status<>'lobby' then raise exception using errcode='P0005',message='Game has already started';end if;select g.status,g.min_players,g.max_players into v_game_status,v_min_players,v_max_players from public.games g where g.id=v_game_id;if v_game_status is distinct from 'active' then raise exception using errcode='P0004',message='Lobby is not ready';end if;
 select pg_catalog.count(*)::integer into v_human_count from public.room_players rp where rp.room_id=v_room_id;
 select pg_catalog.jsonb_agg(participant order by participant_group,participant_order)into v_roster from(
  select 0 participant_group,pg_catalog.row_number()over(order by rp.joined_at,rp.user_id)participant_order,pg_catalog.jsonb_build_object('control','human','userId',rp.user_id::text,'displayName',rp.display_name,'playerColor',rp.player_color)participant from public.room_players rp where rp.room_id=v_room_id
  union all
  select 1,ai.bot_number,pg_catalog.jsonb_build_object('control','ai','aiPlayerId',ai.id::text,'displayName','AI '||ai.bot_number::text,'playerColor',ai.player_color,'botStrategy',ai.bot_strategy)from public.room_ai_players ai where ai.room_id=v_room_id
 )occupied;v_player_count:=coalesce(pg_catalog.jsonb_array_length(v_roster),0);
 if v_player_count<v_min_players or v_player_count>v_max_players or exists(select 1 from public.room_players rp where rp.room_id=v_room_id and(not rp.is_ready or rp.player_color is null or rp.turn_order is not null))or exists(select 1 from public.room_ai_players ai where ai.room_id=v_room_id and(ai.turn_order is not null or ai.bot_strategy not in('random','growth','templeRush','balanced')))or exists(select 1 from(select rp.player_color from public.room_players rp where rp.room_id=v_room_id union all select ai.player_color from public.room_ai_players ai where ai.room_id=v_room_id)c where c.player_color is null or not exists(select 1 from public.game_player_colors supported where supported.game_id=v_game_id and supported.color=c.player_color))or(select pg_catalog.count(distinct c.player_color)from(select rp.player_color from public.room_players rp where rp.room_id=v_room_id union all select ai.player_color from public.room_ai_players ai where ai.room_id=v_room_id)c)<>v_player_count then raise exception using errcode='P0004',message='Lobby is not ready';end if;if v_roster is distinct from p_expected_players then raise exception using errcode='P0006',message='Lobby roster changed';end if;
 select rs.game_state,rs.state_version into v_existing_state,v_state_version from public.room_states rs where rs.room_id=v_room_id for update of rs;if not found then raise exception using errcode='P0004',message='Lobby is not ready';end if;if v_existing_state is not null or v_state_version<>0 then raise exception using errcode='P0005',message='Game has already started';end if;
 if p_game_state->'schemaVersion' is distinct from '9'::jsonb or pg_catalog.jsonb_typeof(p_game_state->'players')is distinct from 'array' or pg_catalog.jsonb_array_length(p_game_state->'players')<>v_player_count or pg_catalog.jsonb_typeof(p_game_state->'turnOrder')is distinct from 'array' or pg_catalog.jsonb_array_length(p_game_state->'turnOrder')<>v_player_count or p_game_state->>'phase' is distinct from 'placement' or p_game_state->'round' is distinct from '1'::jsonb or pg_catalog.jsonb_typeof(p_game_state->'currentPlayerIndex')is distinct from 'number' or(p_game_state->>'currentPlayerIndex')!~'^\d+$' or(p_game_state->>'currentPlayerIndex')::integer not between 0 and v_player_count-1 or nullif(pg_catalog.btrim(p_game_state->>'seed'),'')is null or exists(select 1 from pg_catalog.generate_series(0,v_player_count-1)ordinal(index)where pg_catalog.jsonb_typeof(p_expected_players->index)is distinct from 'object' or pg_catalog.jsonb_typeof(p_game_state->'players'->index)is distinct from 'object' or p_game_state->'players'->index->>'id' is distinct from 'p'||(index+1)::text or p_game_state->'players'->index->>'name' is distinct from p_expected_players->index->>'displayName' or p_game_state->'players'->index->>'color' is distinct from p_expected_players->index->>'playerColor' or p_game_state->'players'->index->>'control' is distinct from p_expected_players->index->>'control' or p_game_state->'turnOrder'->>index is distinct from 'p'||(index+1)::text or(p_expected_players->index->>'control'='ai' and p_game_state->'players'->index->>'botStrategy' is distinct from p_expected_players->index->>'botStrategy')or(p_expected_players->index->>'control'='human' and p_game_state->'players'->index?'botStrategy' and p_game_state->'players'->index->'botStrategy'<>'null'::jsonb))then raise exception using errcode='22023',message='Invalid candidate game state';end if;
 with ordered as(select rp.user_id,(pg_catalog.row_number()over(order by rp.joined_at,rp.user_id)-1)::smallint position from public.room_players rp where rp.room_id=v_room_id)update public.room_players rp set turn_order=ordered.position from ordered where rp.room_id=v_room_id and rp.user_id=ordered.user_id;
 update public.room_ai_players ai set turn_order=(v_human_count+ordered.position-1)::smallint from(select source.id,pg_catalog.row_number()over(order by source.bot_number)position from public.room_ai_players source where source.room_id=v_room_id)ordered where ai.room_id=v_room_id and ai.id=ordered.id;
 update public.room_states rs set game_state=p_game_state,state_version=1 where rs.room_id=v_room_id and rs.game_state is null and rs.state_version=0;update public.rooms r set status='active' where r.id=v_room_id and r.status='lobby';return query select v_room_id,v_room_code,'active'::text,1::bigint;
end;$$;

revoke execute on function public.start_game_server(text,uuid,jsonb,jsonb) from public, anon, authenticated, service_role;
grant execute on function public.start_game_server(text,uuid,jsonb,jsonb) to service_role;

