-- Server-authoritative AI lobby participants are not Auth users and do not
-- receive room_players memberships.
create table public.room_ai_players (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  bot_number smallint not null,
  player_color text not null,
  bot_strategy text not null default 'balanced',
  turn_order smallint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint room_ai_players_bot_number_range check (bot_number between 1 and 8),
  constraint room_ai_players_strategy check (bot_strategy in ('random','growth','templeRush','balanced')),
  constraint room_ai_players_color_format check (char_length(player_color) between 1 and 40 and player_color = btrim(player_color) and player_color ~ '^[a-z][a-z0-9-]*$'),
  constraint room_ai_players_turn_order_range check (turn_order is null or turn_order between 0 and 63),
  unique (room_id, bot_number)
);
create unique index room_ai_players_room_color_uidx on public.room_ai_players(room_id, player_color) where player_color is not null;
create unique index room_ai_players_room_turn_order_uidx on public.room_ai_players(room_id, turn_order) where turn_order is not null;
create trigger room_ai_players_set_updated_at before update on public.room_ai_players for each row execute function ngsllc_private.set_updated_at();
alter table public.room_ai_players enable row level security;
revoke all on table public.room_ai_players from public, anon, authenticated, service_role;
grant select on table public.room_ai_players to authenticated;
grant select, insert, update, delete on table public.room_ai_players to service_role;
create policy room_ai_players_authenticated_read_own_rooms on public.room_ai_players for select to authenticated using (ngsllc_private.is_room_member(room_id));

create function public.add_room_ai_player_server(p_room_code text,p_user_id uuid)
returns table(room_code text,ai_player_id uuid,bot_number smallint,player_color text,bot_strategy text)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_game_id uuid;v_host uuid;v_status text;v_max_players smallint;v_count bigint;v_bot_number smallint;v_color text;v_ai_id uuid;
begin
 if p_user_id is null then raise exception using errcode='22023',message='Invalid AI player request';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' then raise exception using errcode='22023',message='Invalid AI player request';end if;
 select r.id,r.game_id,r.host_user_id,r.status,g.max_players into v_room_id,v_game_id,v_host,v_status,v_max_players from public.rooms r join public.games g on g.id=r.game_id and g.status='active' and g.slug='worship-me' where r.code=v_room_code for update of r;if not found or not exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.user_id=p_user_id)then raise exception using errcode='P0002',message='Room not found or unavailable';end if;if v_host<>p_user_id then raise exception using errcode='P0003',message='Only the host can manage AI players';end if;if v_status<>'lobby' then raise exception using errcode='P0004',message='Lobby is unavailable';end if;
 select(select pg_catalog.count(*)from public.room_players where room_id=v_room_id)+(select pg_catalog.count(*)from public.room_ai_players where room_id=v_room_id)into v_count;if v_count>=v_max_players then raise exception using errcode='P0005',message='Room is full';end if;
 select candidates.candidate into v_bot_number from pg_catalog.generate_series(1,8)as candidates(candidate) where not exists(select 1 from public.room_ai_players ai where ai.room_id=v_room_id and ai.bot_number=candidates.candidate)order by candidates.candidate limit 1;
 select c.color into v_color from public.game_player_colors c where c.game_id=v_game_id and not exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.player_color=c.color)and not exists(select 1 from public.room_ai_players ai where ai.room_id=v_room_id and ai.player_color=c.color)order by c.sort_order limit 1;
 if v_bot_number is null or v_color is null then raise exception using errcode='P0005',message='AI player is unavailable';end if;insert into public.room_ai_players(room_id,bot_number,player_color,bot_strategy)values(v_room_id,v_bot_number,v_color,'balanced')returning id into v_ai_id;return query select v_room_code,v_ai_id,v_bot_number,v_color,'balanced'::text;
end;$$;

create or replace function public.start_game_server(p_room_code text,p_user_id uuid,p_expected_players jsonb,p_game_state jsonb)
returns table(room_id uuid,room_code text,room_status text,state_version bigint)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_game_id uuid;v_host_user_id uuid;v_room_status text;v_game_status text;v_min_players smallint;v_max_players smallint;v_player_count integer;v_human_count integer;v_roster jsonb;v_existing_state jsonb;v_state_version bigint;
begin
 if p_user_id is null then raise exception using errcode='22023',message='User is required';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' or pg_catalog.jsonb_typeof(p_expected_players)is distinct from 'array' or pg_catalog.jsonb_typeof(p_game_state)is distinct from 'object' then raise exception using errcode='22023',message='Invalid Start request';end if;
 select r.id,r.code,r.game_id,r.host_user_id,r.status into v_room_id,v_room_code,v_game_id,v_host_user_id,v_room_status from public.rooms r where r.code=v_room_code for update of r;if v_room_id is null or not exists(select 1 from public.room_players m where m.room_id=v_room_id and m.user_id=p_user_id)then raise exception using errcode='P0002',message='Room not found or unavailable';end if;if v_host_user_id<>p_user_id then raise exception using errcode='P0003',message='Only the host can start the game';end if;if v_room_status<>'lobby' then raise exception using errcode='P0005',message='Game has already started';end if;select g.status,g.min_players,g.max_players into v_game_status,v_min_players,v_max_players from public.games g where g.id=v_game_id;if v_game_status is distinct from 'active' then raise exception using errcode='P0004',message='Lobby is not ready';end if;
 select pg_catalog.count(*)::integer into v_human_count from public.room_players where room_id=v_room_id;
 select pg_catalog.jsonb_agg(participant order by participant_group,participant_order)into v_roster from(
  select 0 participant_group,pg_catalog.row_number()over(order by rp.joined_at,rp.user_id)participant_order,pg_catalog.jsonb_build_object('control','human','userId',rp.user_id::text,'displayName',rp.display_name,'playerColor',rp.player_color)participant from public.room_players rp where rp.room_id=v_room_id
  union all
  select 1,ai.bot_number,pg_catalog.jsonb_build_object('control','ai','aiPlayerId',ai.id::text,'displayName','AI '||ai.bot_number::text,'playerColor',ai.player_color,'botStrategy',ai.bot_strategy)from public.room_ai_players ai where ai.room_id=v_room_id
 )occupied;v_player_count:=pg_catalog.coalesce(pg_catalog.jsonb_array_length(v_roster),0);
 if v_player_count<v_min_players or v_player_count>v_max_players or exists(select 1 from public.room_players where room_id=v_room_id and(not is_ready or player_color is null or turn_order is not null))or exists(select 1 from public.room_ai_players where room_id=v_room_id and(turn_order is not null or bot_strategy not in('random','growth','templeRush','balanced')))or exists(select 1 from(select player_color from public.room_players where room_id=v_room_id union all select player_color from public.room_ai_players where room_id=v_room_id)c where c.player_color is null or not exists(select 1 from public.game_player_colors supported where supported.game_id=v_game_id and supported.color=c.player_color))or(select pg_catalog.count(distinct c.player_color)from(select player_color from public.room_players where room_id=v_room_id union all select player_color from public.room_ai_players where room_id=v_room_id)c)<>v_player_count then raise exception using errcode='P0004',message='Lobby is not ready';end if;if v_roster is distinct from p_expected_players then raise exception using errcode='P0006',message='Lobby roster changed';end if;
 select rs.game_state,rs.state_version into v_existing_state,v_state_version from public.room_states rs where rs.room_id=v_room_id for update of rs;if not found then raise exception using errcode='P0004',message='Lobby is not ready';end if;if v_existing_state is not null or v_state_version<>0 then raise exception using errcode='P0005',message='Game has already started';end if;
 if p_game_state->'schemaVersion' is distinct from '9'::jsonb or pg_catalog.jsonb_typeof(p_game_state->'players')is distinct from 'array' or pg_catalog.jsonb_array_length(p_game_state->'players')<>v_player_count or pg_catalog.jsonb_typeof(p_game_state->'turnOrder')is distinct from 'array' or pg_catalog.jsonb_array_length(p_game_state->'turnOrder')<>v_player_count or p_game_state->>'phase' is distinct from 'placement' or p_game_state->'round' is distinct from '1'::jsonb or pg_catalog.jsonb_typeof(p_game_state->'currentPlayerIndex')is distinct from 'number' or(p_game_state->>'currentPlayerIndex')!~'^\d+$' or(p_game_state->>'currentPlayerIndex')::integer not between 0 and v_player_count-1 or nullif(pg_catalog.btrim(p_game_state->>'seed'),'')is null or exists(select 1 from pg_catalog.generate_series(0,v_player_count-1)ordinal(index)where pg_catalog.jsonb_typeof(p_expected_players->index)is distinct from 'object' or pg_catalog.jsonb_typeof(p_game_state->'players'->index)is distinct from 'object' or p_game_state->'players'->index->>'id' is distinct from 'p'||(index+1)::text or p_game_state->'players'->index->>'name' is distinct from p_expected_players->index->>'displayName' or p_game_state->'players'->index->>'color' is distinct from p_expected_players->index->>'playerColor' or p_game_state->'players'->index->>'control' is distinct from p_expected_players->index->>'control' or p_game_state->'turnOrder'->>index is distinct from 'p'||(index+1)::text or(p_expected_players->index->>'control'='ai' and p_game_state->'players'->index->>'botStrategy' is distinct from p_expected_players->index->>'botStrategy')or(p_expected_players->index->>'control'='human' and p_game_state->'players'->index?'botStrategy' and p_game_state->'players'->index->'botStrategy'<>'null'::jsonb))then raise exception using errcode='22023',message='Invalid candidate game state';end if;
 with ordered as(select rp.user_id,(pg_catalog.row_number()over(order by rp.joined_at,rp.user_id)-1)::smallint position from public.room_players rp where rp.room_id=v_room_id)update public.room_players rp set turn_order=ordered.position from ordered where rp.room_id=v_room_id and rp.user_id=ordered.user_id;
 update public.room_ai_players ai set turn_order=(v_human_count+ordered.position-1)::smallint from(select id,pg_catalog.row_number()over(order by bot_number)position from public.room_ai_players where room_id=v_room_id)ordered where ai.room_id=v_room_id and ai.id=ordered.id;
 update public.room_states set game_state=p_game_state,state_version=1 where room_id=v_room_id and game_state is null and state_version=0;update public.rooms set status='active' where id=v_room_id and status='lobby';return query select v_room_id,v_room_code,'active'::text,1::bigint;
end;$$;

-- Human commits preserve AI strategy as part of immutable player identity.
create or replace function public.commit_game_action_server(p_room_code text,p_user_id uuid,p_expected_state_version bigint,p_next_game_state jsonb)
returns table(room_code text,room_status text,state_version bigint,viewer_turn_order smallint)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_room_status text;v_member_user_id uuid;v_viewer_turn_order smallint;v_viewer_player_id text;v_state_version bigint;v_game_state jsonb;v_current_player_index integer;v_player_count integer;v_existing_round integer;v_candidate_round integer;v_index integer;v_updated integer;
begin
 if p_user_id is null or p_expected_state_version is null or p_expected_state_version<1 then raise exception using errcode='22023',message='Invalid game action request';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' or pg_catalog.jsonb_typeof(p_next_game_state)is distinct from 'object' then raise exception using errcode='22023',message='Invalid game action request';end if;
 select r.id,r.status,rp.user_id,rp.turn_order into v_room_id,v_room_status,v_member_user_id,v_viewer_turn_order from public.rooms r left join public.room_players rp on rp.room_id=r.id and rp.user_id=p_user_id where r.code=v_room_code for update of r;if not found or v_member_user_id is null then raise exception using errcode='P0002',message='Room not found or unavailable';end if;if v_room_status is distinct from 'active' then raise exception using errcode='P0004',message='Game is not active';end if;if v_viewer_turn_order is null or v_viewer_turn_order<0 then raise exception using errcode='P0005',message='Game state is unavailable';end if;v_viewer_player_id:='p'||(v_viewer_turn_order+1)::text;
 select rs.state_version,rs.game_state into v_state_version,v_game_state from public.room_states rs where rs.room_id=v_room_id for update;if not found or v_state_version<1 or pg_catalog.jsonb_typeof(v_game_state)is distinct from 'object' then raise exception using errcode='P0005',message='Game state is unavailable';end if;if v_state_version is distinct from p_expected_state_version then raise exception using errcode='P0006',message='Game state changed';end if;
 if v_game_state->'schemaVersion' is distinct from '9'::jsonb or pg_catalog.jsonb_typeof(v_game_state->'players')is distinct from 'array' or pg_catalog.jsonb_typeof(v_game_state->'turnOrder')is distinct from 'array' or pg_catalog.jsonb_typeof(v_game_state->'board')is distinct from 'array' or pg_catalog.jsonb_typeof(v_game_state->'currentPlayerIndex')is distinct from 'number' or(v_game_state->>'currentPlayerIndex')!~'^\d+$' then raise exception using errcode='P0005',message='Game state is unavailable';end if;v_player_count:=pg_catalog.jsonb_array_length(v_game_state->'players');v_current_player_index:=(v_game_state->>'currentPlayerIndex')::integer;if v_player_count not between 2 and 8 or pg_catalog.jsonb_array_length(v_game_state->'turnOrder')<>v_player_count or v_current_player_index not between 0 and v_player_count-1 or v_viewer_turn_order>=v_player_count then raise exception using errcode='P0005',message='Game state is unavailable';end if;
 if v_game_state->'turnOrder'->>v_current_player_index is distinct from v_viewer_player_id or v_game_state->'players'->v_viewer_turn_order->>'control' is distinct from 'human' or(v_game_state?'pendingResolution' and v_game_state->'pendingResolution' is not null and v_game_state->'pendingResolution'<>'null'::jsonb and v_game_state->'pendingResolution'->>'playerId' is distinct from v_viewer_player_id)then raise exception using errcode='P0003',message='Not the active player';end if;
 if p_next_game_state->'schemaVersion' is distinct from '9'::jsonb or p_next_game_state->'seed' is distinct from v_game_state->'seed' or p_next_game_state->'config' is distinct from v_game_state->'config' or p_next_game_state->'turnOrder' is distinct from v_game_state->'turnOrder' or p_next_game_state->'removedVillageTiles' is distinct from v_game_state->'removedVillageTiles' or pg_catalog.jsonb_typeof(p_next_game_state->'players')is distinct from 'array' or pg_catalog.jsonb_array_length(p_next_game_state->'players')<>v_player_count or pg_catalog.jsonb_typeof(p_next_game_state->'board')is distinct from 'array' or pg_catalog.jsonb_array_length(p_next_game_state->'board')<>25 or pg_catalog.jsonb_array_length(v_game_state->'board')<>25 or pg_catalog.jsonb_typeof(p_next_game_state->'round')is distinct from 'number' or(p_next_game_state->>'round')!~'^\d+$' or pg_catalog.jsonb_typeof(v_game_state->'round')is distinct from 'number' or(v_game_state->>'round')!~'^\d+$' then raise exception using errcode='22023',message='Invalid candidate game state';end if;v_existing_round:=(v_game_state->>'round')::integer;v_candidate_round:=(p_next_game_state->>'round')::integer;if v_candidate_round<v_existing_round or v_candidate_round>v_existing_round+1 then raise exception using errcode='22023',message='Invalid candidate game state';end if;
 for v_index in 0..v_player_count-1 loop if pg_catalog.jsonb_typeof(p_next_game_state->'players'->v_index)is distinct from 'object' or p_next_game_state->'players'->v_index->'id' is distinct from v_game_state->'players'->v_index->'id' or p_next_game_state->'players'->v_index->'name' is distinct from v_game_state->'players'->v_index->'name' or p_next_game_state->'players'->v_index->'color' is distinct from v_game_state->'players'->v_index->'color' or p_next_game_state->'players'->v_index->'templeCellId' is distinct from v_game_state->'players'->v_index->'templeCellId' or p_next_game_state->'players'->v_index->'control' is distinct from v_game_state->'players'->v_index->'control' or p_next_game_state->'players'->v_index->'botStrategy' is distinct from v_game_state->'players'->v_index->'botStrategy' then raise exception using errcode='22023',message='Invalid candidate game state';end if;end loop;
 for v_index in 0..24 loop if pg_catalog.jsonb_typeof(p_next_game_state->'board'->v_index)is distinct from 'object' or p_next_game_state->'board'->v_index->'id' is distinct from v_game_state->'board'->v_index->'id' or p_next_game_state->'board'->v_index->'row' is distinct from v_game_state->'board'->v_index->'row' or p_next_game_state->'board'->v_index->'col' is distinct from v_game_state->'board'->v_index->'col' or p_next_game_state->'board'->v_index->'hiddenKind' is distinct from v_game_state->'board'->v_index->'hiddenKind' or p_next_game_state->'board'->v_index->'templeOwnerId' is distinct from v_game_state->'board'->v_index->'templeOwnerId' then raise exception using errcode='22023',message='Invalid candidate game state';end if;end loop;
 update public.room_states rs set game_state=p_next_game_state,state_version=rs.state_version+1,updated_at=pg_catalog.now()where rs.room_id=v_room_id and rs.state_version=p_expected_state_version;get diagnostics v_updated=row_count;if v_updated<>1 then raise exception using errcode='P0006',message='Game state changed';end if;return query select v_room_code,v_room_status,v_state_version+1,v_viewer_turn_order;
end;$$;

create function public.commit_ai_action_server(p_room_code text,p_user_id uuid,p_expected_state_version bigint,p_expected_ai_player_id text,p_next_game_state jsonb)
returns table(room_code text,room_status text,state_version bigint,viewer_turn_order smallint)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_status text;v_viewer_turn_order smallint;v_version bigint;v_state jsonb;v_count integer;v_index integer;v_round integer;v_next_round integer;v_current text;v_updated integer;
begin
 if p_user_id is null or p_expected_state_version is null or p_expected_state_version<1 or p_expected_ai_player_id is null or p_expected_ai_player_id!~'^p[1-8]$' or pg_catalog.jsonb_typeof(p_next_game_state)is distinct from 'object' then raise exception using errcode='22023',message='Invalid AI action request';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' then raise exception using errcode='22023',message='Invalid AI action request';end if;
 select r.id,r.status,rp.turn_order into v_room_id,v_status,v_viewer_turn_order from public.rooms r join public.room_players rp on rp.room_id=r.id and rp.user_id=p_user_id where r.code=v_room_code for update of r;if not found then raise exception using errcode='P0002',message='Room not found or unavailable';end if;if v_status<>'active' then raise exception using errcode='P0004',message='Game is not active';end if;
 select rs.state_version,rs.game_state into v_version,v_state from public.room_states rs where rs.room_id=v_room_id for update;if not found or v_version<1 or pg_catalog.jsonb_typeof(v_state)is distinct from 'object' then raise exception using errcode='P0005',message='Game state is unavailable';end if;if v_version<>p_expected_state_version then raise exception using errcode='P0006',message='Game state changed';end if;
 if v_state->'schemaVersion' is distinct from '9'::jsonb or pg_catalog.jsonb_typeof(v_state->'players')is distinct from 'array' or pg_catalog.jsonb_typeof(v_state->'turnOrder')is distinct from 'array' or pg_catalog.jsonb_typeof(v_state->'board')is distinct from 'array' or pg_catalog.jsonb_typeof(v_state->'currentPlayerIndex')is distinct from 'number' or(v_state->>'currentPlayerIndex')!~'^\d+$' then raise exception using errcode='P0005',message='Game state is unavailable';end if;v_count:=pg_catalog.jsonb_array_length(v_state->'players');if v_count not between 2 and 8 or pg_catalog.jsonb_array_length(v_state->'turnOrder')<>v_count or(v_state->>'currentPlayerIndex')::integer not between 0 and v_count-1 then raise exception using errcode='P0005',message='Game state is unavailable';end if;v_current:=v_state->'turnOrder'->>((v_state->>'currentPlayerIndex')::integer);
 if v_current is distinct from p_expected_ai_player_id or v_state->'players'->((pg_catalog.substring(p_expected_ai_player_id from 2))::integer-1)->>'control' is distinct from 'ai' or v_state->'players'->((pg_catalog.substring(p_expected_ai_player_id from 2))::integer-1)->>'botStrategy' is null or v_state->'players'->((pg_catalog.substring(p_expected_ai_player_id from 2))::integer-1)->>'botStrategy' not in('random','growth','templeRush','balanced')or(v_state?'pendingResolution' and v_state->'pendingResolution' is not null and v_state->'pendingResolution'<>'null'::jsonb and v_state->'pendingResolution'->>'playerId' is distinct from p_expected_ai_player_id)then raise exception using errcode='P0003',message='AI is not active';end if;
 if p_next_game_state->'schemaVersion' is distinct from '9'::jsonb or p_next_game_state->'seed' is distinct from v_state->'seed' or p_next_game_state->'config' is distinct from v_state->'config' or p_next_game_state->'turnOrder' is distinct from v_state->'turnOrder' or p_next_game_state->'removedVillageTiles' is distinct from v_state->'removedVillageTiles' or pg_catalog.jsonb_typeof(p_next_game_state->'players')is distinct from 'array' or pg_catalog.jsonb_array_length(p_next_game_state->'players')<>v_count or pg_catalog.jsonb_typeof(p_next_game_state->'board')is distinct from 'array' or pg_catalog.jsonb_array_length(p_next_game_state->'board')<>25 or pg_catalog.jsonb_array_length(v_state->'board')<>25 or pg_catalog.jsonb_typeof(p_next_game_state->'round')is distinct from 'number' or(p_next_game_state->>'round')!~'^\d+$' or pg_catalog.jsonb_typeof(v_state->'round')is distinct from 'number' or(v_state->>'round')!~'^\d+$' then raise exception using errcode='22023',message='Invalid candidate game state';end if;v_round:=(v_state->>'round')::integer;v_next_round:=(p_next_game_state->>'round')::integer;if v_next_round<v_round or v_next_round>v_round+1 then raise exception using errcode='22023',message='Invalid candidate game state';end if;
 for v_index in 0..v_count-1 loop if pg_catalog.jsonb_typeof(p_next_game_state->'players'->v_index)is distinct from 'object' or p_next_game_state->'players'->v_index->'id' is distinct from v_state->'players'->v_index->'id' or p_next_game_state->'players'->v_index->'name' is distinct from v_state->'players'->v_index->'name' or p_next_game_state->'players'->v_index->'color' is distinct from v_state->'players'->v_index->'color' or p_next_game_state->'players'->v_index->'templeCellId' is distinct from v_state->'players'->v_index->'templeCellId' or p_next_game_state->'players'->v_index->'control' is distinct from v_state->'players'->v_index->'control' or p_next_game_state->'players'->v_index->'botStrategy' is distinct from v_state->'players'->v_index->'botStrategy' then raise exception using errcode='22023',message='Invalid candidate game state';end if;end loop;
 for v_index in 0..24 loop if pg_catalog.jsonb_typeof(p_next_game_state->'board'->v_index)is distinct from 'object' or p_next_game_state->'board'->v_index->'id' is distinct from v_state->'board'->v_index->'id' or p_next_game_state->'board'->v_index->'row' is distinct from v_state->'board'->v_index->'row' or p_next_game_state->'board'->v_index->'col' is distinct from v_state->'board'->v_index->'col' or p_next_game_state->'board'->v_index->'hiddenKind' is distinct from v_state->'board'->v_index->'hiddenKind' or p_next_game_state->'board'->v_index->'templeOwnerId' is distinct from v_state->'board'->v_index->'templeOwnerId' then raise exception using errcode='22023',message='Invalid candidate game state';end if;end loop;
 update public.room_states rs set game_state=p_next_game_state,state_version=rs.state_version+1,updated_at=pg_catalog.now()where rs.room_id=v_room_id and rs.state_version=p_expected_state_version;get diagnostics v_updated=row_count;if v_updated<>1 then raise exception using errcode='P0006',message='Game state changed';end if;return query select v_room_code,v_status,v_version+1,v_viewer_turn_order;
end;$$;

create or replace function ngsllc_private.bump_room_lobby_update()
returns trigger language plpgsql security definer set search_path='' as $$
declare v_room_id uuid;v_meaningful boolean:=true;
begin
 if tg_table_name='room_players' then
  if tg_op='DELETE' then v_room_id:=old.room_id;else v_room_id:=new.room_id;if tg_op='UPDATE' then v_meaningful:=new.display_name is distinct from old.display_name or new.player_color is distinct from old.player_color or new.is_ready is distinct from old.is_ready;end if;end if;
 elsif tg_table_name='room_ai_players' then
  if tg_op='DELETE' then v_room_id:=old.room_id;else v_room_id:=new.room_id;if tg_op='UPDATE' then v_meaningful:=new.player_color is distinct from old.player_color or new.bot_strategy is distinct from old.bot_strategy;end if;end if;
 elsif tg_table_name='rooms' then v_room_id:=new.id;v_meaningful:=new.host_user_id is distinct from old.host_user_id or new.status is distinct from old.status;
 end if;
 if v_meaningful then update public.room_lobby_updates signal set lobby_version=signal.lobby_version+1,updated_at=pg_catalog.now()where signal.room_id=v_room_id;end if;if tg_op='DELETE' then return old;end if;return new;
end;$$;
create trigger room_ai_players_bump_lobby_update after insert or delete or update of player_color,bot_strategy,turn_order on public.room_ai_players for each row execute function ngsllc_private.bump_room_lobby_update();

create function public.remove_room_ai_player_server(p_room_code text,p_user_id uuid,p_ai_player_id uuid)
returns table(room_code text,ai_player_id uuid,removed boolean)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_host uuid;v_status text;v_deleted uuid;
begin
 if p_user_id is null or p_ai_player_id is null then raise exception using errcode='22023',message='Invalid AI player request';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' then raise exception using errcode='22023',message='Invalid AI player request';end if;
 select r.id,r.host_user_id,r.status into v_room_id,v_host,v_status from public.rooms r join public.games g on g.id=r.game_id and g.status='active' and g.slug='worship-me' where r.code=v_room_code for update of r;if not found or not exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.user_id=p_user_id)then raise exception using errcode='P0002',message='Room not found or unavailable';end if;if v_host<>p_user_id then raise exception using errcode='P0003',message='Only the host can manage AI players';end if;if v_status<>'lobby' then raise exception using errcode='P0004',message='Lobby is unavailable';end if;
 delete from public.room_ai_players where room_id=v_room_id and id=p_ai_player_id returning id into v_deleted;if v_deleted is null then raise exception using errcode='P0002',message='AI player not found';end if;return query select v_room_code,v_deleted,true;
end;$$;

create function public.set_room_ai_player_color_server(p_room_code text,p_user_id uuid,p_ai_player_id uuid,p_player_color text)
returns table(room_code text,ai_player_id uuid,player_color text,changed boolean)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_game_id uuid;v_host uuid;v_status text;v_color text;v_current text;
begin
 if p_user_id is null or p_ai_player_id is null then raise exception using errcode='22023',message='Invalid AI player request';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));v_color:=pg_catalog.btrim(p_player_color);if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' or v_color is null or v_color<>p_player_color or pg_catalog.char_length(v_color)not between 1 and 40 or v_color!~'^[a-z][a-z0-9-]*$' then raise exception using errcode='22023',message='Invalid AI player request';end if;
 select r.id,r.game_id,r.host_user_id,r.status into v_room_id,v_game_id,v_host,v_status from public.rooms r join public.games g on g.id=r.game_id and g.status='active' and g.slug='worship-me' where r.code=v_room_code for update of r;if not found or not exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.user_id=p_user_id)then raise exception using errcode='P0002',message='Room not found or unavailable';end if;if v_host<>p_user_id then raise exception using errcode='P0003',message='Only the host can manage AI players';end if;if v_status<>'lobby' then raise exception using errcode='P0004',message='Lobby is unavailable';end if;
 select ai.player_color into v_current from public.room_ai_players ai where ai.room_id=v_room_id and ai.id=p_ai_player_id;if not found then raise exception using errcode='P0002',message='AI player not found';end if;if v_current=v_color then return query select v_room_code,p_ai_player_id,v_current,false;return;end if;
 if not exists(select 1 from public.game_player_colors c where c.game_id=v_game_id and c.color=v_color)or exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.player_color=v_color)or exists(select 1 from public.room_ai_players ai where ai.room_id=v_room_id and ai.id<>p_ai_player_id and ai.player_color=v_color)then raise exception using errcode='P0006',message='Player color unavailable';end if;
 begin update public.room_ai_players set player_color=v_color where room_id=v_room_id and id=p_ai_player_id;exception when unique_violation then raise exception using errcode='P0006',message='Player color unavailable';end;return query select v_room_code,p_ai_player_id,v_color,true;
end;$$;

create function public.set_room_ai_player_strategy_server(p_room_code text,p_user_id uuid,p_ai_player_id uuid,p_bot_strategy text)
returns table(room_code text,ai_player_id uuid,bot_strategy text,changed boolean)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_host uuid;v_status text;v_current text;
begin
 if p_user_id is null or p_ai_player_id is null or p_bot_strategy is null or p_bot_strategy not in('random','growth','templeRush','balanced')then raise exception using errcode='22023',message='Invalid AI player request';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' then raise exception using errcode='22023',message='Invalid AI player request';end if;
 select r.id,r.host_user_id,r.status into v_room_id,v_host,v_status from public.rooms r join public.games g on g.id=r.game_id and g.status='active' and g.slug='worship-me' where r.code=v_room_code for update of r;if not found or not exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.user_id=p_user_id)then raise exception using errcode='P0002',message='Room not found or unavailable';end if;if v_host<>p_user_id then raise exception using errcode='P0003',message='Only the host can manage AI players';end if;if v_status<>'lobby' then raise exception using errcode='P0004',message='Lobby is unavailable';end if;
 select ai.bot_strategy into v_current from public.room_ai_players ai where ai.room_id=v_room_id and ai.id=p_ai_player_id;if not found then raise exception using errcode='P0002',message='AI player not found';end if;if v_current=p_bot_strategy then return query select v_room_code,p_ai_player_id,v_current,false;return;end if;update public.room_ai_players set bot_strategy=p_bot_strategy where room_id=v_room_id and id=p_ai_player_id;return query select v_room_code,p_ai_player_id,p_bot_strategy,true;
end;$$;

create or replace function public.join_room_server(p_room_code text,p_user_id uuid,p_display_name text)
returns table(room_id uuid,room_code text,game_id uuid,status text,joined_new boolean)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_game_id uuid;v_status text;v_display_name text;v_max_players smallint;v_player_count bigint;v_ai_count bigint;v_lock_room_id uuid;v_is_target_member boolean;v_old_lobby_ids uuid[]:=array[]::uuid[];v_lock_room_ids uuid[]:=array[]::uuid[];
begin
 if p_user_id is null then raise exception using errcode='22023',message='User is required';end if;v_display_name:=pg_catalog.btrim(p_display_name);if v_display_name is null or pg_catalog.char_length(v_display_name)not between 1 and 50 then raise exception using errcode='22023',message='Invalid display name';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' then raise exception using errcode='22023',message='Invalid room code';end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_user_id::text,2010003::bigint));select coalesce(pg_catalog.array_agg(existing.room_id order by existing.room_id),array[]::uuid[])into v_old_lobby_ids from(select distinct r.id room_id from public.rooms r join public.room_players rp on rp.room_id=r.id where rp.user_id=p_user_id and r.status='lobby')existing;select r.id into v_room_id from public.rooms r where r.code=v_room_code;select coalesce(pg_catalog.array_agg(affected.room_id order by affected.room_id),array[]::uuid[])into v_lock_room_ids from(select old_room_id room_id from pg_catalog.unnest(v_old_lobby_ids)old_rooms(old_room_id)union select v_room_id where v_room_id is not null)affected;foreach v_lock_room_id in array v_lock_room_ids loop perform 1 from public.rooms r where r.id=v_lock_room_id for update;end loop;
 select r.id,r.code,r.game_id,r.status,g.max_players into v_room_id,v_room_code,v_game_id,v_status,v_max_players from public.rooms r join public.games g on g.id=r.game_id and g.status='active' where r.id=v_room_id;if v_room_id is null or v_status<>'lobby' then raise exception using errcode='P0002',message='Room not found or unavailable';end if;select exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.user_id=p_user_id)into v_is_target_member;
 if not v_is_target_member then select pg_catalog.count(*)into v_player_count from public.room_players where room_id=v_room_id;select pg_catalog.count(*)into v_ai_count from public.room_ai_players where room_id=v_room_id;if v_player_count+v_ai_count>=v_max_players then raise exception using errcode='P0003',message='Room is full';end if;end if;
 foreach v_lock_room_id in array v_old_lobby_ids loop if v_lock_room_id<>v_room_id then perform * from ngsllc_private.depart_lobby_member(v_lock_room_id,p_user_id);end if;end loop;if v_is_target_member then update public.room_players set display_name=v_display_name,last_seen_at=pg_catalog.now()where room_id=v_room_id and user_id=p_user_id;else insert into public.room_players(room_id,user_id,display_name,player_color,turn_order,is_ready)values(v_room_id,p_user_id,v_display_name,null,null,false);end if;return query select v_room_id,v_room_code,v_game_id,v_status,not v_is_target_member;
end;$$;

create or replace function public.set_player_color_server(p_room_code text,p_user_id uuid,p_player_color text)
returns table(room_id uuid,room_code text,player_color text,changed boolean)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_game_id uuid;v_room_status text;v_requested_color text;v_current_color text;v_member_found boolean;
begin
 if p_user_id is null then raise exception using errcode='22023',message='User is required';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' then raise exception using errcode='22023',message='Invalid room code';end if;if p_player_color is not null then v_requested_color:=pg_catalog.btrim(p_player_color);if v_requested_color<>p_player_color or pg_catalog.char_length(v_requested_color)not between 1 and 40 or v_requested_color!~'^[a-z][a-z0-9-]*$' then raise exception using errcode='22023',message='Invalid player color';end if;end if;
 select r.id,r.code,r.game_id,r.status into v_room_id,v_room_code,v_game_id,v_room_status from public.rooms r join public.games g on g.id=r.game_id and g.status='active' where r.code=v_room_code for update of r;if v_room_id is null or v_room_status<>'lobby' then raise exception using errcode='P0002',message='Room not found or unavailable';end if;select rp.player_color into v_current_color from public.room_players rp where rp.room_id=v_room_id and rp.user_id=p_user_id;v_member_found:=found;if not v_member_found then raise exception using errcode='P0002',message='Room not found or unavailable';end if;
 if v_requested_color is null then if v_current_color is null then return query select v_room_id,v_room_code,null::text,false;return;end if;update public.room_players set player_color=null,is_ready=false where room_id=v_room_id and user_id=p_user_id;return query select v_room_id,v_room_code,null::text,true;return;end if;if not exists(select 1 from public.game_player_colors where game_id=v_game_id and color=v_requested_color)then raise exception using errcode='22023',message='Invalid player color';end if;if v_current_color=v_requested_color then return query select v_room_id,v_room_code,v_current_color,false;return;end if;
 if exists(select 1 from public.room_players where room_id=v_room_id and user_id<>p_user_id and player_color=v_requested_color)or exists(select 1 from public.room_ai_players where room_id=v_room_id and player_color=v_requested_color)then raise exception using errcode='P0003',message='Player color unavailable';end if;begin update public.room_players set player_color=v_requested_color,is_ready=false where room_id=v_room_id and user_id=p_user_id;exception when unique_violation then raise exception using errcode='P0003',message='Player color unavailable';end;return query select v_room_id,v_room_code,v_requested_color,true;
end;$$;

revoke execute on function public.add_room_ai_player_server(text,uuid)from public,anon,authenticated,service_role;
revoke execute on function public.remove_room_ai_player_server(text,uuid,uuid)from public,anon,authenticated,service_role;
revoke execute on function public.set_room_ai_player_color_server(text,uuid,uuid,text)from public,anon,authenticated,service_role;
revoke execute on function public.set_room_ai_player_strategy_server(text,uuid,uuid,text)from public,anon,authenticated,service_role;
revoke execute on function public.join_room_server(text,uuid,text)from public,anon,authenticated,service_role;
revoke execute on function public.set_player_color_server(text,uuid,text)from public,anon,authenticated,service_role;
revoke execute on function public.start_game_server(text,uuid,jsonb,jsonb)from public,anon,authenticated,service_role;
revoke execute on function public.commit_game_action_server(text,uuid,bigint,jsonb)from public,anon,authenticated,service_role;
revoke execute on function public.commit_ai_action_server(text,uuid,bigint,text,jsonb)from public,anon,authenticated,service_role;
grant execute on function public.add_room_ai_player_server(text,uuid)to service_role;
grant execute on function public.remove_room_ai_player_server(text,uuid,uuid)to service_role;
grant execute on function public.set_room_ai_player_color_server(text,uuid,uuid,text)to service_role;
grant execute on function public.set_room_ai_player_strategy_server(text,uuid,uuid,text)to service_role;
grant execute on function public.join_room_server(text,uuid,text)to service_role;
grant execute on function public.set_player_color_server(text,uuid,text)to service_role;
grant execute on function public.start_game_server(text,uuid,jsonb,jsonb)to service_role;
grant execute on function public.commit_game_action_server(text,uuid,bigint,jsonb)to service_role;
grant execute on function public.commit_ai_action_server(text,uuid,bigint,text,jsonb)to service_role;
