-- Forward-only repair for PL/pgSQL column-name ambiguity in the applied M11 RPCs.
-- Function signatures and behavior are unchanged; only table-column qualification is corrected.

create or replace function public.add_room_ai_player_server(p_room_code text,p_user_id uuid)
returns table(room_code text,ai_player_id uuid,bot_number smallint,player_color text,bot_strategy text)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_game_id uuid;v_host uuid;v_status text;v_max_players smallint;v_count bigint;v_bot_number smallint;v_color text;v_ai_id uuid;
begin
 if p_user_id is null then raise exception using errcode='22023',message='Invalid AI player request';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' then raise exception using errcode='22023',message='Invalid AI player request';end if;
 select r.id,r.game_id,r.host_user_id,r.status,g.max_players into v_room_id,v_game_id,v_host,v_status,v_max_players from public.rooms r join public.games g on g.id=r.game_id and g.status='active' and g.slug='worship-me' where r.code=v_room_code for update of r;if not found or not exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.user_id=p_user_id)then raise exception using errcode='P0002',message='Room not found or unavailable';end if;if v_host<>p_user_id then raise exception using errcode='P0003',message='Only the host can manage AI players';end if;if v_status<>'lobby' then raise exception using errcode='P0004',message='Lobby is unavailable';end if;
 select(select pg_catalog.count(*)from public.room_players rp where rp.room_id=v_room_id)+(select pg_catalog.count(*)from public.room_ai_players ai where ai.room_id=v_room_id)into v_count;if v_count>=v_max_players then raise exception using errcode='P0005',message='Room is full';end if;
 select candidates.candidate into v_bot_number from pg_catalog.generate_series(1,8)as candidates(candidate) where not exists(select 1 from public.room_ai_players ai where ai.room_id=v_room_id and ai.bot_number=candidates.candidate)order by candidates.candidate limit 1;
 select c.color into v_color from public.game_player_colors c where c.game_id=v_game_id and not exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.player_color=c.color)and not exists(select 1 from public.room_ai_players ai where ai.room_id=v_room_id and ai.player_color=c.color)order by c.sort_order limit 1;
 if v_bot_number is null or v_color is null then raise exception using errcode='P0005',message='AI player is unavailable';end if;insert into public.room_ai_players(room_id,bot_number,player_color,bot_strategy)values(v_room_id,v_bot_number,v_color,'balanced')returning id into v_ai_id;return query select v_room_code,v_ai_id,v_bot_number,v_color,'balanced'::text;
end;$$;

create or replace function public.start_game_server(p_room_code text,p_user_id uuid,p_expected_players jsonb,p_game_state jsonb)
returns table(room_id uuid,room_code text,room_status text,state_version bigint)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_game_id uuid;v_host_user_id uuid;v_room_status text;v_game_status text;v_min_players smallint;v_max_players smallint;v_player_count integer;v_human_count integer;v_roster jsonb;v_existing_state jsonb;v_state_version bigint;
begin
 if p_user_id is null then raise exception using errcode='22023',message='User is required';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' or pg_catalog.jsonb_typeof(p_expected_players)is distinct from 'array' or pg_catalog.jsonb_typeof(p_game_state)is distinct from 'object' then raise exception using errcode='22023',message='Invalid Start request';end if;
 select r.id,r.code,r.game_id,r.host_user_id,r.status into v_room_id,v_room_code,v_game_id,v_host_user_id,v_room_status from public.rooms r where r.code=v_room_code for update of r;if v_room_id is null or not exists(select 1 from public.room_players m where m.room_id=v_room_id and m.user_id=p_user_id)then raise exception using errcode='P0002',message='Room not found or unavailable';end if;if v_host_user_id<>p_user_id then raise exception using errcode='P0003',message='Only the host can start the game';end if;if v_room_status<>'lobby' then raise exception using errcode='P0005',message='Game has already started';end if;select g.status,g.min_players,g.max_players into v_game_status,v_min_players,v_max_players from public.games g where g.id=v_game_id;if v_game_status is distinct from 'active' then raise exception using errcode='P0004',message='Lobby is not ready';end if;
 select pg_catalog.count(*)::integer into v_human_count from public.room_players rp where rp.room_id=v_room_id;
 select pg_catalog.jsonb_agg(participant order by participant_group,participant_order)into v_roster from(
  select 0 participant_group,pg_catalog.row_number()over(order by rp.joined_at,rp.user_id)participant_order,pg_catalog.jsonb_build_object('control','human','userId',rp.user_id::text,'displayName',rp.display_name,'playerColor',rp.player_color)participant from public.room_players rp where rp.room_id=v_room_id
  union all
  select 1,ai.bot_number,pg_catalog.jsonb_build_object('control','ai','aiPlayerId',ai.id::text,'displayName','AI '||ai.bot_number::text,'playerColor',ai.player_color,'botStrategy',ai.bot_strategy)from public.room_ai_players ai where ai.room_id=v_room_id
 )occupied;v_player_count:=pg_catalog.coalesce(pg_catalog.jsonb_array_length(v_roster),0);
 if v_player_count<v_min_players or v_player_count>v_max_players or exists(select 1 from public.room_players rp where rp.room_id=v_room_id and(not rp.is_ready or rp.player_color is null or rp.turn_order is not null))or exists(select 1 from public.room_ai_players ai where ai.room_id=v_room_id and(ai.turn_order is not null or ai.bot_strategy not in('random','growth','templeRush','balanced')))or exists(select 1 from(select rp.player_color from public.room_players rp where rp.room_id=v_room_id union all select ai.player_color from public.room_ai_players ai where ai.room_id=v_room_id)c where c.player_color is null or not exists(select 1 from public.game_player_colors supported where supported.game_id=v_game_id and supported.color=c.player_color))or(select pg_catalog.count(distinct c.player_color)from(select rp.player_color from public.room_players rp where rp.room_id=v_room_id union all select ai.player_color from public.room_ai_players ai where ai.room_id=v_room_id)c)<>v_player_count then raise exception using errcode='P0004',message='Lobby is not ready';end if;if v_roster is distinct from p_expected_players then raise exception using errcode='P0006',message='Lobby roster changed';end if;
 select rs.game_state,rs.state_version into v_existing_state,v_state_version from public.room_states rs where rs.room_id=v_room_id for update of rs;if not found then raise exception using errcode='P0004',message='Lobby is not ready';end if;if v_existing_state is not null or v_state_version<>0 then raise exception using errcode='P0005',message='Game has already started';end if;
 if p_game_state->'schemaVersion' is distinct from '9'::jsonb or pg_catalog.jsonb_typeof(p_game_state->'players')is distinct from 'array' or pg_catalog.jsonb_array_length(p_game_state->'players')<>v_player_count or pg_catalog.jsonb_typeof(p_game_state->'turnOrder')is distinct from 'array' or pg_catalog.jsonb_array_length(p_game_state->'turnOrder')<>v_player_count or p_game_state->>'phase' is distinct from 'placement' or p_game_state->'round' is distinct from '1'::jsonb or pg_catalog.jsonb_typeof(p_game_state->'currentPlayerIndex')is distinct from 'number' or(p_game_state->>'currentPlayerIndex')!~'^\d+$' or(p_game_state->>'currentPlayerIndex')::integer not between 0 and v_player_count-1 or nullif(pg_catalog.btrim(p_game_state->>'seed'),'')is null or exists(select 1 from pg_catalog.generate_series(0,v_player_count-1)ordinal(index)where pg_catalog.jsonb_typeof(p_expected_players->index)is distinct from 'object' or pg_catalog.jsonb_typeof(p_game_state->'players'->index)is distinct from 'object' or p_game_state->'players'->index->>'id' is distinct from 'p'||(index+1)::text or p_game_state->'players'->index->>'name' is distinct from p_expected_players->index->>'displayName' or p_game_state->'players'->index->>'color' is distinct from p_expected_players->index->>'playerColor' or p_game_state->'players'->index->>'control' is distinct from p_expected_players->index->>'control' or p_game_state->'turnOrder'->>index is distinct from 'p'||(index+1)::text or(p_expected_players->index->>'control'='ai' and p_game_state->'players'->index->>'botStrategy' is distinct from p_expected_players->index->>'botStrategy')or(p_expected_players->index->>'control'='human' and p_game_state->'players'->index?'botStrategy' and p_game_state->'players'->index->'botStrategy'<>'null'::jsonb))then raise exception using errcode='22023',message='Invalid candidate game state';end if;
 with ordered as(select rp.user_id,(pg_catalog.row_number()over(order by rp.joined_at,rp.user_id)-1)::smallint position from public.room_players rp where rp.room_id=v_room_id)update public.room_players rp set turn_order=ordered.position from ordered where rp.room_id=v_room_id and rp.user_id=ordered.user_id;
 update public.room_ai_players ai set turn_order=(v_human_count+ordered.position-1)::smallint from(select source.id,pg_catalog.row_number()over(order by source.bot_number)position from public.room_ai_players source where source.room_id=v_room_id)ordered where ai.room_id=v_room_id and ai.id=ordered.id;
 update public.room_states rs set game_state=p_game_state,state_version=1 where rs.room_id=v_room_id and rs.game_state is null and rs.state_version=0;update public.rooms r set status='active' where r.id=v_room_id and r.status='lobby';return query select v_room_id,v_room_code,'active'::text,1::bigint;
end;$$;

create or replace function public.remove_room_ai_player_server(p_room_code text,p_user_id uuid,p_ai_player_id uuid)
returns table(room_code text,ai_player_id uuid,removed boolean)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_host uuid;v_status text;v_deleted uuid;
begin
 if p_user_id is null or p_ai_player_id is null then raise exception using errcode='22023',message='Invalid AI player request';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' then raise exception using errcode='22023',message='Invalid AI player request';end if;
 select r.id,r.host_user_id,r.status into v_room_id,v_host,v_status from public.rooms r join public.games g on g.id=r.game_id and g.status='active' and g.slug='worship-me' where r.code=v_room_code for update of r;if not found or not exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.user_id=p_user_id)then raise exception using errcode='P0002',message='Room not found or unavailable';end if;if v_host<>p_user_id then raise exception using errcode='P0003',message='Only the host can manage AI players';end if;if v_status<>'lobby' then raise exception using errcode='P0004',message='Lobby is unavailable';end if;
 delete from public.room_ai_players ai where ai.room_id=v_room_id and ai.id=p_ai_player_id returning ai.id into v_deleted;if v_deleted is null then raise exception using errcode='P0002',message='AI player not found';end if;return query select v_room_code,v_deleted,true;
end;$$;

create or replace function public.set_room_ai_player_color_server(p_room_code text,p_user_id uuid,p_ai_player_id uuid,p_player_color text)
returns table(room_code text,ai_player_id uuid,player_color text,changed boolean)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_game_id uuid;v_host uuid;v_status text;v_color text;v_current text;
begin
 if p_user_id is null or p_ai_player_id is null then raise exception using errcode='22023',message='Invalid AI player request';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));v_color:=pg_catalog.btrim(p_player_color);if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' or v_color is null or v_color<>p_player_color or pg_catalog.char_length(v_color)not between 1 and 40 or v_color!~'^[a-z][a-z0-9-]*$' then raise exception using errcode='22023',message='Invalid AI player request';end if;
 select r.id,r.game_id,r.host_user_id,r.status into v_room_id,v_game_id,v_host,v_status from public.rooms r join public.games g on g.id=r.game_id and g.status='active' and g.slug='worship-me' where r.code=v_room_code for update of r;if not found or not exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.user_id=p_user_id)then raise exception using errcode='P0002',message='Room not found or unavailable';end if;if v_host<>p_user_id then raise exception using errcode='P0003',message='Only the host can manage AI players';end if;if v_status<>'lobby' then raise exception using errcode='P0004',message='Lobby is unavailable';end if;
 select ai.player_color into v_current from public.room_ai_players ai where ai.room_id=v_room_id and ai.id=p_ai_player_id;if not found then raise exception using errcode='P0002',message='AI player not found';end if;if v_current=v_color then return query select v_room_code,p_ai_player_id,v_current,false;return;end if;
 if not exists(select 1 from public.game_player_colors c where c.game_id=v_game_id and c.color=v_color)or exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.player_color=v_color)or exists(select 1 from public.room_ai_players ai where ai.room_id=v_room_id and ai.id<>p_ai_player_id and ai.player_color=v_color)then raise exception using errcode='P0006',message='Player color unavailable';end if;
 begin update public.room_ai_players ai set player_color=v_color where ai.room_id=v_room_id and ai.id=p_ai_player_id;exception when unique_violation then raise exception using errcode='P0006',message='Player color unavailable';end;return query select v_room_code,p_ai_player_id,v_color,true;
end;$$;

create or replace function public.set_room_ai_player_strategy_server(p_room_code text,p_user_id uuid,p_ai_player_id uuid,p_bot_strategy text)
returns table(room_code text,ai_player_id uuid,bot_strategy text,changed boolean)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_host uuid;v_status text;v_current text;
begin
 if p_user_id is null or p_ai_player_id is null or p_bot_strategy is null or p_bot_strategy not in('random','growth','templeRush','balanced')then raise exception using errcode='22023',message='Invalid AI player request';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' then raise exception using errcode='22023',message='Invalid AI player request';end if;
 select r.id,r.host_user_id,r.status into v_room_id,v_host,v_status from public.rooms r join public.games g on g.id=r.game_id and g.status='active' and g.slug='worship-me' where r.code=v_room_code for update of r;if not found or not exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.user_id=p_user_id)then raise exception using errcode='P0002',message='Room not found or unavailable';end if;if v_host<>p_user_id then raise exception using errcode='P0003',message='Only the host can manage AI players';end if;if v_status<>'lobby' then raise exception using errcode='P0004',message='Lobby is unavailable';end if;
 select ai.bot_strategy into v_current from public.room_ai_players ai where ai.room_id=v_room_id and ai.id=p_ai_player_id;if not found then raise exception using errcode='P0002',message='AI player not found';end if;if v_current=p_bot_strategy then return query select v_room_code,p_ai_player_id,v_current,false;return;end if;update public.room_ai_players ai set bot_strategy=p_bot_strategy where ai.room_id=v_room_id and ai.id=p_ai_player_id;return query select v_room_code,p_ai_player_id,p_bot_strategy,true;
end;$$;

create or replace function public.join_room_server(p_room_code text,p_user_id uuid,p_display_name text)
returns table(room_id uuid,room_code text,game_id uuid,status text,joined_new boolean)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_game_id uuid;v_status text;v_display_name text;v_max_players smallint;v_player_count bigint;v_ai_count bigint;v_lock_room_id uuid;v_is_target_member boolean;v_old_lobby_ids uuid[]:=array[]::uuid[];v_lock_room_ids uuid[]:=array[]::uuid[];
begin
 if p_user_id is null then raise exception using errcode='22023',message='User is required';end if;v_display_name:=pg_catalog.btrim(p_display_name);if v_display_name is null or pg_catalog.char_length(v_display_name)not between 1 and 50 then raise exception using errcode='22023',message='Invalid display name';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' then raise exception using errcode='22023',message='Invalid room code';end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_user_id::text,2010003::bigint));select coalesce(pg_catalog.array_agg(existing.existing_room_id order by existing.existing_room_id),array[]::uuid[])into v_old_lobby_ids from(select distinct r.id as existing_room_id from public.rooms r join public.room_players rp on rp.room_id=r.id where rp.user_id=p_user_id and r.status='lobby')existing;select r.id into v_room_id from public.rooms r where r.code=v_room_code;select coalesce(pg_catalog.array_agg(affected.affected_room_id order by affected.affected_room_id),array[]::uuid[])into v_lock_room_ids from(select old_rooms.old_room_id as affected_room_id from pg_catalog.unnest(v_old_lobby_ids)old_rooms(old_room_id)union select v_room_id where v_room_id is not null)affected;foreach v_lock_room_id in array v_lock_room_ids loop perform 1 from public.rooms r where r.id=v_lock_room_id for update;end loop;
 select r.id,r.code,r.game_id,r.status,g.max_players into v_room_id,v_room_code,v_game_id,v_status,v_max_players from public.rooms r join public.games g on g.id=r.game_id and g.status='active' where r.id=v_room_id;if v_room_id is null or v_status<>'lobby' then raise exception using errcode='P0002',message='Room not found or unavailable';end if;select exists(select 1 from public.room_players rp where rp.room_id=v_room_id and rp.user_id=p_user_id)into v_is_target_member;
 if not v_is_target_member then select pg_catalog.count(*)into v_player_count from public.room_players rp where rp.room_id=v_room_id;select pg_catalog.count(*)into v_ai_count from public.room_ai_players ai where ai.room_id=v_room_id;if v_player_count+v_ai_count>=v_max_players then raise exception using errcode='P0003',message='Room is full';end if;end if;
 foreach v_lock_room_id in array v_old_lobby_ids loop if v_lock_room_id<>v_room_id then perform * from ngsllc_private.depart_lobby_member(v_lock_room_id,p_user_id);end if;end loop;if v_is_target_member then update public.room_players rp set display_name=v_display_name,last_seen_at=pg_catalog.now()where rp.room_id=v_room_id and rp.user_id=p_user_id;else insert into public.room_players(room_id,user_id,display_name,player_color,turn_order,is_ready)values(v_room_id,p_user_id,v_display_name,null,null,false);end if;return query select v_room_id,v_room_code,v_game_id,v_status,not v_is_target_member;
end;$$;

create or replace function public.set_player_color_server(p_room_code text,p_user_id uuid,p_player_color text)
returns table(room_id uuid,room_code text,player_color text,changed boolean)
language plpgsql security invoker set search_path='' as $$
declare v_room_id uuid;v_room_code text;v_game_id uuid;v_room_status text;v_requested_color text;v_current_color text;v_member_found boolean;
begin
 if p_user_id is null then raise exception using errcode='22023',message='User is required';end if;v_room_code:=pg_catalog.upper(pg_catalog.btrim(p_room_code));if v_room_code is null or pg_catalog.char_length(v_room_code)not between 6 and 10 or v_room_code!~'^[A-Z0-9]+$' then raise exception using errcode='22023',message='Invalid room code';end if;if p_player_color is not null then v_requested_color:=pg_catalog.btrim(p_player_color);if v_requested_color<>p_player_color or pg_catalog.char_length(v_requested_color)not between 1 and 40 or v_requested_color!~'^[a-z][a-z0-9-]*$' then raise exception using errcode='22023',message='Invalid player color';end if;end if;
 select r.id,r.code,r.game_id,r.status into v_room_id,v_room_code,v_game_id,v_room_status from public.rooms r join public.games g on g.id=r.game_id and g.status='active' where r.code=v_room_code for update of r;if v_room_id is null or v_room_status<>'lobby' then raise exception using errcode='P0002',message='Room not found or unavailable';end if;select rp.player_color into v_current_color from public.room_players rp where rp.room_id=v_room_id and rp.user_id=p_user_id;v_member_found:=found;if not v_member_found then raise exception using errcode='P0002',message='Room not found or unavailable';end if;
 if v_requested_color is null then if v_current_color is null then return query select v_room_id,v_room_code,null::text,false;return;end if;update public.room_players rp set player_color=null,is_ready=false where rp.room_id=v_room_id and rp.user_id=p_user_id;return query select v_room_id,v_room_code,null::text,true;return;end if;if not exists(select 1 from public.game_player_colors supported where supported.game_id=v_game_id and supported.color=v_requested_color)then raise exception using errcode='22023',message='Invalid player color';end if;if v_current_color=v_requested_color then return query select v_room_id,v_room_code,v_current_color,false;return;end if;
 if exists(select 1 from public.room_players other_player where other_player.room_id=v_room_id and other_player.user_id<>p_user_id and other_player.player_color=v_requested_color)or exists(select 1 from public.room_ai_players ai where ai.room_id=v_room_id and ai.player_color=v_requested_color)then raise exception using errcode='P0003',message='Player color unavailable';end if;begin update public.room_players rp set player_color=v_requested_color,is_ready=false where rp.room_id=v_room_id and rp.user_id=p_user_id;exception when unique_violation then raise exception using errcode='P0003',message='Player color unavailable';end;return query select v_room_id,v_room_code,v_requested_color,true;
end;$$;

-- Reassert the trusted-server-only execution boundary after replacement.
revoke execute on function public.add_room_ai_player_server(text,uuid) from public, anon, authenticated, service_role;
grant execute on function public.add_room_ai_player_server(text,uuid) to service_role;

revoke execute on function public.start_game_server(text,uuid,jsonb,jsonb) from public, anon, authenticated, service_role;
grant execute on function public.start_game_server(text,uuid,jsonb,jsonb) to service_role;

revoke execute on function public.remove_room_ai_player_server(text,uuid,uuid) from public, anon, authenticated, service_role;
grant execute on function public.remove_room_ai_player_server(text,uuid,uuid) to service_role;

revoke execute on function public.set_room_ai_player_color_server(text,uuid,uuid,text) from public, anon, authenticated, service_role;
grant execute on function public.set_room_ai_player_color_server(text,uuid,uuid,text) to service_role;

revoke execute on function public.set_room_ai_player_strategy_server(text,uuid,uuid,text) from public, anon, authenticated, service_role;
grant execute on function public.set_room_ai_player_strategy_server(text,uuid,uuid,text) to service_role;

revoke execute on function public.join_room_server(text,uuid,text) from public, anon, authenticated, service_role;
grant execute on function public.join_room_server(text,uuid,text) to service_role;

revoke execute on function public.set_player_color_server(text,uuid,text) from public, anon, authenticated, service_role;
grant execute on function public.set_player_color_server(text,uuid,text) to service_role;

