export type {ActiveGameStateRequest,ActiveGameStateResult,CreateRoomRequest,CreateRoomResult,GameRecord,JoinRoomRequest,JoinRoomResult,LeaveRoomRequest,LeaveRoomResult,RoomPlayerRecord,RoomRecord,RoomStateRecord,SetPlayerColorRequest,SetPlayerColorResult,SetPlayerReadyRequest,SetPlayerReadyResult,StartGameRequest,StartGameResult} from './types';
export {ensureAnonymousSession,PlatformAuthError,type AuthenticatedPlatformSession} from './auth/session';
export {createRoom,CreateRoomError} from './rooms/createRoom';
export {createJoinAction,joinRoom,JoinRoomError,normalizeRoomCode} from './rooms/joinRoom';
export {createLeaveAction,leaveRoom,LeaveRoomError} from './rooms/leaveRoom';
export {createSetPlayerColorAction,setPlayerColor,SetPlayerColorError} from './rooms/setPlayerColor';
export {createSetPlayerReadyAction,setPlayerReady,SetPlayerReadyError} from './rooms/setPlayerReady';
export {createStartGameAction,startGame,StartGameError} from './rooms/startGame';
export {createGetActiveGameStateAction,getActiveGameState,ActiveGameStateError} from './rooms/getActiveGameState';
export {getSupabaseClient} from './supabase/client';
export {listActiveGames,GamesCatalogError,type CatalogGame} from './games/catalog';
export {getLobby,LobbyReadError,type Lobby,type LobbyPlayer} from './rooms/lobby';
